### ISSUE TITLE
IDLC: syntax error on "typedef struct"

### ISSUE THREAD

**Issue by TumbleOwlee** [eclipse-cyclonedds/cyclonedds#1003]
There seems to be an issue with the handling of `typedef struct` in the generation with `idlc`. A simple example is given here:
```c
#ifndef DATA_TYPES
#define DATA_TYPES
module some_module
{
    typedef struct SomeIdentifier
    {
      long id;
      long type;
    } SomeIdentifier_t;

    struct ModeCommand_T
    {
      SomeIdentifier_t rId;
      SomeIdentifier_t sId;
      long num;
    };

#pragma keylist ModeCommand_T rId.id rId.type
};
#endif
```
This fails with `typedef_struct.idl:5:13: syntax error` and is fixed by removing the `typedef` all together. To verify that I haven't done any IDL mistakes, I checked it also using the RTI and Vortex generators. Both are successful.

**Comment by k0ekk0ek** [comment]
@TumbleOwlee, @trittsv, I've created #1068 that solves this particular issue.
