### ISSUE TITLE
!NDEBUG and DDSRT_STATIC_ASSERT (sizeof (struct bwhc_iter) <= sizeof (struct whc_sample_iter)) fails on i386 and others

### ISSUE THREAD

**Issue by roehling** [eclipse-cyclonedds/cyclonedds#1009]
Apparently, the additional debug members make `struct bwhc_iter` too large on some 32 bit architectures, probably due to unfortunate padding requirements. I found that compilation works with `-DNDEBUG`.

Given that  `NDEBUG` is a standard symbol that also disables all asserts from `<assert.h>`,  maybe it would be better to have a dedicated macro such as `DDS_DEBUG` with inverted logic to enable debug members in public data structures (I assume there are publicly visible differences because `#ifndef NDEBUG` is used in structs which are defined in publicly installed headers).

Such a define could also be exported by the CMake config with `target_compile_definitions(ddsc PUBLIC $<$<CONFIG:Debug>:DDS_DEBUG>`

**Comment by eboasson** [comment]
Fixed by #1295 ! 🥳
