### ISSUE TITLE
Can cyclonedds and Fast-RTPS communicate with each other?

### ISSUE THREAD

**Issue by fourtech** [eclipse-cyclonedds/cyclonedds#1020]
I want to setting up an cyclonedds publisher with a Fast-DDS subscriber, or an Fast-DDS publisher with a cyclonedds subscriber. But it can not discovery each other.
Can cyclonedds and Fast-RTPS communicate with each other?

**Comment by eboasson** [comment]
It gets tested every night in the ROS 2 CI, so no, there are no issues to get Cyclone DDS and Fast-DDS / Fast-RTPS (the two are the same as far as the networking parts are concerned) to communicate.

I would recommend looking at the network interfaces (configured with General/NetworkInterfaceAddress in Cyclone DDS), presence or absence of multicast support (in part a property of the network, but also controlled by General/AllowMulticast) and, in the absence of multicast, the list of addresses probed during discovery (Discovery/Peers/Peer...).

**Comment by fourtech** [comment]
Thanks for replying.
I try run cyclonedds.HelloworldSubscriber and fastdds.DDSDynamicHelloWorldExample publisher
But I receive the following：
dq.builtin: data(builtin, vendor 1.15): 10fefa5:5ab08909:1000000:3c2 #1: deserialization failed

**Comment by eboasson** [comment]
Interesting, I wouldn't have been surprised if it had been application (chances are that the Fast-DDS example uses a different type from the Cyclone DDS example), but there is usually no issue dealing with discovery data. Usually. I have seen some strange junk getting published ... (and we've also had to fix an incorrect serialization of an odd-ball QoS setting in Cyclone not so long ago).

It maythat running cyclone with parameter-list tracing enabled (i.e., `CYCLONEDDS_URI="<Tr><C>trace,plist</></>" ...`) is enough to find out what exactly it considers invalid. If you run it like that and search for "deserialization failed" then there should be some data just above it.

What is also useful is to run Wireshark, capture the packet and study it. If you have no problem with sharing those files on GitHub, then we can have a look as well.
