### ISSUE TITLE
Passing ROS2 services between RTI and CycloneDDS

### ISSUE THREAD

**Issue by eranroll** [eclipse-cyclonedds/cyclonedds#1034]
Hi,

Is this option supported? From what I have tried in most cases the services will not return the response, or will never become available. Is that supported right now in ROS Galactic versions and RTI Connext 6.0.1?

If it is supported, is there any specific DDS xml configuration that can make it work, which isn't the default config?

Attached is a log of CycloneDDS (finest) when the server is the Cyclone Node, and the client (who asked the service) is RTI, and the XML I am using:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <Compatibility>
            <AssumeRtiHasPmdEndpoints>true</AssumeRtiHasPmdEndpoints>
            <ExplicitlyPublishQosSetToDefault>true</ExplicitlyPublishQosSetToDefault>
            <StandardsConformance>lax</StandardsConformance>
        </Compatibility>
        <General>
            <NetworkInterfaceAddress>auto</NetworkInterfaceAddress>
            <AllowMulticast>false</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>1450B</FragmentSize>
            <Transport>udp</Transport>
        </General>
        <Discovery>
            <Peers>
                <Peer address="172.17.0.2"/>
            </Peers>
            <ParticipantIndex>auto</ParticipantIndex>
        </Discovery>
        <Tracing>
            <Verbosity>finest</Verbosity>
            <OutputFile>/tmp/service_rti_debug.txt</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
[service_rti_debug.txt](https://github.com/eclipse-cyclonedds/cyclonedds/files/7549361/service_rti_debug.txt)

Regards,
Eran

**Comment by eboasson** [comment]
ROS 2 service handling is not part of the DDS implementation but part of the RMW implementation, so this isn't an issue of Cyclone DDS itself. The short answer is that the way service invocations are handled is incompatible between the various RMW layers.

The general topic of interoperability between clients and services of different RMW layers in ROS 2 comes up every now and then. I don't have a reference handy, but I'm sure Google can help you. That's where I'd take this.
