### ISSUE TITLE
Setting ExplicitlyPublishQosSetToDefault to true causes malloc error

### ISSUE THREAD

**Issue by eranroll** [eclipse-cyclonedds/cyclonedds#1035]
Hi,

I am running my own node inside an arm64 ros2 galactic docker. Whenever I set true in my XML, I get an exception in my constructor, when trying to create publishers and subscribers.

I am using this parameter since I want to achieve full communication between a node running RTI's RMW and a node running Cyclone DDS.

Any idea what might be the problem?

My XML:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <Compatibility>
            <AssumeRtiHasPmdEndpoints>true</AssumeRtiHasPmdEndpoints>
            <ExplicitlyPublishQosSetToDefault>true</ExplicitlyPublishQosSetToDefault>
            <StandardsConformance>lax</StandardsConformance>
        </Compatibility>
        <General>
            <NetworkInterfaceAddress>auto</NetworkInterfaceAddress>
            <AllowMulticast>false</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>1450B</FragmentSize>
            <Transport>udp</Transport>
        </General>
        <Discovery>
            <Peers>
                <Peer address="172.17.0.2"/>
            </Peers>
            <ParticipantIndex>auto</ParticipantIndex>
        </Discovery>
        <Tracing>
            <Verbosity>finest</Verbosity>
            <OutputFile>/tmp/service_rti_debug.txt</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```

My publisher:
rclcpp::QoS qos(rclcpp::KeepLast{7}); m_droneStatusUpdatePublisher = this->create_publisher<xtra_common_msgs::msg::MapUInt8ToString>("drone_status_update", qos);

Your prompt response is much appreciated.

I have found that this behavior isn't consistent. If I run my node multiple times, sometimes it'll fail with one of these messages, and on in others it will work as expected. For example:
```bash
corrupted size vs. prev_size
```
OR
```bash
malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
```

Regards,
Eran

**Comment by eboasson** [comment]
> I am running my own node inside an arm64 ros2 galactic docker. Whenever I set true in my XML, I get an exception in my constructor, when trying to create publishers and subscribers.
>I am using this parameter since I want to achieve full communication between a node running RTI's RMW and a node running Cyclone DDS.
> Any idea what might be the problem?

The option is not needed, so the simple work around is to remove it. That said, it shouldn't crash.

I've quickly tried to reproduce it with the "address sanitizer" enabled (though using only Cyclone DDS and without ROS2, so some details will be different), but to no avail. If you happen to be building from source, could you try an address sanitizer run?

**Comment by thijsmie** [comment]
Cannot reproduce and no info provided. @eranroll if you get back with more information I will reopen.
