### ISSUE TITLE
Questions: is it possible that tsd_thread_state would be changed by two thread?

### ISSUE THREAD

**Issue by zhangyaothu** [eclipse-cyclonedds/cyclonedds#1043]
I want to deploy cyclonedds on stm32h745zi-q nucleo board.
Under cyclonedds, freertos and lwip are integrated.
The applicatioin starts to run for a while, but then stops at `assert (thread_is_awake ());`.
After that I dive into the code and find a question as below.
```c
// q_thread.c release 0.8.0
static uint32_t create_thread_wrapper (void *ptr)
{
  struct thread_state1 * const ts1 = ptr;
  struct ddsi_domaingv const * const gv = ddsrt_atomic_ldvoidp (&ts1->gv);
  if (gv)
    GVTRACE ("started new thread %"PRIdTID": %s\n", ddsrt_gettid (), ts1->name);
  assert (ts1->state == THREAD_STATE_INIT);
  tsd_thread_state = ts1;
  ddsrt_mutex_lock (&thread_states.lock);                // get lock
  ts1->state = THREAD_STATE_ALIVE;
  ddsrt_mutex_unlock (&thread_states.lock);              // release lock
  const uint32_t ret = ts1->f (ts1->f_arg);              // what if tsd_thread_state is changed by another thread 
                                                         // and this thread calls lookup_thread state ? a wrong thread state pointer ?
  ddsrt_mutex_lock (&thread_states.lock);                // get lock
  ts1->state = THREAD_STATE_STOPPED;
  ddsrt_mutex_unlock (&thread_states.lock);              // release lock
  tsd_thread_state = NULL;
  return ret;
}
```

**Comment by zhangyaothu** [comment]
I change the source code as below and test again, the application runs well.
```c
static uint32_t create_thread_wrapper (void *ptr)
{
  struct thread_state1 * const ts1 = ptr;
  struct ddsi_domaingv const * const gv = ddsrt_atomic_ldvoidp (&ts1->gv);
  if (gv)
    GVTRACE ("started new thread %"PRIdTID": %s\n", ddsrt_gettid (), ts1->name);
  assert (ts1->state == THREAD_STATE_INIT);
  ddsrt_mutex_lock (&thread_states.lock); // TODO
  tsd_thread_state = ts1;
  //ddsrt_mutex_lock (&thread_states.lock);
  ts1->state = THREAD_STATE_ALIVE;
  //ddsrt_mutex_unlock (&thread_states.lock);
  const uint32_t ret = ts1->f (ts1->f_arg);
  //ddsrt_mutex_lock (&thread_states.lock);
  ts1->state = THREAD_STATE_STOPPED;
  //ddsrt_mutex_unlock (&thread_states.lock);
  tsd_thread_state = NULL;
  ddsrt_mutex_unlock (&thread_states.lock); // TODO
  return ret;
}
```

**Comment by eboasson** [comment]
Hi @zhangyaothu, there is of course always the possibility that there is a real bug and that it asserts correctly on this `thread_is_awake ()`. Do you have a stack trace when this happens?

Secondly, the `tsd_thread_state` is a thread-specific variable ("tsd" is an acronym of "thread-specific data") and so each thread has its own copy. This relies on some compiler support, which all works out-of-the-box on the main platforms, but I do remember that we had to do something special on at least one FreeRTOS port. If that doesn't work out as it should, the different threads will be messing with each other's `tsd_thread_state` and then, indeed, you'll run into this sort of problem.

There is this note: https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/dev/freertos.md#thread-local-storage, that should give you starting point.

The change you suggest means that `thread_states.lock` mutex remains locked for the entire lifetime of the thread. That will cause problems, because you really do need multiple threads to function. In particular, without the "recv" and "tev" threads functioning properly, discovery won't work.

**Comment by zhangyaothu** [comment]
Thanks @eboasson , just as you mentioned, after the modifications, "tev" and "recv" threads do not function.
GCC for STM32 perhaps does not support thread local storage. But instead, FreeRTOS provides a method, [Thread Local Storage Pointers](https://www.freertos.org/thread-local-storage-pointers.html).
In ddsrt/threads/freertos/threads.c, I add two APIs as below.
```c
#if defined (STM32H745xx) && defined(WITH_FREERTOS)
dds_return_t
ddsrt_thread_local_storage_push(int index, void *value){
  assert(index < configNUM_THREAD_LOCAL_STORAGE_POINTERS);

  vTaskSetThreadLocalStoragePointer(xTaskGetCurrentTaskHandle(), index, value);
  return DDS_RETCODE_OK;
}

dds_return_t
ddsrt_thread_local_storage_pull(int index, void **value){
  (void)value; // avoid warning
  assert(index < configNUM_THREAD_LOCAL_STORAGE_POINTERS);

  *value = pvTaskGetThreadLocalStoragePointer(xTaskGetCurrentTaskHandle(), index);
  return DDS_RETCODE_OK;
}
#endif
```
tsd_thread_state will be stored in corresponding thread local storage space when created.
```c
static uint32_t create_thread_wrapper (void *ptr)
{
  struct thread_state1 * const ts1 = ptr;
  struct ddsi_domaingv const * const gv = ddsrt_atomic_ldvoidp (&ts1->gv);
  if (gv)
    GVTRACE ("started new thread %"PRIdTID": %s\n", ddsrt_gettid (), ts1->name);
  assert (ts1->state == THREAD_STATE_INIT);
  tsd_thread_state = ts1;
  ddsrt_thread_local_storage_push(0, (void*)tsd_thread_state);
  ddsrt_mutex_lock (&thread_states.lock);
  ts1->state = THREAD_STATE_ALIVE;
  ddsrt_mutex_unlock (&thread_states.lock);
  const uint32_t ret = ts1->f (ts1->f_arg);
  ddsrt_mutex_lock (&thread_states.lock);
  ts1->state = THREAD_STATE_STOPPED;
  ddsrt_mutex_unlock (&thread_states.lock);
  tsd_thread_state = NULL;
  return ret;
}
```
And tsd_thread_state will be pulled when used.
```c
DDS_INLINE_EXPORT inline struct thread_state1 *lookup_thread_state (void) {
  assert(ddsrt_thread_local_storage_pull(0, (void**)&tsd_thread_state) == DDS_RETCODE_OK);
  struct thread_state1 *ts1 = tsd_thread_state;
  if (ts1)
    return ts1;
  else
    return lookup_thread_state_real ();
}
```
But I still wonder why lookup_thread_state_real functions well, another lookup_thread_state is wrappered? And if tsd_thread_state is not null, it will still firstly be used.

**Comment by eboasson** [comment]
Happy to hear that you solved the issue, @zhangyaothu. I think at least with gcc there is a way where you don't need to add calls to these push/pull functions yourself (and in `lookup_thread_state`, I do wonder what will happen when multiple threads execute this at the same time).

The reason for using `tsd_thread_state` with a wrapper function is that `lookup_thread_state_real` has to scan the list of known threads, looking for the current thread's identifier (and possibly initializing a new slot if the thread wasn't known yet). The thread-specific data is generally pretty well-optimized nowadays, usually it is done by offsetting off a register reserved by the ABI.
