### ISSUE TITLE
OpenSplice and Cyclone

### ISSUE THREAD

**Issue by zephod77** [eclipse-cyclonedds/cyclonedds#1057]
I have an old system that uses OpenSplice DDS and I would like to update it to use CycloneDDS.

First question; is it possible to run an OpenSplice based app and have it communicate with a CycloneDDS based app on the same host? I assume that it is and if so is there a tool that will take an OpenSplice configuration file and create the corresponding Cyclone conifg file?

**Comment by k0ekk0ek** [comment]
Hi @zephod77, yes OpenSplice and Cyclone will communicate just fine. As a matter of fact the DDSI-RTPS stack in Cyclone evolved from the stack that's in OpenSplice (both written by @eboasson for the most part). Fun fact: the *cyclonedds-cxx* is also an evolution of the C++11 binding found in OpenSplice. I should note though that Cyclone will not be able to communicate over shared memory with OpenSplice, but I think you guessed that already(?) Also note that Cyclone does not communicate the proprietary type descriptors used by OpenSplice. Basically that means that if you're accustomed to some of the OpenSplice tools, they may not be able to correctly discover or name the fields in the topic. In Cyclone we have our own type discovery until #904 lands. Some of the tools have been ported to *cyclonedds-python*, but if something isn't there, the Python binding makes it extremely easy to write some simple diagnostic tooling yourself until we manage to provide additional tools.

As for the configuration file, I think you don't need to convert it at all. @eboasson took great care to make that part backwards compatible. If it does complain about the configuration though, the [options.md](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md) file provides an up-to-date description of all options. If you have a fancy XML editor with support for XSD validation, [cyclonedds.xsd](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/etc/cyclonedds.xsd) can be used to validate the configuration file (not backwards compatible tags). Cyclone should print warnings if it doesn't understand the configuration options provided in `CYCLONEDDS_URI`.

Let me know if you have any further questions.

**Comment by zephod77** [comment]
Hi @k0ekk0ek, thanks for the detailed answer and in particular the links to options.md. 

As for the config file being backward compatible... well I guess it depends how far back! In my case not so much. 

The root element changed from OpenSplice to CycloneDDS, The Domain.Id element has become an attribute, the Domain.Description element is not supported any more, the Domain.SingleProcess element is not supported any more and the Domain.Service element is not supported any more.
The DDSI2Service.General.NetworkInterface element has become Domain.General.NetworkInterface and the DDSI2Service.Discovery.MaxAutoParticipantIndex element has become Domain.Discovery.MaxAutoParticipant.

I was able to change everything by examining the error messages and the options.md file.

**Comment by eboasson** [comment]
Hi @zephod77, the `Domain` element indeed changed a lot, that's where Cyclone and OpenSplice configurations really differ. Among the many reasons is, for example, that in Cyclone the networking bit isn't a service that needs to be started. Another major change is that Cyclone configuration files can contain configurations for multiple independent domains.

What should work (perhaps not perfectly, but pretty close) is copy-pasting the elements contained in an OpenSplice "DDSI2Service" section into the Cyclone "Domain" section. That seems to match with the changes you describe.

I suppose we should've remembered all this before writing that "it just works" when clearly it didn't. Still, I am very happy that you did manage and that the error messages and documentation helped you figure it out.

**Comment by zephod77** [comment]
So now I need some pointers on troubleshooting. I created a small program based on the helloworld subscriber example that just listens for a particular type of message and prints when it receives something. I know the msg is being sent because I have an OpenSplice based tool that can see it but my cyclone program does not see it.
Are there any cyclone tools that can, for example, see if any msgs are being sent on that domain id or do I need to fire up tcpdump?

**Comment by zephod77** [comment]
Well I found one issue. We have an IDL file that contains something like this:
```
module A
{
    struct M
    {
        boolean m;
    };
    #pragma keylist M
};
```
The old OpenSplice IDL compiler had no problem with this but the cyclone version generates an error:

> 5:17: Declaration 'm' collides with earlier an declaration of 'M'

The spec [https://www.omg.org/spec/IDL/4.2/PDF], para 7.2.3.1, Collision Rules, isn't clear on this particular case and I'm a bit surprised as referring to M.m is perfectly OK. 
Is this an issue with the IDL parser?

**Comment by eboasson** [comment]
@zephod77, 7.5.2, Scoping Rules and Name Resolution, says (among other things):
> The name of a module, structure, union, map, interface, value type, event type, exception or home may not be redefined within the immediate scope of the module, structure, union, map, interface, value type, event type, exception or home. For example:
> ```
> module M {
>   typedef short M;    // Error: M is the name of the module...
>                       // ...in the scope of which the typedef is.
>   interface I {
>      void i (in short j); // Error: i clashes with the interface name I
>   }; };
> ```
Your `struct M { boolean m; };` is quite similar, but a member name is not among the list of things that may not be redefined within the "immediate scope of ...". I agree with you that it ought to be allowed, but there are people who know the IDL rules better than I do (@e-hndrks is one of them). Perhaps they can comment.

Cyclone's IDL `-fcase-sensitive` option makes its name resolution case-sensitive (needed for some issues in ROS 2), and that would perhaps suffice as a work-around while the subject is debated and the compiler changed (assuming that the conclusion is that this is a bug).

**Comment by eboasson** [comment]
> Are there any cyclone tools that can, for example, see if any msgs are being sent on that domain id or do I need to fire up tcpdump?

Yes and no. The problem hinges on type discovery: tooling that can't subscribe to any topic that has been published is next to useless. OpenSplice does type discovery has done so since the very beginning, but it uses a proprietary mechanism and representation. Cyclone is not going to implement that, and is in fact on the verge of getting  "proper", spec-compliant type discovery (#904), and then the Python binding will make it trivial to subscribe to any topic (and the `pubsub` tool there will provide that on the command-line). But that's not going to help you ...

If you have the IDL, I'd advise using the python binding, but that's just because it is (even) simpler to subscribe & print the data in python than in C or C++.

In any case, whether that is useful at all also depends on where one suspects the problem one is investigating to be — that is, if the reason there is no data flowing has to do with discovery and/or QoS matching, the above is not going to help you. If you look at `ddsls` (also in the python binding), that's the easiest way to check whether discovery completed. There is also a variant of that for OpenSplice, at https://github.com/eboasson/opensplice-tools.

**Comment by eboasson** [comment]
I have studied the spec a bit further with @e-hndrks, trying to find a definitive answer. I have come to the conclusion that all of the above forms are allowed. The argument is that the section 7.5.2 says:
> The name of a module, structure [...] may not be redefined within the immediate scope of the module, structure [...].

which hinges upon the definition of "to define" (perhaps it is not a coincidence that CORBA is a Clinton-era spec 🤔). I am of the opinion that the enumerating of members is part of the definition of a struct type, but that these members do not constitute definitions themselves. This opinion is supported by the way the word "definition" is used in the grammar. 

It follows that I conclude `struct a { boolean a; };` should be allowed and that the current behaviour of the IDL compiler is erroneous.

**Comment by eboasson** [comment]
It turns out the OMG IDL-to-C++11 mapping makes the legality `struct a { boolean a; };` a moot point, because there it can't work ... see also https://github.com/eclipse-cyclonedds/cyclonedds/pull/1068#discussion_r774392112

I believe this issue has come to a conclusion, so I am closing it.
