### ISSUE TITLE
Make type meta-data generator available for IDLC back-ends

### ISSUE THREAD

**Issue by dennis-adlink** [eclipse-cyclonedds/cyclonedds#1067]
The IDLC generator for type meta-data, that will be added by PR #904, generates CDR data for XTypes type identifiers and type objects. This type meta-data is used in the C backend which is embedded in IDLC, but this functionality should also be made available for other backends of the IDL compiler, in order to include it in the topic descriptors. 

The current implementation has a function `print_type_meta_ser` in IDLC that for a provided `idl_node`, writes C defines with the CDR meta-data for this (topic top-level) type. These defines are used in the topic descriptors. Exporting the existing function so it can be used in other back-ends might be an option, but a better approach might be to pass a function pointer to the generators, and refactor the function so it returns the CDR data as byte array.

**Comment by eboasson** [comment]
Fixed by #1112
