### ISSUE TITLE
Communication between different domain ID of DDS in ROS2.

### ISSUE THREAD

**Issue by sumitpaulde** [eclipse-cyclonedds/cyclonedds#1094]
As you already know all the ROS2 nodes are not always on the same DDS domain, for fastdds there are systems handle for different systems, so that communication between dds<-->ros1, dds<-->ros2, ros2<-->ros1, domain_id_5<-->domain_id_15 is possible. https://github.com/eProsima/FastDDS-SH you can have a look here. Is there any way to communicate between different domain_id's? if possible then how?

**Comment by eboasson** [comment]
We rely on [Zenoh](www.zenoh.io) for that — which by the way is also what was used for connecting the cars and the roadside stuff in the Indy Autonomous Challenge (there's a [blog post](https://zenoh.io/blog/2021-09-28-iac-experiences-from-the-trenches/) giving some details).
