### ISSUE TITLE
how to init dds when process is forked？？

### ISSUE THREAD

**Issue by sgf201** [eclipse-cyclonedds/cyclonedds#1097]
there is fork in my app, I test the fork feature of cyclonedds by hellowolrd example.
I add a fork func before participant init , and double all the code to child process as father process

test result like that below:
the father process report a Segmentation fault and quit
why??
"
=== [Subscriber] Waiting for a sample ...
 child  take failed no new write=== [Subscriber child] Received : Message ( 193)
=== [Subscriber child] Received : Message ( 194)
=== [Subscriber child] Received : Message ( 195)
=== [Subscriber child] Received : Message ( 196)
=== [Subscriber child] Received : Message ( 197)
=== [Subscriber child] Received : Message ( 198)
=== [Subscriber child] Received : Message ( 199)
=== [Subscriber child] Received : Message ( 200)
Segmentation fault
worker@slave:~/sgf/cyclonedds/build/bin$ === [Subscriber child] Received : Message ( 201)
=== [Subscriber child] Received : Message ( 202)
"

int ret = fork();
if(ret == 0)
{
  participant = dds_create_participant (DDS_DOMAIN_DEFAULT, NULL, NULL);
  if (participant < 0)
    DDS_FATAL("dds_create_participant: %s\n", dds_strretcode(-participant));

  /* Create a Topic. */
  topic = dds_create_topic (
    participant, &d_proc_state_msg_t_desc, "uos_camera", NULL, NULL);
  if (topic < 0)
    DDS_FATAL("dds_create_topic: %s\n", dds_strretcode(-topic));

  /* Create a reliable Reader. */
  qos = dds_create_qos ();
  dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_SECS (10));
  reader = dds_create_reader (participant, topic, qos, NULL);
  if (reader < 0)
    DDS_FATAL("dds_create_reader: %s\n", dds_strretcode(-reader));
  dds_delete_qos(qos);

  printf ("\n=== [Subscriber] Waiting for a sample ...\n");
  fflush (stdout);

  /* Initialize sample buffer, by pointing the void pointer within
   * the buffer array to a valid sample memory location. */
  samples[0] = HelloWorldData_Msg__alloc ();
  
	dds_sleepfor(DDS_MSECS(5));
//	dds_sleepfor(DDS_MSECS(20));
//	dds_sleepfor(DDS_MSECS(20));
  /* Poll until data has been read. */
  while (true)
  {
    /* Do the actual read.
     * The return value contains the number of read samples. */
    rc = dds_take (reader, samples, infos, MAX_SAMPLES, MAX_SAMPLES);
    if (rc < 0)
      DDS_FATAL("dds_read: %s\n", dds_strretcode(-rc));

    /* Check if we read some data and it is valid. */
    if ((rc > 0) && (infos[0].valid_data))
    {
      /* Print Message. */
      msg = (d_proc_state_msg_t*) samples[0];
      printf ("=== [Subscriber child] Received : ");
      printf ("Message ( %d)\n", msg->data[0]);
      fflush (stdout);
	dds_sleepfor(DDS_MSECS(20));
//      break;
    }
    else
    {
      printf( " child  take failed no new write");/* Polling sleep. */
      dds_sleepfor (DDS_MSECS (20));
    }
}
}
  /* Create a Participant. */
  participant = dds_create_participant (DDS_DOMAIN_DEFAULT, NULL, NULL);
  if (participant < 0)
    DDS_FATAL("dds_create_participant: %s\n", dds_strretcode(-participant));

  /* Create a Topic. */
  topic = dds_create_topic (
    participant, &d_proc_state_msg_t_desc, "uos_camera", NULL, NULL);
  if (topic < 0)
    DDS_FATAL("dds_create_topic: %s\n", dds_strretcode(-topic));

  /* Create a reliable Reader. */
  qos = dds_create_qos ();
  dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_SECS (10));
  reader = dds_create_reader (participant, topic, qos, NULL);
  if (reader < 0)
    DDS_FATAL("dds_create_reader: %s\n", dds_strretcode(-reader));
  dds_delete_qos(qos);

  printf ("\n=== [Subscriber] Waiting for a sample ...\n");
  fflush (stdout);

  /* Initialize sample buffer, by pointing the void pointer within
   * the buffer array to a valid sample memory location. */
  samples[0] = HelloWorldData_Msg__alloc ();
  
	dds_sleepfor(DDS_MSECS(5));
//	dds_sleepfor(DDS_MSECS(20));
//	dds_sleepfor(DDS_MSECS(20));
  /* Poll until data has been read. */
  while (true)
  {
    /* Do the actual read.
     * The return value contains the number of read samples. */
    rc = dds_take (reader, samples, infos, MAX_SAMPLES, MAX_SAMPLES);
    if (rc < 0)
      DDS_FATAL("dds_read: %s\n", dds_strretcode(-rc));

    /* Check if we read some data and it is valid. */
    if ((rc > 0) && (infos[0].valid_data))
    {
      /* Print Message. */
      msg = (d_proc_state_msg_t*) samples[0];
      printf ("=== [Subscriber] Received : ");
      printf ("Message ( %d)\n", msg->data[0]);
      fflush (stdout);
	dds_sleepfor(DDS_MSECS(20));
//      break;
    }
    else
    {
      printf("take failed no new write");/* Polling sleep. */
      dds_sleepfor (DDS_MSECS (20));
    }
  }

**Comment by sgf201** [comment]
there is different result in x64  ubuntu :
the father process can read Message
the child process can not ,but there is no Segmentation fault error

child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write child  take failed no new write=== [Subscriber] Received : Message ( 237)
=== [Subscriber] Received : Message ( 238)
=== [Subscriber] Received : Message ( 239)
=== [Subscriber] Received : Message ( 240)
=== [Subscriber] Received : Message ( 241)
=== [Subscriber] Received : Message ( 242)
=== [Subscriber] Received : Message ( 243)
=== [Subscriber] Received : Message ( 244)
=== [Subscriber] Received : Message ( 245)
=== [Subscriber] Received : Message ( 246)
=== [Subscriber] Received : Message ( 247)
=== [Subscriber] Received : Message ( 248)
=== [Subscriber] Received : Message ( 249)
=== [Subscriber] Received : Message ( 250)
=== [Subscriber] Received : Message ( 251)

**Comment by eboasson** [comment]
That's odd. There is a little bit of initialization happening in the library "constructor" called by the dynamic linker, so I suppose that must be the bit of code that causes the problem. That's done more as a convenience than anything else, except perhaps for setting up the emulation code for atomic operations used by Cyclone but not natively supported by the hardware (they get emulated using mutexes).

For those atomic operations support there is a difference between 32-bit and 64-bit code, so it might explain things if the crash was in 32-bit mode. It would be interesting to see *where* it crashed. If it is in that bit of code, it should be fairly obvious from the stack trace of the crash.

I have no idea yet why there'd be a problem on 64-bit ... I'll see if I can reproduce it.

**Comment by sgf201** [comment]
> 

there are two different problem,first : crash,  the crashed platform is AArch64(tagera)

second : one of the processes father or child can not get msg, the reproduce file is below, it should very easy to reproduce
[helloworld.tar.gz](https://github.com/eclipse-cyclonedds/cyclonedds/files/7839508/helloworld.tar.gz)

**Comment by sgf201** [comment]
the crash problem I reproduce in x64 ubuntu also,it crashed at
cyclonedds/src/core/ddsi/src/q_entity.c :4490   rdguid->prefix = pp->e.guid.prefix;
the file below contain the finest log when it crashed
[debug_sub.txt](https://github.com/eclipse-cyclonedds/cyclonedds/files/7839562/debug_sub.txt)

**Comment by sgf201** [comment]
I test the 1103patch it solve the fork process participant ,but other fork relevant situations work not good ether.
  main () {
    create_participant
    if (fork () == 0)
          create_reader1
    else
          create_reader2
  }
I test the situation above , the reader1 can not get message 

  main () {
    create_participant
    if (fork () == 0)
    {
          create_participant
          create_reader1
    }
    else
          create_reader2
  }
I test the situation above , the reader1 can not get message ether.
@eboasson

**Comment by sgf201** [comment]
[debug_pub.txt](https://github.com/eclipse-cyclonedds/cyclonedds/files/7852441/debug_pub.txt)
main () {
create_participant
if (fork () == 0)
{
dds_delete(participant)
create_participant
create_reader1
}
else
while(1);
}
I test the situation above , the reader1 process crashed and finest log is attached
@eboasson

**Comment by eboasson** [comment]
@sgf201 I am not surprised that fails, and I am not even sure it can be made to work. When you `fork` the process, only the thread calling `fork` exists in the child process (*) and it shares any network sockets with the parent. So you really shouldn't expect the first case (https://github.com/eclipse-cyclonedds/cyclonedds/issues/1097#issuecomment-1010695420) to work. Furthermore I don't think it can be made to work either.

The second case in the same comment similarly means you have a partial copy of an fully initialized DDS stack. In Cyclone participants aren't completely independent to keep the overhead of multiple participants low, and so that one runs into roughly the same problems. It is just a little less obvious.

The last one (https://github.com/eclipse-cyclonedds/cyclonedds/issues/1097#issuecomment-1010713685) looks the most innocent, and it might be possible to get that to work if the `fork` happens at a "good time". It wouldn't be trivial.

So for now, please just don't do that. Your original case should work and I am happy that #1103 does the trick for you. I'll merge that one after pressing the "Comment" button here.

(*) See https://pubs.opengroup.org/onlinepubs/9699919799/functions/fork.html. Solaris pre-POSIX threads was slightly different, but this is the behaviour of all current Unix and Unix-like implementations.

**Comment by sgf201** [comment]
> 

3Q a lot for the socket and process info.
then, I met a problem, I am trying to replace the middle layer of communication  by cyclone dds ,but the process may fork a children process at some case, and the children process need to communicate with other process through middle layer(the old solution base by RCSlib works both in father and child process ). so I need to make sure DDS works both in father and child process, I can do something by pthread_atfork（any thing is ok）, but I can not figure out how I can make it. 
glad to look forward to your kind advice

**Comment by sgf201** [comment]
father process must init DDS before fork,and I think it is normal enough
how could I init DDS in child process
