### ISSUE TITLE
How to enable multi-homing?

### ISSUE THREAD

**Issue by roni-kreinin** [eclipse-cyclonedds/cyclonedds#1130]
I would like to enable multi-homing specifically for ROS2 Galactic such that I can use multiple network interfaces. I have not been able to find any documentation on how to enable this. Is it simply done in the cyclonedds.xml file?

**Comment by eboasson** [comment]
Hi @roni-kreinin, yes, that's correct. It is done by specifying the interfaces in the `General/NetworkInterfaceAddress` setting, separated by a comma.

**Comment by ciandonovan** [comment]
@eboasson does that not simply define a subset of available network interfaces, of which only a single one will be chosen by Cyclone for use?

**Comment by eboasson** [comment]
@ciandonovan no it really means to try and use them all at the same time (probably you'd want to set General/DontRoute as well, at least for the time being, see, e.g., https://github.com/eclipse-cyclonedds/cyclonedds/issues/1190). I suppose it is indeed a bit confusing, given some of the other options.

**Comment by thijsmie** [comment]
Question answered :smile:
