### ISSUE TITLE
ddsi_xqos_valid: DURABILITY invalid on arm32 

### ISSUE THREAD

**Issue by PetervdPerk-NXP** [eclipse-cyclonedds/cyclonedds#1141]
I'm in the process to port cyclonedds to an embedded arm cortex-m7 target using the following toolchain.
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 9-2020-q2-update) 9.3.1 20200408 (release)

I'm trying to run the helloworld subscriber example.
https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/examples/helloworld/subscriber.c

Where it fails on 
https://github.com/eclipse-cyclonedds/cyclonedds/blob/5bd30bc6c2586a3e0be96fc15f588d514347baa2/examples/helloworld/subscriber.c#L35-L37

And I get the following message
```
Thread #1 (Suspended : Breakpoint)	
	ddsi_xqos_valid_strictness() at ddsi_plist.c:2,485 0x43ad1c	
	ddsi_xqos_valid() at ddsi_plist.c:2,501 0x43adf6	
	dds_create_reader_int() at dds_reader.c:583 0x4283da	
	dds_create_reader() at dds_reader.c:787 0x42867c	
	cyclonedds_main() at cyclone.cpp:113 0x426bc8	

126.030000 []         61: ddsi_xqos_valid: DURABILITY invalid
126.050000 []         61: dds_create_reader: Bad Parameter
```

It seems that the valid_generic() function ddsi_plist.c invalides this, but this function is quite complex to to debug.
https://github.com/eclipse-cyclonedds/cyclonedds/blob/5bd30bc6c2586a3e0be96fc15f588d514347baa2/src/core/ddsi/src/ddsi_plist.c#L1472
My own rough guess would be that the padding of memory is different and thus offsets might be incorrect.

Is someone else using a comparable toolchain and can reproduce this issue?

**Comment by eboasson** [comment]
A wild guess: the size of enums. Some embedded ARM toolchains use the smallest integral type that can hold all the declared enum symbols, rather than always mapping it to an `int`. The case(s?) I know of had a compiler switch to always make it use a 32-bit int.

**Comment by PetervdPerk-NXP** [comment]
Thanks for the feedback turns out the arm-none-eabi-gcc toolchain indeed by default enables the short-enum functionality.
Which is quite vaguely described here
https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Structures-unions-enumerations-and-bit-fields-implementation.html

But looking at arm.h in my toolchain is see that `ARM_DEFAULT_SHORT_ENUMS` is defined

A quick solution is to use the -fno-short-enums flag which forces 32-bit int enums, however this might give some linker warnings.

Not sure if there's a portable solution for this accross all platforms but for now this will suffice.

**Comment by wjbbupt** [comment]
Hello, I see that you can cross-compile. I use aarch64 to cross-compile on ubuntu18.04. The compilation fails. I want to learn how you adapt to the arm platform. If it is convenient, can you post the compilation code? Or run the method, thanks a lot!
