### ISSUE TITLE
LICENSE renamed license.txt causing docs/cmake_install.cmake to fail under buildroot

### ISSUE THREAD

**Issue by pscheie** [eclipse-cyclonedds/cyclonedds#1142]
When building cyclonedds under buildroot, it fails at line 49 in docs/cmake_install.cmake tries as it tries to copy the LICENSE file to the target destination:

`CMake Error at docs/cmake_install.cmake:46 (file):`
  `file INSTALL cannot find`
  `"/home/petre/buildroot-2021.02.8.beaglebone/output/build/cyclonedds-ec866a11f66bf7cfac02b024823d92368d4049c8/docs/../LICENSE":`
 ` No such file or directory.`
`Call Stack (most recent call first):`
`  cmake_install.cmake:80 (include)`

Checking the build directory, I can see that LICENSE has been renamed license.txt.  Grepping for license.txt reveals this:

`CMakeCPack.cmake:file(RENAME "${CMAKE_BINARY_DIR}/LICENSE" "${CMAKE_BINARY_DIR}/license.txt")`
`CMakeCPack.cmake:set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_BINARY_DIR}/license.txt")`
`CPackConfig.cmake:set(CPACK_RESOURCE_FILE_LICENSE "/home/petre/buildroot-2021.02.8.beaglebone/output/build/cyclonedds-ec866a11f66bf7cfac02b024823d92368d4049c8/license.txt")`
`CPackSourceConfig.cmake:set(CPACK_RESOURCE_FILE_LICENSE "/home/petre/buildroot-2021.02.8.beaglebone/output/build/cyclonedds-ec866a11f66bf7cfac02b024823d92368d4049c8/license.txt")`

The culprit may be the first line above since it's a RENAME, and when cyclonedds is first cloned out it includes the file LICENSE.  If I manually rename license.txt to LICENSE and then rerun the build, it works.

**Comment by eboasson** [comment]
Fixed by #1200
