### ISSUE TITLE
Cmake Issues

### ISSUE THREAD

**Issue by USAFxPilot21** [eclipse-cyclonedds/cyclonedds#1151]
When trying to run example code I recieve the error:

Could not find a package configuration file provided by "CycloneDDS" with any of the following names:

cycloneddsConfig.cmake
cyclonedds-config.cmake

Anyone know solutions to this problem?

**Comment by eboasson** [comment]
I've always been able to solve such problems by adding the correct directory to the `CMAKE_PREFIX_PATH`. E.g., when building Cyclone, pass `-DCMAKE_INSTALL_PREFIX=/wherever/you/want/to/install/it` to `cmake` and when building an application that "requires" the Cyclone package, make sure to pass to pass `-DCMAKE_PREFIX_PATH=/wherever/you/want/to/install/it` (and if you need to set a path for multiple packages, separate them with semicolons).

**Comment by thijsmie** [comment]
CMake confuses everyone all the time, even if using it for a while its ways can be mysterious.
