### ISSUE TITLE
Child and parent process gets the same domain participant eneity?

### ISSUE THREAD

**Issue by t0ny-peng** [eclipse-cyclonedds/cyclonedds#1160]
Hi there. We found a strange behavior in one of our tests, which can be thought as a ROS2 unit test in our own `rmw_cyclone_dds` package.

The design is that in the test case, `fork` will be called to create a child process. Both the parent and child process will create a DomainParticipant using the same domain id. We want to test that the ROS2 node/data writer/data reader created in child process can be detected in the parent process. However, it seems that the child and parent process are using the same domain participant? We tried to print out the value of `ddsc_entity` of the DomainParticipant (using [this](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/511eb786885821e3d1aa86b1c8534f72a1b11ff0/src/ddscxx/src/org/eclipse/cyclonedds/core/DDScObjectDelegate.cpp#L51) API), and they are the same.

```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from test_discovery_info_manager
[ RUN      ] test_discovery_info_manager.extract_message_typesupport
Child process
442230439 // ddsc_entity_t
110e01c8eb7987ba6b18001c100000000 // GUID
Parent process
442230439 // ddsc_entity_t
110e01c8eb7987ba6b18001c100000000 // GUID
```
Since `fork` is called before initializing the DomainParticipant via CycloneDDS-CXX api, I would assume that CycloneDDS should create two separate domain participant. 

@eboasson Could you please give some of your thoughts? Thanks

**Comment by eboasson** [comment]
Sounds like a duplicate of #1097 — it is an interesting combination of details that leads to this. That should be fixed on `master` so I hope you are using the 0.8 release. (The fix can be backported to `0.8.x` if needed, but `0.9.0` is expected shortly.)

Note that #1105 is related, but that it concerns the slightly different problem of forking a process that already has readers/writers.

**Comment by t0ny-peng** [comment]
@eboasson that is great. Sorry I should’ve searched before creating the issue. I’ll apply the patch and let you know if it works. 🙏

**Comment by t0ny-peng** [comment]
@eboasson I've confirmed that the patch in https://github.com/eclipse-cyclonedds/cyclonedds/pull/1103 does make the GUID different in  parent to child process. Thanks for the work! Closing this issue now.
