### ISSUE TITLE
Valgrind gives memory loss record

### ISSUE THREAD

**Issue by xl4hub** [eclipse-cyclonedds/cyclonedds#1168]
Running ThroughputSubscribe with valgrind gives the report below.  The expectation is that all allocated memory is freed before exit and looking at the source code it appears that this memory should be freed. 

Using commit eea821b89fd 
Built on Ubuntu 20.04 using
$ cmake -DBUILD_EXAMPLES=ON -DENABLE_SECURITY=ON -DENABLE_SHM=OFF ..

$ **valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes ./ThroughputSubscriber**
==2273076== Memcheck, a memory error detector
==2273076== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2273076== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==2273076== Command: bin/ThroughputSubscriber
==2273076== 
Cycles: 0 | PollingDelay: -1 | Partition: Throughput example
=== [Subscriber] Waiting for samples...
**^C**
Total received: 0 samples, 0 bytes
Out of order: 0 samples
Average transfer rate: 0.00 samples/s, 0.00 Mbit/s
==2273076== 
==2273076== HEAP SUMMARY:
==2273076==     in use at exit: 24 bytes in 1 blocks
==2273076==   total heap usage: 757 allocs, 756 frees, 3,435,595 bytes allocated
==2273076== 
==2273076== 24 bytes in 1 blocks are still reachable in loss record 1 of 1
==2273076==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==2273076==    by 0x491159C: ddsrt_calloc (heap.c:41)
==2273076==    by 0x491271F: ddsrt_thread_cleanup_push (threads.c:532)
==2273076==    by 0x48E0194: lazy_create_thread_state (q_thread.c:210)
==2273076==    by 0x48E0194: lookup_thread_state_real (q_thread.c:223)
==2273076==    by 0x48E0194: lookup_thread_state_real (q_thread.c:216)
==2273076==    by 0x48EE1D7: dds_init (dds_init.c:115)
==2273076==    by 0x48EAC7E: dds_create_participant (dds_participant.c:105)
==2273076==    by 0x109552: prepare_dds (subscriber.c:322)
==2273076==    by 0x109552: main (subscriber.c:87)
==2273076== 
==2273076== LEAK SUMMARY:
==2273076==    definitely lost: 0 bytes in 0 blocks
==2273076==    indirectly lost: 0 bytes in 0 blocks
==2273076==      possibly lost: 0 bytes in 0 blocks
==2273076==    still reachable: 24 bytes in 1 blocks
==2273076==         suppressed: 0 bytes in 0 blocks
==2273076== 
==2273076== For lists of detected and suppressed errors, rerun with: -s
==2273076== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by thijsmie** [comment]
The fact that it is "still reachable" indicates this is not a true memory loss, just the thread global hanging around in the lib which is cleaned up on process end. Not a bug.

**Comment by johnecrosbie** [comment]
Perhaps not a bug but it is always better to cleanup all valgrind noise so any real leaks are more easily detected.
