### ISSUE TITLE
Ensure compatibility with iceoryx 2.0

### ISSUE THREAD

**Issue by MatthiasKillat** [eclipse-cyclonedds/cyclonedds#1174]
There is a change in the iseoryx API which affects the how iceoryx C API creates objects (they are now created in dynamic memory).

While the current CycloneDDS will build with iceoryx 2.0, it will crash due to semantic changes of the C-API.
We need some minor adaptations to ensure it will still compile and work correctly.

Furthermore we can add some more checks to handle cases where some iceoryx resource limits are exceeded.
This affects mainly the iceoryx listener (currently if the limits are exceeded we will silently receive no data).

Unfortunately this will not work for iceoryx publishers and subscribers given the current API (if limits are exhausted the libary will call terminate, as is already happening).

**Comment by MatthiasKillat** [comment]
@eboasson @sumanth-nirmal FYI

**Comment by sumanth-nirmal** [comment]
@MatthiasKillat @eboasson Can we close this issue since the corresponding MR is merged?

**Comment by eboasson** [comment]
Thanks for reminding me @sumanth-nirmal
