### ISSUE TITLE
Hint : Iceoryx is present as conan package 

### ISSUE THREAD

**Issue by dotChris90** [eclipse-cyclonedds/cyclonedds#1193]
Hello Cyclone DDS team, 

i just saw that you are also using conan for cunit and iceoryx for shared memory. 
In case you want a smoother integration --> https://conan.io/center/iceoryx?version=1.0.1 

Hopefully also can be used via the conanfile.txt - i just thought conan would be more beneficial for cross compilation of cyclone-DDS and in case you also want to distribute cycloneDDS one day in conan-center. 

wish you a good week.

**Comment by eboasson** [comment]
Wow, that's neat and I'd have loved to use it, but we've *just* switched to (upcoming) Iceoryx 2.0 in master (and for the upcoming 0.9.0 release). Do you have any plan on adding 2.0 to conan-center as well?

**Comment by dotChris90** [comment]
Wow! just saw they already release it. That's cool. I will look into it. I am not 100% sure how fast it will be to bring into conan-center official. But we definitive will have a look into it ;)

**Comment by dotChris90** [comment]
Ok have some issues need to consider but looks good from my point of view. 

- they adapted namespace from utils to hoofs 
- their installation dir is now containing the iceoryx version --> need to adjust the includePaths in the package_info
- tomlcpp was somehow not found for some reason - need to check here why 

But just checked now and tried out on my end. so cool - not big issue - will try a PR this week.

**Comment by dotChris90** [comment]
ok - PR started - working for 1.0.0, 1.0.1 and 2.0.0 --> https://github.com/conan-io/conan-center-index/pull/9779 

Let's see when PR can be merged. 

If you interested into how to use iceoryx from conan : 
- https://github.com/conan-io/conan-center-index/blob/master/recipes/iceoryx/all/test_package/CMakeLists.txt 
- https://github.com/conan-io/conan-center-index/blob/master/recipes/iceoryx/all/test_package/conanfile.py

**Comment by dotChris90** [comment]
@eboasson 

ok - PR is merged to conan-center github repo - in the next hours it should be also present in conan-center artifactory.

:D just small question - any interest that cyclone - DDS also becomes part of conan center or you guys think because more focused on ROS and so that cyclone dds users are not interested in conan? 

just would offer you that we could bring into conan center if you are interested. ;)
