### ISSUE TITLE
"ddsi_serdata_from_sample"  and SHM

### ISSUE THREAD

**Issue by sgf201** [eclipse-cyclonedds/cyclonedds#1196]
the code below is from  dds_write_imp() 
/* Serialize and write data or key */
  if ((d = ddsi_serdata_from_sample (ddsi_wr->type, writekey ? SDK_KEY : SDK_DATA, data)) == NULL)
    ret = DDS_RETCODE_BAD_PARAMETER;
  else
  {
    ...
#ifdef DDS_HAS_SHM
    if (wr->m_iox_pub)
    {
      iceoryx_header_t *ice_hdr;
      if (!deregister_pub_loan(wr, data))
      {
        void *pub_loan;
        pub_loan = create_iox_chunk(wr);
        memcpy (pub_loan, data, wr->m_topic->m_stype->iox_size);
        data = pub_loan;
      }
      ice_hdr = SHIFT_BACK_TO_ICEORYX_HEADER(data);
      ice_hdr->guid = ddsi_wr->e.guid;
      ice_hdr->tstamp = tstamp;
      ice_hdr->statusinfo = d->statusinfo;
      ice_hdr->data_kind = writekey ? SDK_KEY : SDK_DATA;
      ddsi_serdata_get_keyhash(d, &ice_hdr->keyhash, false);
      iox_pub_publish_chunk (wr->m_iox_pub, ice_hdr);
}

HI, if use SHM（iceoryx）, the "ddsi_serdata_from_sample " need not to call ? for performance
may that works below?

  if (wr->m_iox_pub)
  {
      ...
   }
   else
{
  ddsi_serdata_from_sample ();
}

@eboasson

**Comment by eboasson** [comment]
Hi @sgf201 ! You're right, and even better, we noticed it too. That improvement has been on `master` for a while now. And I am about to create a 0.9 release branch. (At first it'll just be a beta, but if history is anything to go by, it'll be pretty close to the release.)

**Comment by sgf201** [comment]
> Hi @sgf201 ! You're right, and even better, we noticed it too. That improvement has been on `master` for a while now. And I am about to create a 0.9 release branch. (At first it'll just be a beta, but if history is anything to go by, it'll be pretty close to the release.)

OK, thanks.I will  learn the code in master, Looking forward to 0.9   and then 1.0
