### ISSUE TITLE
Hang on cmake configuration (on Maven)

### ISSUE THREAD

**Issue by i-and** [eclipse-cyclonedds/cyclonedds#120]
1. On 1c7f9035469e53a7bade1353669c1637436fb410 observed the hangs configuring "cmake ../src". The probable reason is the non-completion of the process " mvn.cmd" (apache-maven-3.6.0) running by: execute_process(COMMAND ${Main_EXECUTABLE} - version
RESULT_VARIABLE res
OUTPUT_VARIABLE var
ERROR_VARIABLE var
OUTPUT_STRIP_TRAILING_WHITESPACE
ERROR_STRIP_TRAILING_WHITESPACE).

**Comment by k0ekk0ek** [comment]
Hi @i-and, I've made the parsing of the version number mandatory to ensure that maven actually woks. It probably has something to do with your environment, can you give a bit more information? What operating system are you using? Windows? What happens if you run the command manually?

**Comment by i-and** [comment]
Hi @k0ekk0ek, Yes, Windows. 
The idea of controlling the Maven version is good. 
If I run manually "mvn.cmd --version" then runs Maven, which outputs the version information in the correct format" Apache Maven 3.6.0 (97c98.....)" and remains in the interpreter. To complete the process, i have to run the "exit"command. I suspect that's the problem.

**Comment by k0ekk0ek** [comment]
Sounds like you found the problem. Any special version of Maven or Java installed perhaps? Did this happen before the changes too?

**Comment by i-and** [comment]
Uses JRE from JDK 1.8.0_162. 
Apparently this was before the changes. At the same time, after bypassing the need to check the version of Maven (REQUIRED_VARS Maven_EXECUTABLE Maven_VERSION -> REQUIRED_VARS Maven_EXECUTABLE) - all project files are generated and projects (including idlc) are built successfully.

**Comment by k0ekk0ek** [comment]
I think the problem is the script name in this case. FindMaven.cmake didn't work properly on Windows. It didn't check for mvn.cmd, but mvn. The latter is the script that's executed on Linux and Apple. On Windows it previously just tried to run that script, which of course failed, but since the output wasn't checked it went unnoticed. The real problem here is that the command never finishes. I'd like to know why that is, since the command that is executed to build the idl compiler completes successfully.

**Comment by i-and** [comment]
At the end of the file `mvn.cmd` is found as follows: 

    if "%MAVEN_TERMINATE_CMD% "== " on " exit %ERROR_CODE%
    cmd /C exit /B %ERROR_CODE%

After setting the environment variable MAVEN_TERMINATE_CMD=on, everything was fixed.
@k0ekk0ek, thank you for participating.

**Comment by i-and** [comment]
As it turned out, the root cause was that one of the installed packages overridden the `cmd` command and its behavior. After rolling back to the standard `cmd`, everything is OK.

**Comment by k0ekk0ek** [comment]
Hi @i-and. Sorry for replying this late, but thanks for analysing the issue.

I might add setting `MAVEN_TERMINATE_CMD` when executing the command in `FindMaven.cmake` since other users may run into it as well. Thanks again.
