### ISSUE TITLE
How can i monitor dds data flow in domain just like rosbag

### ISSUE THREAD

**Issue by PandaSel** [eclipse-cyclonedds/cyclonedds#1219]
I'm trying to subscribe to all publishers' data to monitor dds data flow, but that means I have to know all publisher's dds_topic_descriptor_t and the actual struct. Is there have a common 'data type'/method that I can use to subscribe to different publisher struct.

I want to make a tool like rosbag(ros2).

**Comment by eboasson** [comment]
In C or C++, not quite yet. You could do a bit of trickery and get hold of the serialised representation without knowing the type, but the usefulness of that is debatable.

In Python, it is already supported: https://cyclonedds.io/docs/cyclonedds-python/latest/cyclonedds.dynamic.html, which is used for example in the [pubsub](https://cyclonedds.io/docs/cyclonedds-python/latest/tools.pubsub.html) tool in https://github.com/eclipse-cyclonedds/cyclonedds-python/blob/aeca1b9f8bc384b358771dab8aeab94132ef471e/cyclonedds/tools/pubsub/topic_manager.py#L19

**Comment by a438254702** [comment]
You could do a bit of trickery and get hold of the serialised representation without knowing the type
----> Can you give me some examples for how to use it?

**Comment by eboasson** [comment]
If I were you, I'd use the Python binding to get a supported and much nicer interface, but if you really want to do it in C ...

https://github.com/atolab/cdds-util/blob/master/example/blob_subscriber.c is a bit out-of-date but the issues are mostly taken care of by a global replace of `ddsi_sertopic` to `ddsi_sertype`, calling `ddsi_sertype_init_flags` and creating the topic using `dds_create_topic_serdata`. Other relevant sources: https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/core/ddsc/tests/cdr.c is a bunch of test cases that also use this path, with both the old, depracted `sertopic` and the new interface; and https://github.com/eboasson/cyclonedds-haskell/blob/master/examples/IDLTest.hs is a completely different take on this, but it can also do this (well it only writes at the moment, I think).

When you call `ddsi_sertype_init_flags`, and two flags are important:
* `DDSI_SERTYPE_FLAG_TOPICKIND_NO_KEY` to indicate whether or not the topic has key fields (don't get me started on the inanity of that part of the spec), which you correlates with the GUID of a reader/writer: if the least significant four bits of the last byte of a GUID is 2 or 7, it concerns a topic that has one or more key fields; if it is 3 or 4, it concerns a topic that has zero key fields.
* `DDSI_SERTYPE_FLAG_REQUEST_KEYHASH`, which gives you access to the "DDSI key hash" where your `sertype` implementation gets the fragments from the wire to construct a sample. Then, and only then, using `ddsi_serdata_keyhash_from_fragchain` you can get a pointer to the "DDSI key hash" (or a null pointer if it isn't present) which you can then use to distinguish between different key values. But only if you're willing to take some risks:
  * this "DDSI key hash" thing has issues with hash collisions (but if it is actually a hash, it is MD5 and collisions are therefore not so likely)
  * whether or not it is a hash also depends on whether some DDS Security settings are set just so
  * you can play tricks with DDS XTypes that cause the same key value to map to different key hashes ...
  * the thing is mostly optional in the protocol, but if you set this particular flag, Cyclone writers will provide it

  Without this, the only way to distinguish between different instances is to know the type, but then you get back to the earlier point.

I really ought to do a proper example for this, as it would be quite useful and it won't take me very much time to do it. But now is not a good time for that for me, and perhaps you like a challenge 🙂

**Comment by a438254702** [comment]
Thanks a lot for answer，

I'm having some problems：
1.  Can I use the normal listener method to get the data of dds_create_topic_sertype
2. I have coredump which described as below
3. Replace “memcpy (&d->valuesz, base + off, sizeof (uint32_t)); ” with “d->valuesz = *(base + off);”，coredump disappeared ，but got incorrect results for example：‘=== [Subscriber] Received : Message (-2080371952, o World)’；The correct result is ‘=== [Subscriber] Received : Message (1, Hello World)’

btw：The sdr_include.h codes are copied from ~/dds/cyclonedds/src/core/ddsc/tests/cdr.c

static uint32_t sdx_from_ser_iov (struct sdx *d, enum ddsi_serdata_kind kind, ddsrt_msg_iovlen_t niov, const ddsrt_iovec_t *iov, uint32_t basehash)
{
  // assuming not fragmented, CDR Header specifies native encoding, input is valid and all that
  // CDR encoding of strings: uint32_t length-including-terminating-0 ; blob-including-terminating-0
  assert (niov == 1);
  (void) niov;
  size_t off = 0;
  const char *base = (const char *) iov[0].iov_base + 4;
  memcpy (&d->keysz, base + off, sizeof (uint32_t));
  off += sizeof (uint32_t);
  d->data.key = strdup_with_len (base + off, d->keysz);
  off += d->keysz;
  d->pad0 = (uint32_t) (((off % 4) == 0) ? 0 : 4 - (off % 4));
  off += d->pad0;
  if (kind == SDK_DATA)
  {
    **memcpy (&d->valuesz, base + off, sizeof (uint32_t));**
    off += sizeof (uint32_t);
    d->data.value = strdup_with_len (base + off, d->valuesz);
    off += d->valuesz;
    // FIXME: not sure if this is still needed, it shouldn't be, but ...
    d->pad1 = (uint32_t) (((off % 4) == 0) ? 0 : 4 - (off % 4));
  }
  else
  {
    d->data.value = NULL;
    d->valuesz = d->pad1 = 0;
  }
  return ddsrt_mh3 (d->data.key, d->keysz, 0) ^ basehash;
}


In this function, this code
memcpy (&d->valuesz, base + off, sizeof (uint32_t));
will cause a coredump
Maybe the actual code is
d->valuesz = *(base + off);

below is all testing code :

#include "dds/dds.h"
#include "HelloWorldData.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <signal.h>
#include "sdr_include.h"
/* An array of one message (aka sample in dds terms) will be used. */
#define MAX_SAMPLES 1
dds_listener_t* m_listener = NULL;

void notifyPublication(dds_entity_t reader, void* arg)
{
  printf("~~~~~~~~ notifyPublication ~~~~~~~~~~~:%d\n", sizeof(HelloWorldData_Msg));
  char topicName[1024];
  auto topic = dds_get_topic(reader);

  auto result = dds_get_name(topic, topicName, 1024);
  printf("#### topic:%d, topicName:%s\n", topic, topicName);
  void *samples[MAX_SAMPLES];
  dds_sample_info_t infos[MAX_SAMPLES];
  dds_return_t rc;

  samples[0] = HelloWorldData_Msg__alloc ();

  /* Poll until data has been read. */
  while (true)
  {
    /* Do the actual read.
     * The return value contains the number of read samples. */
    rc = dds_read (reader, samples, infos, MAX_SAMPLES, MAX_SAMPLES);
    if (rc < 0)
      DDS_FATAL("dds_read: %s\n", dds_strretcode(-rc));

    /* Check if we read some data and it is valid. */
    if ((rc > 0) && (infos[0].valid_data))
    {
      /* Print Message. */
      HelloWorldData_Msg *msg = (HelloWorldData_Msg*) samples[0];
      printf ("=== [Subscriber] Received : ");
      printf ("Message (%"PRId32", %s)\n", msg->userID, msg->message);
      fflush (stdout);
      break;
    }
    else
    {
      /* Polling sleep. */
      dds_sleepfor (DDS_MSECS (20));
    }
  }
  HelloWorldData_Msg_free (samples[0], DDS_FREE_ALL);

}

bool exitFlag = false;
static void exitFn(int sig)
{
    if (SIGINT == sig)
    {
        printf("exitFN invoked, exit.\n");
        exitFlag = true;
    }
}


int main (int argc, char ** argv)
{
  dds_entity_t participant;
  dds_return_t rc;
  (void)argc;
  (void)argv;

  signal(SIGINT, exitFn);

  m_listener = dds_create_listener(NULL);
  if (NULL != m_listener)
  {
      dds_lset_data_available(m_listener, notifyPublication);
  }
  else
  {
      DDS_FATAL("error to create listener\n");
  }

  participant = dds_create_participant (DDS_DOMAIN_DEFAULT, NULL, NULL);
  if (participant < 0)
  {
    DDS_FATAL("dds_create_participant: %s\n", dds_strretcode(-participant));
  }

  struct tw sub_tw = make_topic (participant, "HelloWorldData_Msg", "HelloWorldData::Msg", NULL);

  dds_qos_t *qos = dds_create_qos ();
  dds_entity_t reader = dds_create_reader (participant, sub_tw.tp, qos, m_listener);
  if (reader < 0)
    DDS_FATAL("dds_create_reader: %s\n", dds_strretcode(-reader));
  dds_delete_qos(qos);

  while (!exitFlag)
  {
    dds_sleepfor (DDS_MSECS (20));
  }

  rc = dds_delete (participant);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_delete: %s\n", dds_strretcode(-rc));

  return EXIT_SUCCESS;
}

**Comment by a438254702** [comment]
Thanks a lot for answer，

I'm having some problems：

1. Can I use the normal listener method to get the data of dds_create_topic_sertype, see function "notifyPublication"
2. I have coredump which described as below function "sdx_from_ser_iov"
3. Replace "memcpy (&d->valuesz, base + off, sizeof (uint32_t));" with "d->valuesz = *(base + off);"，coredump disappeared ，but got incorrect results for example：'=== [Subscriber] Received : Message (-2080371952, o World)'；The correct result is '=== [Subscriber] Received : Message (1, Hello World)'

btw：The sdr_include.h codes are copied from ~/dds/cyclonedds/src/core/ddsc/tests/cdr.c

static uint32_t sdx_from_ser_iov (struct sdx *d, enum ddsi_serdata_kind kind, ddsrt_msg_iovlen_t niov, const ddsrt_iovec_t *iov, uint32_t basehash)
{
    // assuming not fragmented, CDR Header specifies native encoding, input is valid and all that
    // CDR encoding of strings: uint32_t length-including-terminating-0 ; blob-including-terminating-0
    assert (niov == 1);
    (void) niov;
    size_t off = 0;
    const char *base = (const char *) iov[0].iov_base + 4;
    memcpy (&d->keysz, base + off, sizeof (uint32_t));
    off += sizeof (uint32_t);
    d->data.key = strdup_with_len (base + off, d->keysz);
    off += d->keysz;
    d->pad0 = (uint32_t) (((off % 4) == 0) ? 0 : 4 - (off % 4));
    off += d->pad0;
    if (kind == SDK_DATA)
    {
        **memcpy (&d->valuesz, base + off, sizeof (uint32_t));**
        off += sizeof (uint32_t);
        d->data.value = strdup_with_len (base + off, d->valuesz);
        off += d->valuesz;
        // FIXME: not sure if this is still needed, it shouldn't be, but ...
        d->pad1 = (uint32_t) (((off % 4) == 0) ? 0 : 4 - (off % 4));
    }
    else
    {
        d->data.value = NULL;
        d->valuesz = d->pad1 = 0;
    }
    return ddsrt_mh3 (d->data.key, d->keysz, 0) ^ basehash;
}

In this function, this code
**memcpy (&d->valuesz, base + off, sizeof (uint32_t));**
will cause a coredump
Maybe the actual code is
**d->valuesz = *(base + off)?**

below is all testing code :

#include "dds/dds.h"
#include "HelloWorldData.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <signal.h>
#include "sdr_include.h"
/* An array of one message (aka sample in dds terms) will be used. /
#define MAX_SAMPLES 1
dds_listener_t m_listener = NULL;

void notifyPublication(dds_entity_t reader, void* arg)
{
    printf("~~~~~~~~ notifyPublication ~~~~~~~~~~~:%d\n", sizeof(HelloWorldData_Msg));
    char topicName[1024];
    auto topic = dds_get_topic(reader);
    auto result = dds_get_name(topic, topicName, 1024);
    printf("#### topic:%d, topicName:%s\n", topic, topicName);
    void *samples[MAX_SAMPLES];
    dds_sample_info_t infos[MAX_SAMPLES];
    dds_return_t rc;

    samples[0] = HelloWorldData_Msg__alloc ();
    if (NULL == samples[0])
    {
        DDS_FATAL("parameterAlloc failed with unKnown topicName: %s\n", topicName);
    }

    rc = dds_take_next(reader, samples, infos);
    if (rc < 0)
    {
        DDS_FATAL("dds_read: %s\n", dds_strretcode(-rc));
    }

    if ((rc > 0) && (infos[0].valid_data))
    {
        /* Print Message. */
        HelloWorldData_Msg *msg = (HelloWorldData_Msg*) samples[0];
        printf ("=== [Subscriber] Received : ");
        printf ("Message (%"PRId32", %s)\n", msg->userID, msg->message);
        fflush (stdout);
    }

    HelloWorldData_Msg_free (samples[0], DDS_FREE_ALL);
}

bool exitFlag = false;
static void exitFn(int sig)
{
    if (SIGINT == sig)
    {
        printf("exitFN invoked, exit.\n");
        exitFlag = true;
    }
}

int main (int argc, char ** argv)
{
    dds_entity_t participant;
    dds_return_t rc;
    (void)argc;
    (void)argv;

    signal(SIGINT, exitFn);

    m_listener = dds_create_listener(NULL);
    if (NULL != m_listener)
    {
        dds_lset_data_available(m_listener, notifyPublication);
    }
    else
    {
        DDS_FATAL("error to create listener\n");
    }

    participant = dds_create_participant (DDS_DOMAIN_DEFAULT, NULL, NULL);
    if (participant < 0)
    {
        DDS_FATAL("dds_create_participant: %s\n", dds_strretcode(-participant));
    }

    struct tw sub_tw = make_topic (participant, "HelloWorldData_Msg", "HelloWorldData::Msg", NULL);

    dds_qos_t *qos = dds_create_qos ();
    dds_entity_t reader = dds_create_reader (participant, sub_tw.tp, qos, m_listener);
    if (reader < 0)
    DDS_FATAL("dds_create_reader: %s\n", dds_strretcode(-reader));
    dds_delete_qos(qos);

    while (!exitFlag)
    {
        dds_sleepfor (DDS_MSECS (20));
    }

    rc = dds_delete (participant);
    if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_delete: %s\n", dds_strretcode(-rc));

    return EXIT_SUCCESS;
}

**Comment by PandaSel** [comment]
Hi @eboasson ，
I have researched for a few days and understood the mechanism of code running , and I have got  the correctly serialized data from callback. But when I want to deserialize the data, I find that I can't get the correct information in ddsi_sertype_default (such as 'align' in ddsi_sertype_default_desc, 'nops, ops' in ddsi_sertype_default_desc_op_seq_t, etc.),My understanding is that the relevant information in dds_sertype_default is assigned by dds_topic_descriptor_t when the topic is created.And it can be confirmed from the calling relationship in q_receiver.c : deliver_user_data -> deliver_locally_one -> struct reader *rd = entidx_lookup_reader_guid (gv->entity_index, rdguid) -> from_ser; The source of dds_topic_descriptor_t looks like querying the local reader.
But when I created the topic, I used topicname and typename which without dds_topic_descriptor_t. So how do I get deserialization related information (align, nops, etc)?

**Comment by eboasson** [comment]
The plan is to make it add code to convert an XTypes type object to a `dds_topic_descriptor_t`, and the code needed to do that more-or-less exists today (the IDL compiler does essentially the same thing, except it doesn't work on XTypes type object). I know @dpotman is looking at that in the background, but I don't know exactly when it'll be ready. Hence why I originally suggested using Python: you can deserialise the blob in Python given just that type object.

If you don't quite need XTypes just yet, in Cyclone 0.8.x you can do `dds_find_topic` and (effectively) get the `dds_topic_descriptor_t`. It's just that it only works for the C API. But it could be an option.

**Comment by PandaSel** [comment]
Hi @eboasson ,
I have gained some experience from the [main.c](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/tools/idlc/xtests/main.c) test case, and my solution is to store serialized data. When the user views the monitoring data (the user must know the data type), I can get the idl structure provided by the user to deserialize data. 
1. Initialize dds_topic_descriptor_t with the specific idl data structure.
2. Get ddsi_sertype_default through dds_topic_descriptor_t.
3. Get the specific sample through dds_stream_read_sample.
4. Print the specific sample through dds_stream_print_sample.
thanks a lot!

**Comment by PandaSel** [comment]
Hi @eboasson ,
I have a question that is confusing me. When I tested the [listtopics](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/examples/listtopics/listtopics.c) case, I found that regardless of whetherthe key exists in the publisher idl, the reader's The least significant four bits of the last byte of the GUID are all 7(which indicates that there is a key). I am using helloworld's [publisher.c](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/examples/helloworld/publisher.c) as publisher(Add or delete @key field in [HelloWorld.idl](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/examples/helloworld/HelloWorldData.idl).

My code is as follows:
`static bool process_topic (dds_entity_t readcond)
{
#define MAXCOUNT 10
  /* dds_take allocates memory for the data if samples[0] is a null pointer, and reuses
     it otherwise, so it must be initialized properly.  The "10" is arbitrary. */

  bool topicNoKey = false;

  dds_entity_t reader = dds_get_datareader(readcond);
  if (0 < reader)
  {
    dds_guid_t guid;
    dds_get_guid(reader, &guid);
    uint8_t topicKey = guid.v[15];
    if (3 == topicKey || 4 == topicKey)
    {
      topicNoKey = true;
    }
    else if (2 == topicKey || 7 == topicKey)
    {
      topicNoKey = false;
    }
    else
    {
      printf("[error] unknown topic key:%d\n", topicKey);
    }
  }

  printf("topicNoKey:%d\n", topicNoKey);
...
}`

And below are some of the experiences you told me:
DDSI_SERTYPE_FLAG_TOPICKIND_NO_KEY to indicate whether or not the topic has key fields (don't get me started on the inanity of that part of the spec), which you correlates with the GUID of a reader/writer: if the least significant four bits of the last byte of a GUID is 2 or 7, it concerns a topic that has one or more key fields; if it is 3 or 4, it concerns a topic that has zero key fields.

**Comment by eboasson** [comment]
I think the problem is that you're looking at the GUID of the data reader created by `listtopics` to subscribe to the "DCPSTopic" built-in topic. Adding/removing the `@key` annotation in the helloworld topic affects the GUIDs of the readers/writers of that topic, but not of the topic GUID.

With the type object contained in the "DCPSTopic" topic, I suppose you could find out the key fields. I think that'll be a painful affair (unless @dpotman can think of a simple way). So given the importance that the DDSI-RTPS spec gives to the distinction, perhaps we should make sure that the keyed/non-keyed distinction is visible in the topic's GUID.

If you look at the "DCPSPublication" topic you should see the entity kind of the hello world publisher's writer change. The easiest way to monitor that is using [ddsls](https://github.com/eclipse-cyclonedds/cyclonedds-python/blob/master/docs/source/tools.ddsls.rst), or you could hack `listtopics` a trivial bit, given that it already has a (short-lived) subscription to the "DCPSPublication" topic.

**Comment by PandaSel** [comment]
Hi @eboasson ,
Thanks a lot, I think I've solved it. As you said, I use [ddsls](https://github.com/eclipse-cyclonedds/cyclonedds-python/blob/master/docs/source/tools.ddsls.rst) to test, [ddsls](https://github.com/eclipse-cyclonedds/cyclonedds-python/blob/master/docs/source/tools.ddsls.rst) can get the result . Then I compared the c code and the py code, and I found the c code uses the incorrect DDS_BUILTIN_TOPIC_DCPSTOPIC, it should be DDS_BUILTIN_TOPIC_DCPSPUBLICATION. Then use the key which in dds_builtintopic_endpoint_t to get the @key field.
