### ISSUE TITLE
idlc does not have an option to respect directory structure (feature?)

### ISSUE THREAD

**Issue by ahoenerBE** [eclipse-cyclonedds/cyclonedds#1220]
I'm working on a project that makes use of a large collection of generated IDL files. 
The structure of the files is fairly complex with 4-5 layers of sub-directories. Many of the IDL files have `#include` headers for dependencies to other structs, modules, etc. within this structure
```
Base
---- Sub1
-------- Sub1A
------------ Sub1AA
---------------- Sub1AAA.idl
------------ Sub1AB
---------------- Sub1ABA.idl
------------ Sub1AC
---------------- Sub1ACA.idl
-------- Sub1B
-------- Sub1C
-------- ....
---- Sub2
---- Sub3
---- Sub4
---- ....
```
When using `idlcxx_generate` with cmake, all the files are just thrown into the cmake bin directory and don't retain any of the directory information, **but** the `include` directives are preserved which leads to compilation errors.

## Example

**TL;DR** You have to manually recreate the directory structure or use an external script, I want a flag for idlc to create a directory structure matching the path from a user-defined root. I'll do the PR myself if it's something you're open to

I have this directory structure with IDL files
![image](https://user-images.githubusercontent.com/84148896/159345671-92c49ae8-1643-4af0-8861-64d826f7f028.png)
### IDL code
https://gist.github.com/ahoenerBE/812a9baaeef2c63c652357bb728f59da

### idlcxx_generate output
```
file(GLOB_RECURSE idl_files RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} idl/**/*.idl)

idlcxx_generate(TARGET test_idls
        FILES ${idl_files}
        INCLUDES ${CMAKE_CURRENT_SOURCE_DIR}/idl
        FEATURES case-sensitive
        DEFAULT_EXTENSIBILITY appendable
        WARNINGS no-implicit-extensibility
        )
```
![image](https://user-images.githubusercontent.com/84148896/159346520-78782bc1-b2a8-41a5-8eb2-11b11f874bfb.png)

Inside the files, the idl `#includes` have been translated correctly to the right output headers, but they reference directories that don't exist
![image](https://user-images.githubusercontent.com/84148896/159346893-1cf4d617-0767-46a9-8101-c53c8c29af95.png)
```
FAILED: CMakeFiles/ddscxxHelloworldPublisher.dir/Item.cpp.o 
/usr/bin/c++  -I/home/drew/CLionProjects/CycloneTests/cmake-build-debug -isystem /home/drew/CLionProjects/cyclonedds-cxx/install/include/ddscxx -isystem /home/drew/CLionProjects/cyclonedds/install/include -g -std=gnu++17 -MD -MT CMakeFiles/ddscxxHelloworldPublisher.dir/Item.cpp.o -MF CMakeFiles/ddscxxHelloworldPublisher.dir/Item.cpp.o.d -o CMakeFiles/ddscxxHelloworldPublisher.dir/Item.cpp.o -c /home/drew/CLionProjects/CycloneTests/cmake-build-debug/Item.cpp
In file included from /home/drew/CLionProjects/CycloneTests/cmake-build-debug/Item.cpp:9:
/home/drew/CLionProjects/CycloneTests/cmake-build-debug/Item.hpp:12:10: fatal error: Base/Inventory/ItemCategory.hpp: No such file or directory
   12 | #include "Base/Inventory/ItemCategory.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Either using a script or manually recreating the directory structure allows the program to compile
![image](https://user-images.githubusercontent.com/84148896/159347646-0ed0304b-b03d-473a-9273-c510034233d0.png)

## Request
Could there be an idlc flag to recreate a directory structure starting at a certain root, like the include path flag?
If so, would you be open to a PR for it, I'd like to have it integrated in the tool if I could

**Comment by eboasson** [comment]
Oops, that's quite an oversight!

I know there are some PRs (#947, #922) that at least superficially seem related. I haven't really looked at those carefully because my former co-conspirator was looking after them, but he has had to stop actively contributing to Cyclone because of other obligations and I didn't get around to them. If you feel like this is something you'd be happy to pick up, then those two PRs might well give you some inspiration and we'd be more than happy to receive a PR that fits the current version of the code base.

Otherwise I'll see what I can do (but I already have a todo list that's longer than I'd like ...)
