### ISSUE TITLE
idlc segfault with repeated module

### ISSUE THREAD

**Issue by ghorn** [eclipse-cyclonedds/cyclonedds#1245]
The following IDL causes `idlc` to segfault
```
module module1 {
  module module1 {
    struct MyStruct {
      double yolo;
    };
  };  // module1
};  // module1
```

if the modules are not nested, it it is fine. For example:
```
module module1 {
  module module2 {
    struct MyStruct {
      double yolo;
    };
  };  // module2
};  // module1
```

**Comment by dpotman** [comment]
Thanks for reporting this. According to the [IDL 4.2 spec](https://www.omg.org/spec/IDL/4.2/PDF) section 7.5.2, using nested modules with the same (local) name is not allowed:

_The name of a module, structure, union, (...) may not be redefined within the immediate scope of the module, structure, union, (...)_

So the first IDL fragment above should be rejected by the IDL compiler with a proper message. I'll add a check for this in `idlc`.

**Comment by ghorn** [comment]
Thanks for the quick fix! Two questions.

1. Could you clarify the IDL spec to me? Is it immediate parent/child collisions which are problematic, or must there be no collisions anywhere in the hierarchy? For example, would the following be legal:
```
module A {
  module B {
    module C {
      module A {
        struct SomeType {
          double yolo;
        };
      };  // A
    };  // C
  };  // B
};  // A
```

2. On a scale of 1-10, how unwise would it be for cyclonedds to be non-compliant with the DDS spec, in order to help out one user who undertook a poor design decision and could greatly benefit from repeated module names?

**Comment by dpotman** [comment]
1. Yes, that IDL fragment is valid. Only in the immediate scope of a module (or struct, union or any other definition that forms a scope), the name of that scope may not be redefined. I don't know the exact reason for this, might be that it causes problems in certain language mappings (constructors?) or may be related to search rules for type resolving. @e-hndrks do you know the exact reason for this restriction? 

2. Depending on the exact reason for this rule, it may be ok to have a command line option in IDLC that disables the check for redefining a name within the immediate scope. But the behavior has to be consistent for all language mappings, so if certain languages can't handle this, I think we shouldn't add that option in IDLC.

**Comment by eboasson** [comment]
> On a scale of 1-10, how unwise would it be for cyclonedds to be non-compliant with the DDS spec, in order to help out one user who undertook a poor design decision and could greatly benefit from repeated module names?

Sensible languages all allow it, I believe. So I'd say 3, with 1 being least unwise (a.k.a. most wise 🙂) and 10 being most unwise. Given the explicit prohibition in the spec, I think it would be wise to generate a warning by default, if only to prevent accidental portability issues.
