### ISSUE TITLE
how could new reader get the msg which is sent before it

### ISSUE THREAD

**Issue by sgf201** [eclipse-cyclonedds/cyclonedds#1251]
I think that after the new reader is created, it can receive the topic messages that have been sent before, because they are stored in the writer's history, but they are not received in the actual test. The new reader can only receive the MSG sent after the creation。how to get the history msg after reader is created

**Comment by eboasson** [comment]
Did you make them reliable and set the "durability" QoS setting to "transient local" on both the reader and the writer?

(If you want the writer to store more than just the most recent sample for each key value, you also need to set the "durability service" QoS setting history depth on the writer side. It is ignored by the reader, so you may well be able to use the exact same settings for both.)

e.g.:
```C
  dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_SECS (1));
  dds_qset_durability (qos, DDS_DURABILITY_TRANSIENT_LOCAL);
  dds_qset_durability_service (qos, 0, DDS_HISTORY_KEEP_LAST, depth, DDS_LENGTH_UNLIMITED, DDS_LENGTH_UNLIMITED, DDS_LENGTH_UNLIMITED);
```

**Comment by sgf201** [comment]
> Did you make them reliable and set the "durability" QoS setting to "transient local" on both the reader and the writer?
> 
> (If you want the writer to store more than just the most recent sample for each key value, you also need to set the "durability service" QoS setting history depth on the writer side. It is ignored by the reader, so you may well be able to use the exact same settings for both.)
> 
> e.g.:
> 
> ```c
>   dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_SECS (1));
>   dds_qset_durability (qos, DDS_DURABILITY_TRANSIENT_LOCAL);
>   dds_qset_durability_service (qos, 0, DDS_HISTORY_KEEP_LAST, depth, DDS_LENGTH_UNLIMITED, DDS_LENGTH_UNLIMITED, DDS_LENGTH_UNLIMITED);
> ```

when I do this   the dds_loan_sample() return unsupport. did that if using ICEORYX   the msg sent before can not be got?
why the qos must be set to DDS_DURABILITY_TRANSIENT_LOCAL to that msg
