### ISSUE TITLE
error use of mutex，when dds security is enable.

### ISSUE THREAD

**Issue by johnflj** [eclipse-cyclonedds/cyclonedds#1275]
HI, @eboasson 
When the helloworld program finishes communication, 
dds will call dds_delete to destroy the corresponding resources, and the participant entity will be deleted via gc. 
When dds security is enabled, deleting the participant will trigger sec_attributes deletion, 
and in the function cleanup_participant_sec_attributes attributes at the end, it will call:

  ddsrt_avl_cfree(&pp_proxypp_treedef, &attr->proxy_participants, NULL);
  ddsrt_mutex_unlock(&attr->lock);
  ddsrt_free(attr);
 
Here, the call to ddsrt_mutex_unlock is wrong, it should be ddsrt_mutex_destroy, 
in QNX, the wrong call to ddsrt_mutex_unlock will cause coredump. 
I think, use participant_sec_attributes_free (attr); 
to replace 3 lines of code is a better way.

**Comment by eboasson** [comment]
I couldn't agree more!

**Comment by johnflj** [comment]
e god！ e speed！
