### ISSUE TITLE
Could not find a configuration file for package "CycloneDDS" that is   compatible with requested version ""

### ISSUE THREAD

**Issue by saharsh270797** [eclipse-cyclonedds/cyclonedds#1301]
I am trying to build the hello world example but it the throws an error.
The error says that the CycloneDDSConfig file was considered but not accepted.

The cmakelists.text file does find_package(CycloneDDS REQUIRED). Is there any version that can be specified here for the config file to be accepted?

Please find the snip below for reference:
![image](https://user-images.githubusercontent.com/107139144/172675002-fb9e071d-38ef-4e71-a31e-62fcb5ab57e9.png)

**Comment by saharsh270797** [comment]
> Hi @saharsh270797,
> 
> My suspicion is that you are trying to build the example as 64bit application while your CycloneDDS core library is built as 32bit, as indicated in the screenshot. Can you try if making sure they are equal fixes your problem? (this is controlled by the cmake `-A` flag)

Hello Thijs, thank you for your response.
I tried running the x64 architecture but cmake is still generating a 32 bit project.

![image](https://user-images.githubusercontent.com/107139144/172697518-3a1bbca3-ed20-48f4-9ae1-d275a57535c7.png

Is there any other way to generate a 64 bit project?

**Comment by thijsmie** [comment]
Almost, you understood me the wrong way round. The _library_ is 32 bit, so either rebuild CycloneDDS core with 64 bit or build the example in 32 bit
