### ISSUE TITLE
A page in Eclipse Cyclone DDS C API Reference not working properly

### ISSUE THREAD

**Issue by eunsooan** [eclipse-cyclonedds/cyclonedds#1311]
While I was reading through the documentation, I found [this page](https://cyclonedds.io/docs/cyclonedds/latest/api/basics.html#return-codes) not working properly. I really want to find out what it says!  

The page prints a warning that says:

> Warning
> doxygengroup: Cannot find group “retcode” in doxygen xml output for project “ddsc_api_docs” from directory: /tmp/tmpbuapei3t/xml

Thanks,

Eunsoo

**Comment by thijsmie** [comment]
Ah, the doxygen setup in the website repository is slightly out of sync with the main repository one, I'll fix that now.

**Comment by thijsmie** [comment]
This was fixed.
