### ISSUE TITLE
Revisit doing a static build of Cyclone DDS

### ISSUE THREAD

**Issue by thijsmie** [eclipse-cyclonedds/cyclonedds#1313]
While not a huge priority, a static build of a library is simply something you _should_ support if at all possible. The support for this in Cyclone DDS is somewhat in a grey area, it works with some caveats which are not properly captured in documentation, as clear by quite the list of issues: https://github.com/eclipse-cyclonedds/cyclonedds/pull/1259 https://github.com/eclipse-cyclonedds/cyclonedds/issues/1198 https://github.com/eclipse-cyclonedds/cyclonedds/issues/317 https://github.com/eclipse-cyclonedds/cyclonedds/issues/800 and probably more. Let's properly document the process and caveats to address this.

**Comment by Kischy** [comment]
We recently made two patches that let us build cyclonedds v0.8.0 and v0.9.0 static. I will attach the patches here, if this helps.
[remove_pdb_install_v0.8.0.patch.txt](https://github.com/eclipse-cyclonedds/cyclonedds/files/9052223/remove_pdb_install_v0.8.0.patch.txt)
[remove_pdb_install_v0.9.0.patch.txt](https://github.com/eclipse-cyclonedds/cyclonedds/files/9052224/remove_pdb_install_v0.9.0.patch.txt)

The patches basically remove the installation of .pdb files.

**Comment by Kischy** [comment]
I can also open a PR if wanted. Should I?

**Comment by vectorsli** [comment]
Wouldn't it be easier to simply embed the debug symbols instead of managing PDB files?

**Comment by eboasson** [comment]
How would we do that? And what are the downsides to embedding them? Having the debug data in separate files is almost always annoying, but it seems to be the norm on Windows.

**Comment by vectorsli** [comment]
I think the flag is `/Z7` (see [msvc docu](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=msvc-170#z7)). The only downside for OSS code I can think of is a bigger binary.

**Comment by vectorsli** [comment]
Please make the installation optional. For example with cmake option where the default value is `BUILD_SHARED_LIBS`. Like that:

```cmake
option(INSTALL_PDB "Install PDB files" ${BUILD_SHARED_LIBS}")
```

**Comment by Kischy** [comment]
@thijsmie I just wanted to look at this and compiled using
`-DBUILD_SHARED_LIBS=OFF`
and it worked fine. I also saw that the following lines
```cmake
if(MSVC)
  option(INSTALL_PDB "Install PDB files next to DLLs." ${BUILD_SHARED_LIBS})
endif()
```
where added. I think this is already done and this can be closed.

**Comment by thijsmie** [comment]
Thank you @Kischy for doing the work for me! Indeed this seems to be all fine now, good that that is confirmed.
