### ISSUE TITLE
Idlc fails when handling nested includes with files in different folders

### ISSUE THREAD

**Issue by ceyxiang** [eclipse-cyclonedds/cyclonedds#1319]
Idlc will return with code 1 when processing an idl file that includes a idl file in another folder with nested includes.

Example case:
```
Directory layout
base_folder/Folder1/File1.idl
base_folder/Folder1/Folder2/File2.idl
base_folder/Folder1/Folder2/File3.idl

File1.idl
#include "Folder2/File2.idl"

File2.idl
#include "File3.idl"
```

When running idlc on File1.idl, nothing will be printed or generated. From what I have traced, it will fail at [directive.c L150](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/idl/src/directive.c#L150) as the `dir->path` would be `<Absolute Path to base_folder>/base_folder/Folder1/Folder2/Folder2/File2.idl` (duplicate `Folder2` in path) From my understanding it comes about when returning from an included file. 

Changing [this](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/idl/src/directive.c#L129) line to `if (dir->flags & (START_OF_FILE) && !idl_isabsolute(dir->path)) {` will fix the issue if idlc is called from `Folder1`. But if idlc is called from `base_folder` (with the argument to idlc as `Folder1/File1.idl`), this fix will fail as `dir->path` will now be `<Absolute Path to base_folder>/base_folder/Folder2/File2.idl` (Missing `Folder1` in path).

A solution that seems to fix this properly would be to change the preprocessor to output the absolute paths to the included files instead of their relative paths. Changing [these 2 lines](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/tools/idlpp/src/system.c#L4007-L4008) to just `name = file->full_fname;` seems to fix the issue properly.

As I am not familiar with the idlc code, I would like someone's opinion on whether the fix would potentially cause any other issues.

**Comment by dpotman** [comment]
Thanks for reporting this issue! We're currently looking into this. Your proposed solution to add the absolute path in the linemarkers might have impact on the includes in generated sources, and I'd prefer to solve this issue in the IDL library, e,g, by fixing the conversion to an absolute path in `push_line`, or by changing the way the file is popped from the stack when handling `RETURN_TO_FILE`. I'll keep you updated on this.

**Comment by dpotman** [comment]
PR #1324 changes the way the `RETURN_TO_FILE` flag in a file marker from the preprocessor is processed in IDLC. I did some additional manual tests and I think this fixes the issue. @ceyxiang could you please check if this also fixes your issue?

**Comment by ceyxiang** [comment]
Fixed with PR https://github.com/eclipse-cyclonedds/cyclonedds/pull/1324 and PR https://github.com/eclipse-cyclonedds/cyclonedds/pull/1329
