### ISSUE TITLE
output of throughput subscriber not flushed on win10 console

### ISSUE THREAD

**Issue by hansvanthag** [eclipse-cyclonedds/cyclonedds#133]
In order to have periodic output of the achieved throughput on windows-10, a 'fflush(stdout)' needs to be performed after printing each report(-line).

Without this, the application doesn't seem to work .. and you'd have to wait like a minute before buffered-output is finally flushed to the console (and you find out its working after-all :) )

**Comment by eboasson** [comment]
Isn't Windows just lovely ...

**Comment by eboasson** [comment]
fixed
