### ISSUE TITLE
Optional network interfaces

### ISSUE THREAD

**Issue by timonegk** [eclipse-cyclonedds/cyclonedds#1330]
We are using cyclonedds on a robot that is sometimes used with an external network interface and sometimes runs without it. It would therefore be nice to be able to define network interfaces as optional to avoid the error "does not match an available interface" on startup when an interface is currently not connected. This way, it would not be necessary to change the configuration when an interface is connected or disconnected.

**Comment by thijsmie** [comment]
Hi @timonegk,

Your suggestion was relatively easy to implement so I just went ahead and did it. Would you be so kind to verify if this works for you?
