### ISSUE TITLE
 Declaration '<idl struct>' collides with earlier an declaration of '<idl struct>'

### ISSUE THREAD

**Issue by Alpha2Mao** [eclipse-cyclonedds/cyclonedds#1333]
I defined three idl file， when I use idlc program to generate TestA.h/TestA.c for TestA.idl，it will cause error `TestC.idl:3:9: Declaration 'TestC' collides with earlier an declaration of 'TestC'`，I want to to known what cause this，thanks!

The idlc version is 0.9.0

TestC.idl
```idl
module Test {                                                                                                                               
    module msg {
        struct TestC {
            uint32 a;
        };
    };
};
```

TestB.idl
```idl
#include "TestC.idl"                                                                                                                        

module Test {
    module msg {
        struct TestB {
            TestC tc;
        };
    };
};
```

TestA.idl
```idl
#include "TestB.idl"
#include "TestC.idl"

module Test {
    module msg {
        struct TestA {
            TestB tb;
            TestC tc;
        };
    };
};
```

**Comment by dpotman** [comment]
You get this error because `TestC.idl` is included in `TestA.idl`, and via `TestB.idl`. As there are no include guards in your IDL files, `TypeC` is redeclared when the file is included the second time. 

To solve this, you can use (C/C++ style) include guards in the IDL:

```
#ifndef _TESTC_IDL_
#define _TESTC_IDL_

module Test {
  ...
  ...
};

#endif // _TESTC_IDL_
```
