### ISSUE TITLE
Required CMake version should be bumped (maybe) 

### ISSUE THREAD

**Issue by stan-guer** [eclipse-cyclonedds/cyclonedds#1354]
The following line uses a CMake 3.12 feature, [EXPORT_PROPERTIES](https://cmake.org/cmake/help/latest/prop_tgt/EXPORT_PROPERTIES.html):

https://github.com/eclipse-cyclonedds/cyclonedds/blob/21fe67fb243d3a660b7608038802f459ceaf3e78/src/core/CMakeLists.txt#L89-L91

As a result, when building and doing `make install` with CMake 3.10 , the `CycloneDDSTargets.cmake` won't contain certain properties f.e. that type/topic discovery are supported. 

In turn, a project that uses those properties , like [cyclonedds-cxx](https://github.com/eclipse-cyclonedds/cyclonedds-cxx), won't know that those properties are actually available. 

I discovered this because the current master does not build without Type/Topic discovery, see [Build without type and topic discovery](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/300) in that project.

I understand #550 was merged to allow building with default Ubuntu 18.04 CMake, so i'm not sure what's the best solution here is:

- Lift baseline to Ubuntu 20.04 Cmake 3.16, it's fairly easy to install a newer CMake
- add a CMake version check for install 
- add property manually using CMake 3.10? not sure if its possible at all

**Comment by eboasson** [comment]
I'm tempted to say bumping the minimum required version to 3.16 should be ok, Ubuntu 20.04 is already 2 years old, the minimum version supported by ROS 2 Foxy, and upgrading CMake is not all that hard. (And I really do not want to contemplate emulating it on older CMake ...)

So let's bump it and see who complains ...

If worst comes to worst, I suspect we can work around it using the C preprocessor, at least for C++ binding, and with some limitations where the CMake files depend on having this knowledge.
