### ISSUE TITLE
Forwarding topics to a different network interface.

### ISSUE THREAD

**Issue by roni-kreinin** [eclipse-cyclonedds/cyclonedds#1361]
OS: Ubuntu 20.04
ROS2 Galactic

I have a setup with 3 PCs connected like so:
PC1 <- Ethernet -> PC2 <- WiFi -> PC3

PC2 has CycloneDDS configured to use both WiFi and Ethernet and can see topics from both PC1 and PC3. PC1 can only see topics from PC2 and similarly PC3 can only see topics from PC2. Is there a way to forward topics from PC1 to PC3 through PC2 without just republishing them?

**Comment by eboasson** [comment]
Hi @roni-kreinin, Cyclone doesn't do routing itself and relies on the IP stack to route the packets. So you might want to check whether PC2 is configured to route traffic.

To complicate matters a bit, I assume you're currently relying on multicast discovery, but in IP stacks there tends to be a difference between unicast routing and multicast routing, and it is quite likely that PC2 will happily forward unicast packets, but not multicast.

So probably the most practical thing to try is to enable unicast discovery:
```XML
<Discovery>
  <ParticipantIndex>auto</ParticipantIndex>
  <Peers>
    <Peer address="PC1"/>
    <Peer address="PC2"/>
    <Peer address="PC3"/>
  </Peers>
</Discovery>
```

The default behaviour of Cyclone on a WiFi interface is avoid multicast for application data, so with a bit of luck this is enough configuration to make it work.

**Comment by roni-kreinin** [comment]
@eboasson thanks for the response, I'll try this out. Will I need to set this configuration on each PC or just PC2?

**Comment by eboasson** [comment]
The absolute minimum is to put PC3 in the peer list of PC1, or PC1 in the peer list of PC3 (it's enough if one reaches the other, that'll trigger a response and complete discovery). PC2 sees both anyway.

I assumed you had a single configuration file, and so putting all three in and using the same configuration would be an easy way to check this idea of mine. It won't do much harm, even if it does produce a little bit of extra traffic.

**Comment by roni-kreinin** [comment]
@eboasson What method would you recommend using for unicast routing? I have tried a few things but can't seem to get it working.

**Comment by eboasson** [comment]
@roni-kreinin I don't remember ever having had to do it in Linux, and my experience on Solaris from is so outdated and irrelevant it doesn't make sense to even try to reconstruct how to do it there. This: https://unix.stackexchange.com/questions/449468/how-to-route-between-interfaces does match my expectations, but I don't have special google-fu, so I'm sure this is exactly the same sort of thing that you looked at already ...
