### ISSUE TITLE
CycloneDDS v0.10 release date

### ISSUE THREAD

**Issue by alknemeyer** [eclipse-cyclonedds/cyclonedds#1377]
Hey. Is there a rough timeline for when a new version could be released? I would like to make use of some bug fixes between v0.9.1 and the current master.

Following the comments and discussion in [issue 121](https://github.com/eclipse-cyclonedds/cyclonedds-python/issues/121#issuecomment-1209289958) (cyclonedds-python repo), it looks like the next version should be v0.10, not v0.9.2. Please let me know if I can help with the release process somehow.

Thanks!

**Comment by thijsmie** [comment]
Hi @alknemeyer,

That day is today :smile:!
