### ISSUE TITLE
Adding python3-breathe entry to rosdep

### ISSUE THREAD

**Issue by giusebar** [eclipse-cyclonedds/cyclonedds#1380]
Hello,

I'm currently trying to install the dependencies of cyclonedds via rosdep. However, rosdep fails to resolve dependencies for python3-breathe.
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
cyclonedds: Cannot locate rosdep definition for [python3-breathe]
```
I'm going to add an entry to rosdistro in order to fix this to solve the issue. I just wanted to flag this up, there might be more dependencies with the same issue.

**Comment by giusebar** [comment]
I've opened a [PR](https://github.com/ros/rosdistro/pull/34205) here.

**Comment by eboasson** [comment]
Thanks for the heads-up @giusebar. I know someone has create a FreeBSD port and that someone has looked into a Conan package for Cyclone, but neither has resulted in any questions about dependencies and I am not aware of anything else.

In short, I think it best to close this issue, with thanks!
