### ISSUE TITLE
Ok to enable multicast on lo interface?

### ISSUE THREAD

**Issue by sloretz** [eclipse-cyclonedds/cyclonedds#1400]
Are there known issues with enabling multicast on the `lo` interface?
It seems to solve my problems, but I'm wondering if there is a reason not to do it.

The rest of this is context.

---

The particular system is using CycloneDDS and ROS 2 Humble. It uses `ROS_LOCALHOST_ONLY=1` to configure CycloneDDS to restrict traffic to the `lo` interface. If I understand what I'm seeing in wireshark correctly, it does this by making all packets have a source address of `127.0.0.1`.

On Ubuntu `lo` isn't configured for multicast by default. CycloneDDS detects this, prints an error message, and to switches to unicast discovery for DDSI participants.

```
selected interface "lo" is not multicast-capable: disabling multicast
```

It seems like this causes [ParticipantIndex](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaindiscoveryparticipantindex) to be set to `auto`  because unicast discovery [requires very specific port numbers](https://cyclonedds.io/docs/cyclonedds/0.9.1/config.html#controlling-port-numbers) so that it can discover participants on the system. However, the default value of [MaxAutoParticipantIndex](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaindiscoverymaxautoparticipantindex) is only `9`. CylconeDDS only uses one DDSI participant per process, but 9 ROS 2 processes is still too few for this system. Attempting to launch another process fails when creating a ROS 2 node, and CycloneDDS output's this error message.

```
Failed to find a free participant index for domain 0
```

Creating a config with `MaxAutoParticipantIndex` set to the maximum value of 120 and setting the environment variable `CYCLONEDDS_URI=/path/to/config` works. In this case there's a desire to avoid setting another environment variable because of the complexity it adds to how this system launches processes.

That leaves me with enabling multicast on the loopack device. I can do it persistently by creating a script `/etc/network/if-up.d/ros2-lo-multicast`. It seems get rid of the warning and allows many ROS 2 processes to run at once.

```bash
#!/bin/sh
ip link set lo multicast on
```

**Comment by eboasson** [comment]
@sloretz I think it is perfectly safe to do that, it is a completely mystery to me why Ubuntu doesn't set the flag.

The implementation in the kernel doesn't seem to care in the slightest and current reality is that multicast on loopback works just fine regardless of whether this flag is set — hence the existence of the `multicast` attribute (and its deprecated ancestor, the `AssumeMulticastCapable` element) in Cyclone's configuration.

Setting the multicast flag at startup seems like the ideal solution to me. And Cyclone's generally happier if it can multicast anyway 😁

**Comment by thijsmie** [comment]
I fully agree, I also have something to this effect in my startup procedure. 😁

**Comment by sloretz** [comment]
Thank you for answering my question!
