### ISSUE TITLE
Some useless code in dds_topic.c

### ISSUE THREAD

**Issue by binbowang1987** [eclipse-cyclonedds/cyclonedds#1406]
I find some useless code in dds_topic.c

In dds_create_topic, ddsi_plist_t is initialized. 
https://github.com/eclipse-cyclonedds/cyclonedds/blob/91c61f2e0c0efc19f9f0722b6b811d9d9e1c70c7/src/core/ddsc/src/dds_topic.c#L645-L664

Following the invocation path, find that the `ddsi_plist_t *sedp_plist` is not used.
https://github.com/eclipse-cyclonedds/cyclonedds/blob/91c61f2e0c0efc19f9f0722b6b811d9d9e1c70c7/src/core/ddsc/src/dds_topic.c#L333-L348

What is the ddsi_plist used for in dds_topic.c formerly ? Can it be deleted now ?

**Comment by eboasson** [comment]
It was used for publishing metadata prior to adding XTypes support, but now that all happens with different encodings and with the relevant information coming from a different place. So, based on your research and my little bit of checking the code just now, this can indeed be thrown away.

That actually holds not just for this code, but I think also for all the `..._ADLINK_TYPE_DESCRIPTION`, `plist.type_description`, as well as `ADLINK_SUBSCRIPTION_KEYS` and `qos.subscription_keys`.

As the discoverer of this bit of dead code, you are entitled the honour of removing it (but if you'd rather let us take care of it, that's ok too) 🙂

**Comment by binbowang1987** [comment]
I just found this code by accident, I am not so familiar with other codes, please take care of it, thank you.:smile:
