### ISSUE TITLE
Configuration Cyclone to allow multi subnet/interface communications

### ISSUE THREAD

**Issue by ruffson** [eclipse-cyclonedds/cyclonedds#1422]
My setup:

On a ros2 galactic installation: `PC A` connected to `PC B` and `PC C` via ethernet. They are participating in the `192.168.2.0/24` subnet.
All three are also connected to a wifi network with the subnet `192.168.1.0/24`.
All three computers are communicating with one another and are mostly publishers. For some tasks I would like to connect to them via another computer `PC D` using the wifi network.

The three computers can communicate fine via Ethernet, all ROS nodes are visible.
However, when connecting to the same wifi network with `PC D`, no ROS nodes are visible.

A table summarizing this problem (by focusing only at PC A and PC D)

PC | Interface | IP
-|-|-
PC A | ethernet | 192.168.2.2
PC A | wifi | 192.168.1.2
PC D | wifi | 192.168.1.8

I first assumed that the different subnets are the issue here but I suspect it is the different network interfaces. 

When I tried forcing the wifi interface, I could see data via wifi with this configuration (but of course not via ethernet):

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <NetworkInterfaceAddress>wlp0s20f3</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
            <AssumeMulticastCapable>wlp0s20f3</AssumeMulticastCapable>    <!-- And this line -->
        </Internal>
    </Domain>
</CycloneDDS>
```

I also attempted to add all IP addresses as Peers like this to all participants' computers (e.g. `PC A` and `PC D`):

```
export CYCLONEDDS_URI="<Discovery><Peers><Peer Address='192.168.2.2' /><Peer Address='192.168.1.2' /><Peer Address='192.168.1.8' /></></>"
```

No luck here. Btw. I always stop the ROS daemon, set the domain ID correctly and make sure that no other ros2 process is running in between changing these configs.

I also tried some of the suggestions from this issue: https://github.com/eclipse-cyclonedds/cyclonedds/issues/1190
Which seems related but I could not get that to work with setting:

```
export CYCLONEDDS_URI='<Domain Id="any"><General><DontRoute>true</DontRoute></></>'
```

It would also be nice to know which XML Schema version the ros2 galactic release is using or a documentation with the available options. I could not find anything. The one specified in the xml header seems to be too new: https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd

**Comment by eboasson** [comment]
Hi @ruffson 

> I first assumed that the different subnets are the issue here but I suspect it is the different network interfaces.
>
> When I tried forcing the wifi interface, I could see data via wifi with this configuration (but of course not via ethernet):
> ```
> ```

That this works by forcing everything over WiFi is indeed what I would expect.

**Comment by ruffson** [comment]
Hey @eboasson thank you so much for your swift and thorough response! 
After a first few tests it does seem to work if I specify two interfaces as long as the wifi interface is listed first like this (otherwise it does not work):

```
export CYCLONEDDS_URI="<Domain><General><NetworkInterfaceAddress>wlp0s20f3,enp89s0</NetworkInterfaceAddress></></>"
```

Again, thank you for your help.
