### ISSUE TITLE
Options.md mentions deprecated `General/NetworkInterfaceAddress`

### ISSUE THREAD

**Issue by AndyZe** [eclipse-cyclonedds/cyclonedds#1434]
I'm trying to debug something and it looks like the documentation is out of date.

Specifically Options.md mentions `NetworkInterfaceAddress` but when I try to set `NetworkInterfaceAddress` I get:

`python3: config: //CycloneDDS/Domain/General: 'NetworkInterfaceAddress': deprecated element (file:///home/andy/cyclonedds.xml line 6)`

**Comment by AndyZe** [comment]
Unfortunately there are a lot of references to `NetworkInterfaceAddress` floating around the web already, like:

http://www.robotandchisel.com/2020/08/12/cyclonedds/

https://answers.ros.org/question/375360/multiple-network-interfaces-with-rmw_cyclonedds_cpp/

Some comments on these issues would be bice.

**Comment by eboasson** [comment]
That's indeed a good point. The good news here is that:

> python3: config: //CycloneDDS/Domain/General: 'NetworkInterfaceAddress': deprecated element (file:///home/andy/cyclonedds.xml line 6)

is no more than a warning and everything will work unchanged, and likely will continue to work for quite a while.

That it continues to work doesn't mean it is a good thing that there are references to deprecated things still in the current documentation, and you are also correct that it would be good to add a comment on those fora. I'd completely forgotten about them and the confusion it causes when they contain out-of-date information.

**Comment by thijsmie** [comment]
I've tweeted at the author of robotandchisel (but maybe he watches github better: @mikeferguson), submitted a PR for the dds-demonstrators guide and Husarion docs and submitted an issue for the iRobotEducation guide. I've also made a PR clearing up that reference in the options.md file.

**Comment by mikeferguson** [comment]
For clarity, is this new to Humble, or was the change made in an earlier release?

**Comment by thijsmie** [comment]
This change was introduced in CycloneDDS version 0.9.0 and a quick check shows that Galactic is on `releases/0.8.x` and Humble is on `releases/0.9.x` so indeed this is the recommended way to set up in Humble.

**Comment by AndyZe** [comment]
Thank you @thijsmie !
