### ISSUE TITLE
NetworkInterface option in xml config does not work

### ISSUE THREAD

**Issue by AndyZe** [eclipse-cyclonedds/cyclonedds#1435]
It seems that the "NetworkInterface" option in the xml configuration does not work. For example, I put this:

```
    <General>
        <Interfaces>
            <NetworkInterface name="wlp0s20f3" priority="default"/>
        </Interfaces>
        <AllowMulticast>spdp</AllowMulticast> <!-- Effectively disable multicast -->
        <EnableMulticastLoopback>true</EnableMulticastLoopback> 
    </General>
```

But the terminal still reports usage of the `lo` network interface!?

`spawner: selected interface "lo" is not multicast-capable: disabling multicast`

**Comment by eboasson** [comment]
I'm pretty sure it works just fine, and it will never auto-select a loopback interface if an ethernet or WiFi is available, so I'm pretty sure this means `CYCLONEDDS_URI` references two configurations, there is some additional configuration manipulation.

If you are using ROS 2 and have `ROS_LOCALHOST_ONLY` set, then the Cyclone DDS RMW layer prepends a loopback interface selection. If I were to guess, that's how this happened.

**Comment by AndyZe** [comment]
Yep, turning off `ROS_LOCALHOST_ONLY` gets rid of the messages related to `lo`. Thanks
