### ISSUE TITLE
IDLC fails when missing a space in final angles.

### ISSUE THREAD

**Issue by matte1** [eclipse-cyclonedds/cyclonedds#1436]
The following snippet from an .idl fails with a syntax error

```
sequence<sequence<double>> foo;
```

however the following is okay
```
sequence<sequence<double> > bar;
```

This isn't a huge deal but it does prevent me from using clang-format to autoformat all my idl files with a consistent style which IMO is pretty nice feature.

**Comment by thijsmie** [comment]
Hi @matte1,

I have also ran into this before, and sadly it is exactly what the grammar from the specification dictates. What it does currently is the "right" behaviour. Turning it into "convenient but technically incorrect" behaviour is not an easy fix, differentiating between a right shift and two "template end"s can not be done "context free". You can do a dirty parsing trick and split the token when needed with backtracking, I made one attempt at that in the past but did not succeed.

I'm tempted to make this a #wontfix but it is more like a #iwontfixit. If you can manage to make it work (and thus deviate from OMG specced grammar) I would be happy to merge it.

**Comment by matte1** [comment]
Not worth it to me when I can just disable clang-format anytime I come across it. Interesting the grammar is so strick. Thanks @thijsmie !
