### ISSUE TITLE
[Question] How to include cmake files proper for using idlc_generate command

### ISSUE THREAD

**Issue by dotChris90** [eclipse-cyclonedds/cyclonedds#1439]
Dear Cyclone team, 

i would like to know how to proper include the cmake files for using idlc commands. 

i did 

include("/tmp/cyclonedds/build/install/lib64/cmake/CycloneDDS/idlc/Generate.cmake")

and 

idlc_generate(TARGET HelloWorldData_lib FILES "HelloWorldData.idl")

but i get the error : 

CMakeFiles/HelloWorldData_lib_generate.dir/build.make:73: *** target pattern contains no '%'.  Stop.

**Comment by thijsmie** [comment]
Hi @dotChris90,

You shouldn not need to include the 'Generate' file directly. Simply `find_package(CycloneDDS)` already includes the generation routines _if_ it was built with `IDLC` included.
