### ISSUE TITLE
Why is the waitSet itself attached in this example?

### ISSUE THREAD

**Issue by mangodan2003** [eclipse-cyclonedds/cyclonedds#1443]
I've been using the below linked file as a basis for my project and am trying to better understand how the waitSet is being used.

Can somebody explain this?

https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/examples/shm_throughput/shmsubscriber.c#L464

I gather one reason for doing this is to allow the application to "be woken up" from the blocking state of `dds_waitset_wait()` e.g. for shutdown, but this does not seem to be the case here, i.e. nowhere is `dds_waitset_set_trigger()` used.

**Comment by mangodan2003** [comment]
Sorry for the noise! I had some dummy/incorrect signoff details on my machine that I hadn't noticed until too late and wasn't sure how to deal with. Ended up scrubbing the branch and the original PR and starting over.

**Comment by thijsmie** [comment]
Thanks @mangodan2003! Your relevant PR was merged. 😄
