### ISSUE TITLE
set dds to work only in localhost for SIL test

### ISSUE THREAD

**Issue by sgf201** [eclipse-cyclonedds/cyclonedds#1447]
I find a phenomenon that the more hosts in the LAN segment, the higher the CPU load of the dds process. When there are 26 hosts, the CPU utilization rate is about 50, and when there are 52 hosts, the CPU utilization rate is about 80.
so, Is there any configuration that allows DDS to run only on this host, regardless of the number of hosts in the same network segment? In this scenario, the processes of the local host only need communicate in the local machine

**Comment by thijsmie** [comment]
Hi @sgf201,

If I understand your question right, you want to make sure DDS traffic does not exit the host the application is running on. The easy way to do this by controlling the network interfaces DDS is allowed to use. By allowing only the loopback interface no traffic can exit your host. Here is an example XML file:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <Interfaces>
                <NetworkInterface name="lo" />
            </Interfaces>
        </General>
    </Domain>
</CycloneDDS>
```
If CycloneDDS gives you a warning about using multicast you can follow [this stackoverflow answer](https://stackoverflow.com/a/30982079) to enable that.

Let me know if that answers your question! :smile:

**Comment by sgf201** [comment]
@thijsmie  I test this in 0.8.1,  but I did not see the cpu decrease(there are many pc in the net), Is this config works in 0.8.1?

**Comment by thijsmie** [comment]
Hi @sgf201,

In 0.8.1 you should use the now deprecated `NetworkInterfaceAddress` like so:

```xml
<CycloneDDS>
    <Domain id="any">
        <General>
            <NetworkInterfaceAddress>lo</NetworkInterfaceAddress>
        </General>
    </Domain>
</CycloneDDS>

**Comment by sgf201** [comment]
> Hi @sgf201,
> 
> In 0.8.1 you should use the now deprecated `NetworkInterfaceAddress` like so:
> 
> ```
> <CycloneDDS>
>     <Domain id="any">
>         <General>
>             <NetworkInterfaceAddress>lo</NetworkInterfaceAddress>
>         </General>
>     </Domain>
> </CycloneDDS>
> ```

thanks

**Comment by sgf201** [comment]
https://github.com/eclipse-cyclonedds/cyclonedds/issues/1475
