### ISSUE TITLE
FreeRTOS sim project

### ISSUE THREAD

**Issue by sgf201** [eclipse-cyclonedds/cyclonedds#1455]
![image](https://user-images.githubusercontent.com/5253415/197566669-4e87793b-ed43-49bf-803e-771a8cb551c3.png)

![image](https://user-images.githubusercontent.com/5253415/197566258-6debaecb-3647-49df-a94e-6c2213eb1774.png)
Is readme right? the https://github.com/shlinym/FreeRTOS-Sim.git is not a cmake project

**Comment by thijsmie** [comment]
The readme is indeed wrong, the other project mentioned in that readme should have been linked.

https://github.com/linvis/FreeRTOS-POSIX
