### ISSUE TITLE
arm cross compile cyclonedds idl error

### ISSUE THREAD

**Issue by wjbbupt** [eclipse-cyclonedds/cyclonedds#1457]
cmake -DCMAKE_TOOLCHAIN_FILE=/tmp/toolchain.cmake
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=/ddsinstall/stage
../..
-- Building with OpenSSL support
CMake Error at cmake/Modules/Generate.cmake:44 (find_program):
Could not find _idlc_executable using the following names: idlc
Call Stack (most recent call first):
cmake/Modules/Generate.cmake:32 (idlc_generate_generic)
examples/helloworld/CMakeLists.txt:24 (idlc_generate)

Two questions

Openssl I directly replaced the local compiled link. My understanding is whether there is an openssl that automatically replaces gcc and arm in the program.
After cross-compiling, the idl idlc tool cannot be generated. Is there any way?

**Comment by thijsmie** [comment]
We will discuss all arm issues @wjbbupt has on https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/335.
