### ISSUE TITLE
dds::topic::ContentFilteredTopic: could not create dds::sub::DataReader

### ISSUE THREAD

**Issue by husnaini798** [eclipse-cyclonedds/cyclonedds#1460]
Hi,
using CycloneDDS, I am currently trying to create DataReader by passing in a filteredTopic

`      
       dds::sub::DataReader<T> reader = dds::core::null;
        std::stringstream str;
       str << "filtered_" << this->topic_name;

        LOG_S(TRACE) << "Creating topic";
        dds::topic::Topic<T> topic(participant, this->topic_name);

        dds::topic::ContentFilteredTopic<T> filterTopic(topic, str.str(), dds::topic::Filter("A_recipientID.A_resourceId = 50000"));
       reader = dds::sub::DataReader<T>(subscriber, filterTopic, qos, eventManager, dds::core::status::StatusMask::all());
`

However , once we debug in the CycloneDDS code method dds::sub::detail::DataReader<T>::common_constructor
I'm getting the following error

`2022-10-26 14:18:19.422 (  26.203s) [        F2057700]   registryresource.cpp:281   INFO| C_Resource_Registry received - service resourceId is 0
terminate called after throwing an instance of 'dds::core::InvalidArgumentError'
  what():  Error Bad Parameter - Could not create DataReader.

Context     : void dds::sub::detail::DataReader<T>::common_constructor
Node        : UnknownNode
`

Could someone please let me know if the parameters that I'm passing to ContentFilteredTopic are incorrect? or if the dds::sub::DataReader doesn't support content filtering?

Thanks.

Kind Regards,
Husnain Malik

**Comment by eboasson** [comment]
Sorry it took a while to get to around to responding ...

Content filtering is supported, but not yet using the expression syntax. Luckily someone has run into this before: https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/253#issuecomment-1087452070
