### ISSUE TITLE
Support interProcess Communication

### ISSUE THREAD

**Issue by YeahhhhLi** [eclipse-cyclonedds/cyclonedds#1464]
Currently, the communication is shm or udp, which requires serialization and deserialization operations. 

Can we support the method of inter-process communication ? such as sharing pointers, which saves the overhead of serialization and deserialization

**Comment by YeahhhhLi** [comment]
Or maybe we already support this scenario now, I just didn't find it

**Comment by sgf201** [comment]
SHM(iceoryx) do not require serialization and zero-copy featured

**Comment by thijsmie** [comment]
Answered by @sgf201, we indeed support shared memory zero-copy (for certain datatypes) via iceoryx.

**Comment by YeahhhhLi** [comment]
> Answered by @sgf201, we indeed support shared memory zero-copy (for certain datatypes) via iceoryx.

Sorry for replying now

Please see my latest reply above
