### ISSUE TITLE
Configuring ROS2 on Turtlebot4

### ISSUE THREAD

**Issue by escortKwon** [eclipse-cyclonedds/cyclonedds#1476]
My issue is much similar to the current opened issue(#1421)
[Previous Thread](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1421)

Let me describe more detail, as you asked on previous thread

**Describe the troubles I had**
I had my Turtlebot4 Lite clean-installed. Because I had some connection problems and in troubleshooting progress, therefore I thought overwriting the latest TB4 lite image(ver. 0.1.3) on my TB4 is the best way to solve problems.
After overwriting image, I had completed setting connection between Raspberry Pi 4 and 5GHz AP, between iCreate3 and 2.4GHz AP.
with "nmap -sP ..." command, I could find IP addresses from both TB4 lite and iCreate3. But there were no what looks like some name or label(Ubuntu or Create-XXXX)

Also, I have checked all topics from ROS2 for both computers
![Screenshot from 2022-11-08 15-02-23](https://user-images.githubusercontent.com/78137059/200487355-fa2b7c40-d0bc-4d10-ad3b-b372bee10ea0.png)
![Screenshot from 2022-11-08 15-02-26](https://user-images.githubusercontent.com/78137059/200487359-52d5ce6a-c8b2-4731-be00-6644a6b8aa59.png)
The upper one is captured from Remote PC and the other one is from RPi4

BTW, my final CylconeDDS configuration is as follows:
![Screenshot from 2022-11-11 15-50-13](https://user-images.githubusercontent.com/78137059/201280625-0c3f61ff-8f9e-4edd-8865-3628eb08ca82.png)

**Desired features I hope**
First of all, I hope to get IP address on my Remote PC by `ros2 topic echo /ip`
(If I could get that topic, there could be a chance to configure wireless connection among iCreate3 - Raspberry Pi 4 - Remote PC
I wanna see all topics on my Remote PC by `ros2 topic list`.

**Previous work**
I had many tries to troubleshoot.
[Ros2 topic list does not show the Create3 is publishing topics for turtebot4 lite](https://github.com/turtlebot/turtlebot4/issues/53)
[Request for uploading Dependencies](https://github.com/turtlebot/turtlebot4_robot/issues/9)

Thank you for your efforts!

**Comment by ciandonovan** [comment]
Are you on Galactic or Humble? Have you exported the environment variables to set Cyclone DDS as the RMW and a path to your config file?
```		
<Tracing>
	<Verbosity>config</Verbosity>
	<OutputFile>stdout</OutputFile>
</Tracing>
```
Add this configuration to your Cyclone DDS XML under the `Domain` tag and it should provide you with a wealth of information on how it has been configured and configured itself, including what interfaces it has chosen to communicate on and why.

N.B That config snippet works with the version of Cyclone DDS that comes with Humble, the syntax might be slightly different if you're on Galactic.

**Comment by escortKwon** [comment]
Thank you for you reply.

I have attached the snippet on my `cyclonedds_pc.xml` as follows:
![Screenshot from 2022-11-16 09-27-07](https://user-images.githubusercontent.com/78137059/202054186-09a65271-f43f-4b9d-947c-2a624792337d.png)
Then, I have run a command as follows: `ros2 doctor` and the result is as follows:
![Screenshot from 2022-11-16 09-31-55](https://user-images.githubusercontent.com/78137059/202054396-1447e02a-0809-47a1-abd2-10ae5b6e41d1.png)
I might guess the interface is not properly setup between my TB4 and remote PC
I wanna hear your opinion more.

BTW, I'm using Galactic on Remote PC. Thanks!

**Comment by ciandonovan** [comment]
Looks like your remote PC is picking wlp6s0 as the right interface.

I don't know much about the TB4's architecture, but should be getting my hands on one soon and so could look further then, could run into the same issue!

**Comment by escortKwon** [comment]
Then, **are there better ideas for troubleshooting?** or I have to just wait for TB4 developer to solve this issue. For right now, I cannot come up with better idea to configure connection Remote PC and TB4 (according to reference, for middleware, CycloneDDS is Tier 1 for ROS2 Galactic and Ubuntu 20.04.)

**Comment by eboasson** [comment]
There is always the possibility of capturing the network packets and a Cyclone DDS trace. Somehow I seem to always find some time to look at those when everything else fails 😉 

My first assumption would be picking the "wrong" network interface on the PC, but as @ciandonovan says, that seems looks fine. I also assume both are on the same WiFi network and you're not running into any routing problems (which should be really rare anyway for unicast ...)

A packet capture is made using Wireshark, plenty of examples and excellent documentation is available.

Turning on tracing in Cyclone is done by adding:
```XML
<Tracing>
  <Category>trace</Category>
  <OutputFile>cdds.log.${CYCLONEDDS_PID}</OutputFile>
</Tracing>
```
(or some other output file name, of course!) to the Cyclone configuration XML file.

If you're curious about the contents of that trace file, [it is somewhat documented now](https://cyclonedds.io/content/guides/tracefile.html), but I expect it'll be a bit overwhelming hence my offer to have a look 😄 .

**Comment by eboasson** [comment]
@escortKwon friendly ping to add to issue when you have something that may help moving it forward.

**Comment by jmm-slamcore** [comment]
We are also seeing similar issues when using `rmw_cyclonedds_cpp` on a corporate Wi-Fi network. We are not able to see any topics with `ros2 topic list` between a Laptop and the Turtlebot 4 or even between laptops when running a demo talker node. We have tried the same config as shared above (from https://iroboteducation.github.io/create3_docs/setup/xml-config/) without success.

**Comment by escortKwon** [comment]
Using FastDDS discovery server, I could access all topics between Remote PC and RPi4 simultaneously. Refer to this thread https://github.com/turtlebot/turtlebot4/issues/98
