### ISSUE TITLE
dds_write crash in ThreadSafePolice

### ISSUE THREAD

**Issue by sgf201** [eclipse-cyclonedds/cyclonedds#1481]
![image](https://user-images.githubusercontent.com/5253415/202075386-ca61cca3-d27a-49cc-914e-a2c8b957793c.png)
program crash in dds_write, maybe about iceoryx

**Comment by eboasson** [comment]
It could be a analogous to https://github.com/eclipse-cyclonedds/cyclonedds/pull/1463 . I'd love to merge that one, but unfortunately the Eclipse ECA check says there's no ECA on file.

@elfenpiff @elBoberido: mentioning you just to keep you informed.
