### ISSUE TITLE
How to make fastDDS & CycloneDDS Helloworld example communicate with each other

### ISSUE THREAD

**Issue by CodeTornato** [eclipse-cyclonedds/cyclonedds#1485]
Hello,I am trying to make FastDDS and CycloneDDS Helloworld example communicate with each other,, I checked their QOS, only difference I found is durability kind, I try to change their QOS to the same,but still not working,and I don't know if there is any additional place I need to change, can you please take a look for me?I uploaded 2 helloworld example and qos infomation of them.Data Writer is CycloneDDS, Data Reader is FastDDS.
![image](https://user-images.githubusercontent.com/118702310/202952846-ce41b105-f7a3-4cb9-bbf4-017e6015a689.png)
![image](https://user-images.githubusercontent.com/118702310/202953045-9a1fef51-ce2d-47dd-8e8a-59738c4a4bef.png)

[FastCyclone_HelloWorld.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/10052588/FastCyclone_HelloWorld.zip)

**Comment by eboasson** [comment]
Hi @CodeTornato there is no "standard" for examples, so when you take the "hello world" examples from two different vendors and try to make them talk, you really need to make sure they are compatible in all the ways that matter. In this case, it the data types are different: both IDL files define roughly the same structure (an 32-bit integer, though with different signedness, followed by a string), but they are still very different in other aspects:
* Cyclone's type is named `HelloWorldData::Msg`, Fast's is simply called `HelloWorld`
* Cyclone's IDL marks the `userID` field as key, Fast's doesn't have a key.

Both differences are currently blocking communication. I am actually surprised that this fancy tool you made screenshots of doesn't alert you to these differences — indeed, that it doesn't even show the type name! Maybe you should give `cyclonedds ls` a try, too 😎

Anyway, I would highly recommend using the same IDL for both to prevent this kind of problem.

On a side note: I think you're using a pretty old version of Cyclone, am I right? The IDL file in the file you attached still uses the `#pragma keylist` thing, but today there is a standardised way for specifying key fields (an `@key` annotation). I'd highly recommend using this standardised way, especially if you want to interoperate between different implementations.

**Comment by CodeTornato** [comment]
Thank you so much, I did as you said, first I use the same idl file for both project,and I made sure Domain ID,Topic Name,Type Name is same, finally it worked ,I was so happy to see it work.you really made my day.
Here I upload it my HelloWorld source code, if anyone have the same problem with me,welcome to look at it.
And by the way what is cyclonedds ls,can you give me link, I would be glad to give it a try.
[cyclone_fast_hello.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/10100011/cyclone_fast_hello.zip)

**Comment by eboasson** [comment]
Good to hear that it works!

The `cyclonedds` tool is included with the [Python](https://github.com/eclipse-cyclonedds/cyclonedds-python) binding. I just noticed that the README misses out on the screenshots in the documentation but they are present on our [website](https://cyclonedds.io/docs/cyclonedds-python/latest/tools.html). (I think I know why, a clever trick to auto-generate them, but those auto-generated screenshots of course don't get committed on GitHub. Maybe we shouldn't use the README as the source for this particular bit of documentation 🤔)
