### ISSUE TITLE
CycloneDDS+Iceoryx on Windows

### ISSUE THREAD

**Issue by EttoreVidotto** [eclipse-cyclonedds/cyclonedds#1490]
Dear CycloneDDS Team,
I have a question for you, since the support of Iceoryx by CycloneDDS is not 100% clear to me.
On the official GitHub page of CycloneDDS I could not find any limitations regarding the usage of Iceoryx, since there only the CMake variable ENABLE_SHM is described. However, trying to build CycloneDDS with Iceoryx support on my laptop with Windows 10 is apparently not supported, since I get the CMake error:
```cmake
-- This project seems to be plain C, using 'MSVC' compiler
-- Library y found D:/dev/.conan/data/bison/3.7.1/_/_/package/58dfdc10302cb712787b358dceba3d18737fc982/lib/y.lib
-- Library iceoryx_posh_gateway found D:/dev/.conan/data/iceoryx/2.0.2/_/_/package/a1163d1672fcc9f437f21accbe5c1b6c02993e3a/lib/iceoryx_posh_gateway.lib
-- Library iceoryx_posh_config found D:/dev/.conan/data/iceoryx/2.0.2/_/_/package/a1163d1672fcc9f437f21accbe5c1b6c02993e3a/lib/iceoryx_posh_config.lib
-- Library iceoryx_posh_roudi found D:/dev/.conan/data/iceoryx/2.0.2/_/_/package/a1163d1672fcc9f437f21accbe5c1b6c02993e3a/lib/iceoryx_posh_roudi.lib
-- Library iceoryx_binding_c found D:/dev/.conan/data/iceoryx/2.0.2/_/_/package/a1163d1672fcc9f437f21accbe5c1b6c02993e3a/lib/iceoryx_binding_c.lib
-- Library iceoryx_posh found D:/dev/.conan/data/iceoryx/2.0.2/_/_/package/a1163d1672fcc9f437f21accbe5c1b6c02993e3a/lib/iceoryx_posh.lib
-- Library iceoryx_hoofs found D:/dev/.conan/data/iceoryx/2.0.2/_/_/package/a1163d1672fcc9f437f21accbe5c1b6c02993e3a/lib/iceoryx_hoofs.lib
-- Library iceoryx_platform found D:/dev/.conan/data/iceoryx/2.0.2/_/_/package/a1163d1672fcc9f437f21accbe5c1b6c02993e3a/lib/iceoryx_platform.lib
-- Looking for getopt.h
-- Looking for getopt.h - not found
-- Warning: iceoryx binding for Windows currently not supported
CMake Error at src/CMakeLists.txt:58 (find_package):
  By not providing "Findiceoryx.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "iceoryx", but
  CMake did not find one.

  Could not find a package configuration file provided by "iceoryx" with any
  of the following names:

    iceoryxConfig.cmake
    iceoryx-config.cmake

  Add the installation prefix of "iceoryx" to CMAKE_PREFIX_PATH or set
  "iceoryx_DIR" to a directory containing one of the above files.  If
  "iceoryx" provides a separate development package or SDK, be sure it has
  been installed.
```
This is also in line with issues such as https://github.com/eclipse-cyclonedds/cyclonedds/pull/1209 or https://github.com/eclipse-cyclonedds/cyclonedds/issues/1134
I would like to point out that I would like to have ENABLE_SHM on True. Looking deeper in CycloneDDS’s code, the following check is performed:
```cmake
if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
  set(ENABLE_SHM "OFF" CACHE STRING "Disable shared memory support")
  message(STATUS "Warning: iceoryx binding for Windows currently not supported")
else()
…
```
Meaning that on Windows the variable ENABLE_SHM is set to OFF. However, two lines below, the following is set:
```cmake
if(ENABLE_SHM)
  if(NOT ENABLE_SHM STREQUAL "AUTO")
    set(iceoryx_required REQUIRED)
  else()
…
```
which sets the new variable to REQUIRED, since ENABLE_SHM = OFF != AUTO and then the NOT operator is applied. 
Therefore, my question since I don’t understand the logic behind these checks: Is Iceoryx supported for Windows or not?

I thank you in advance for your attention.
Bests,
Ettore

**Comment by thijsmie** [comment]
Hi @EttoreVidotto,

Our integration with iceoryx stems from a time when iceoryx did not work on Windows at all. These checks also stem from that time. With iceoryx now working on Windows Cyclonedds+iceoryx might actually work on Windows, simply no one has tried it yet!

As you seem to have a working iceoryx installation on a Windows machine and are fiddling with it, maybe you want to give it a try for us? Removing the Windows check from the CMake file and seeing if it works. If it does we can try to add it to CI and start to officially support it.

**Comment by EttoreVidotto** [comment]
Hi @thijsmie 
Thank you very much for your quick answer. So, I took the checks out, and, at least the cunit tests were working. Here are the changes I made:
![Enable SHM on Windows](https://user-images.githubusercontent.com/79527119/203736705-b1880a87-459f-4aaa-ba26-d9b9c5ec4f02.PNG)
I don't know if running the cunit tests is enough to say that iceoryx is working with CycloneDDS on Windows. What's your take?

**Comment by eboasson** [comment]
> I don't know if running the cunit tests is enough to say that iceoryx is working with CycloneDDS on Windows. What's your take?

For a build including Iceoryx, there are a number of tests that really do verify that it works. If you want to be sure that those were run, look for `start_roudi` and/or `iceoryx`. If those run successfully and Iceoryx's own testsuite passes, then we should be good.

Would have the time to do a PR for this change?

**Comment by EttoreVidotto** [comment]
Hi @thijsmie, @eboasson 
I was finally able to configure my CycloneDDS to work with conan, and pass to CMake the parameter ENABLE_SHM=True. Unfortunately, when this parameter is activated on Windows, I get the error:
```bash
D:\dev\cyclonedds\src\core\ddsi\include\dds/ddsi/ddsi_serdata.h(307,47): error C2375: 'ddsi_serdata_from_iox': redefinition; different linkage (compiling source file D:\dev\cyclonedds\src\core\ddsi\src
\ddsi_serdata.c) [D:\dev\cyclonedds\build\vscode\build\src\core\ddsc.vcxproj]
D:\dev\cyclonedds\src\core\ddsi\include\dds/ddsi/ddsi_serdata.h(305): message : see declaration of 'ddsi_serdata_from_iox' (compiling source file D:\dev\cyclonedds\src\core\ddsi\src\ddsi_serdata.c) [D: 
\dev\cyclonedds\build\vscode\build\src\core\ddsc.vcxproj]
D:\dev\cyclonedds\src\core\ddsi\include\dds/ddsi/ddsi_serdata.h(314,47): error C2375: 'ddsi_serdata_from_loaned_sample': redefinition; different linkage (compiling source file D:\dev\cyclonedds\src\cor 
e\ddsi\src\ddsi_serdata.c) [D:\dev\cyclonedds\build\vscode\build\src\core\ddsc.vcxproj]
D:\dev\cyclonedds\src\core\ddsi\include\dds/ddsi/ddsi_serdata.h(312): message : see declaration of 'ddsi_serdata_from_loaned_sample' (compiling source file D:\dev\cyclonedds\src\core\ddsi\src\ddsi_serd 
ata.c) [D:\dev\cyclonedds\build\vscode\build\src\core\ddsc.vcxproj]
```
Apparently, it is not possible to build Iceoryx as a shared library on Windows, while CycloneDDS is built as a shared library. Might this be the problem? In which case, do you have any idea I to solve it? I seem to recall that building CycloneDDS as a static library is not trivial.

**Comment by eboasson** [comment]
> I seem to recall that building CycloneDDS as a static library is not trivial.

This is also what I recall, but looking at #1508 it seemed rather straightforward. So perhaps it would make sense to give it a try and see where it fails?

**Comment by EttoreVidotto** [comment]
@eboasson Thanks for the suggestion, but the steps in #1508 do not seem to work for Windows. Apart from removing the section
```cpp
#elif defined(__APPLE__) || defined(__QNXNTO__) || defined(__FreeBSD__)  /* probably works for all BSDs */ 
```
from [src/ddsrt/src/ifaddrs/posix/ifaddrs.c](https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/ddsrt/src/ifaddrs/posix/ifaddrs.c#L82), which does not influence Windows, I tried commenting out the line 
```cmake
add_subdirectory(symbol_export)
```
from [src/core/xtests/CMakeLists.txt](https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/core/xtests/CMakeLists.txt#L18). However, I still receive the error 
```bash
CMake Error: install(EXPORT "CycloneDDS" ...) includes target "ddsc" which requires target "security_core" that is not in any export set.
```
even if the CMake variable `ENABLE_SECURITY` is set to `ON` in my project. Do you have any suggestion?

**Comment by EttoreVidotto** [comment]
The problem was solved replacing the line
```cmake
target_link_libraries(ddsc PRIVATE security_core)
```
with
```cmake
target_link_libraries(ddsc PRIVATE "$<BUILD_INTERFACE:security_core>")
```
Now I get some unresolved external symbol referenced in function `iceoryx_init`, but I'm looking into it.

**Comment by EttoreVidotto** [comment]
Update: I included CycloneDDS with iceoryx on Windows in my project (which requires CycloneDDS-CXX as well). Now, when I create a `DomainParticipant`, the function `dds_shm_monitor_init` is called, and then the execution hangs while calling iceoryx's function `iox_listener_init` with the following message:
![Screenshot 2023-01-18 121915](https://user-images.githubusercontent.com/79527119/213158387-f37ba060-640c-41d7-b20f-2fed20c0b035.png)
Any idea/suggestion?

**Comment by eboasson** [comment]
I usually get that "not responding" message when I stop things in the debugger or kill a process, and in those cases this is reasonable in my view. I don't recall having seen it in other cases. If you're not doing anything of the sort, then I'd start with the assumption that is caused by an Iceoryx-on-Windows thing. The other messages seem like collateral damage. It might be worth it to create an Iceoryx issue for this.

On a side note, even if there are still some lingering issues, I'd be happy to take the CMake change you describe and your `ddsrt_eth_get_mac_addr` implementation. Perhaps it would be an idea to update #1539 to include all the changes you need and rename it to "Iceoryx on Windows" support? We can delay claiming to support it on Windows until we have ironed out these last few issues.

That would also make it easier for the Iceoryx gues to reproduce it.
