### ISSUE TITLE
the idl is too long，The pub cannot find the sub

### ISSUE THREAD

**Issue by wjbbupt** [eclipse-cyclonedds/cyclonedds#1499]
Hello, I encountered a problem when using cyclone dds,

Problem phenomenon: The use of the idl is too long or the use of the monitor function in the idl union is too long. The phenomenon that the pub cannot find the sub appears, as shown below:

1. Start the pub first, and then start the sub. The monitoring on both sides is normal, and data can also be received;

2. Start the sub first and then the pub. The sub can find the pub, but the pub can't find the sub, but the sub can't receive the data sent by the pub

The expected result is that the pub and sub can find each other and transmit data at the same time;

Is there any way to solve this problem by coding or modifying the qos file? Thank you very much

**Comment by eboasson** [comment]
Hi @wjbbupt, the order in which you start the processes should not affect the discovery, and the size of the IDL shouldn't be a problem either. It doesn't really smell like a simple QoS or application issue, but I could be wrong.

There is a lot I don't know about what you're doing and it would really would help if you could provide a reproducer, otherwise a set of traces (*) will probably go a long way to understanding it.

**Comment by wjbbupt** [comment]
such as this：
`module cyclonedds {
    module test {
        module test1 {
            // 通用下行数据格式，适用于远程控制、远程诊断、OTA
            struct demoMessage {
                uint32 messageId;
                @key
                uint16 businessType;
                uint64 businessId;
                uint64 timestamp;
                uint32 businessSubType;
                sequence<octet, 20480> payload;

                uint64 num0;
                uint64 num1;
                uint64 num2;
                uint64 num3;
                uint64 num4;
                uint64 num5;
                uint64 num6;
                uint64 num7;
                uint64 num8;
                uint64 num9;
                uint64 num10;
                uint64 num11;
                uint64 num12;
                uint64 num13;
                uint64 num14;
                uint64 num15;
                uint64 num16;
                uint64 num17;
                uint64 num18;
                uint64 num19;
                uint64 num20;
                // uint64 num21;
                // uint64 num22;
                // uint64 num23;
                // uint64 num24;
                // uint64 num25;
                // uint64 num26;
                // uint64 num27;
                // uint64 num28;
                // uint64 num29;
                // uint64 num30;
                // uint64 num31;
                // uint64 num32;
                // uint64 num33;
                // uint64 num34;
                // uint64 num35;
                // uint64 num36;
                // uint64 num37;
                // uint64 num38;
                // uint64 num39;
                // uint64 num40;
                // uint64 num41;
                // uint64 num42;
                // uint64 num43;
                // uint64 num44;
                // uint64 num45;
                // uint64 num46;
                // uint64 num47;
                // uint64 num48;
                // uint64 num49;

            };
        };
    };
};`

**Comment by wjbbupt** [comment]
For example, if you increase the length, you will not be able to find it.


module cyclonedds {
    module test {
        module test1 {
            // 通用下行数据格式，适用于远程控制、远程诊断、OTA
            struct demoMessage {
                uint32 messageId;
                @key
                uint16 businessType;
                uint64 businessId;
                uint64 timestamp;
                uint32 businessSubType;
                sequence<octet, 20480> payload;

                uint64 num0;
                uint64 num1;
                uint64 num2;
                uint64 num3;
                uint64 num4;
                uint64 num5;
                uint64 num6;
                uint64 num7;
                uint64 num8;
                uint64 num9;
                uint64 num10;
                uint64 num11;
                uint64 num12;
                uint64 num13;
                uint64 num14;
                uint64 num15;
                uint64 num16;
                uint64 num17;
                uint64 num18;
                uint64 num19;
                uint64 num20;
                // uint64 num21;
                // uint64 num22;
                // uint64 num23;
                // uint64 num24;
                // uint64 num25;
                // uint64 num26;
                // uint64 num27;
                // uint64 num28;
                // uint64 num29;
                // uint64 num30;
                // uint64 num31;
                // uint64 num32;
                // uint64 num33;
                // uint64 num34;
                // uint64 num35;
                // uint64 num36;
                // uint64 num37;
                // uint64 num38;
                // uint64 num39;
                // uint64 num40;
                // uint64 num41;
                // uint64 num42;
                // uint64 num43;
                // uint64 num44;
                // uint64 num45;
                // uint64 num46;
                // uint64 num47;
                // uint64 num48;
                // uint64 num49;

            };
        };
    };
};
//                 // uint64 num48;
//                 // uint64 num49;

//             };
//         };
//     };
// };

**Comment by wjbbupt** [comment]
union demotest switch(demotype) {
            case test:
                xxx;
            // case test1:
            //     xxx;
            // case test2:
            //     xxx;
            // case test3:
            //     xxx;
            };

**Comment by wjbbupt** [comment]
module cyclonedds {
    module test {
        module test1 {
            struct demoMessage {
                uint32 messageId;
                @key
                uint16 type1;
                uint64 typeId;
                uint64 timestamp;
                uint32 typeSubType;
                sequence<octet, 20480> payload;

                uint64 num0;
                uint64 num1;
                uint64 num2;
                uint64 num3;
                uint64 num4;
                uint64 num5;
                uint64 num6;
                uint64 num7;
                uint64 num8;
                uint64 num9;
                uint64 num10;
                uint64 num11;
                uint64 num12;
                uint64 num13;
                uint64 num14;
                uint64 num15;
                uint64 num16;
                uint64 num17;
                uint64 num18;
                uint64 num19;
                uint64 num20;
                // uint64 num21;
                // uint64 num22;
                // uint64 num23;
                // uint64 num24;
                // uint64 num25;
                // uint64 num26;
                // uint64 num27;
                // uint64 num28;
                // uint64 num29;
                // uint64 num30;
                // uint64 num31;
                // uint64 num32;
                // uint64 num33;
                // uint64 num34;
                // uint64 num35;
                // uint64 num36;
                // uint64 num37;
                // uint64 num38;
                // uint64 num39;
                // uint64 num40;
                // uint64 num41;
                // uint64 num42;
                // uint64 num43;
                // uint64 num44;
                // uint64 num45;
                // uint64 num46;
                // uint64 num47;
                // uint64 num48;
                // uint64 num49;

            };
        };
    };
};
