### ISSUE TITLE
reader created first，reader may can not receive first msg from writer

### ISSUE THREAD

**Issue by sgf201** [eclipse-cyclonedds/cyclonedds#1511]
The reader is created it first, and the writer is created a few minutes later, but it is possible that the reader  can not receive the first frame sent by the writer，but the second frame is Guaranteed
how could this happen？

**Comment by sgf201** [comment]
Confirm that success is returned in dds_write()

**Comment by thijsmie** [comment]
Hi @sgf201,

Even if the writer is created after creating the reader, DDS discovery is not instantaneous. If the writer writes data before the reader is discovered it the reader won't receive it directly. In this case it depends on the QoS settings what happens. If your Durability is set to `TransientLocal` and the History is `KeepLast(1)`, the writer will send one sample for each key value in its cache to the newly discovered reader. With `KeepAll` you will get everything as long as the writer history cache permits.

There is another strategy: if you know how many readers should be present for your writer you can wait for a status event to occur. The publication matched status tells you when readers are matched with your writer. This is the strategy our [helloworld example](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/examples/helloworld/publisher.c) writer uses too.

I hope this is sufficient explanation. Let me know if anything else is unclear.
