### ISSUE TITLE
Question: Which topic names are allowed?

### ISSUE THREAD

**Issue by Kischy** [eclipse-cyclonedds/cyclonedds#1512]
According to the DDS specification `a-z`, `A-Z`, `0-9` and a underscore `_` is allowed as topic name:
```
TOPICNAME - A topic name is an identifier for a topic, and is defined as any series of characters 'a', ..., 'z', 'A', ..., 'Z', '0', ..., '9', '_' but may not start with a digit.
```
no forward slash `/` is allowed in a topic name, but I saw that cyclonedds does allow it, because ROS2 does:
```
may contain alphanumeric characters ([0-9|a-z|A-Z]), underscores (_), or forward slashes (/)
```

ROS2 also allows a tilde `~` as a starting character of a topic
```
may start with a tilde (~), the private namespace substitution character
```
Does cyclonedds also allow a `~` as a starting character of a topic?

**Comment by thijsmie** [comment]
Hi @Kischy,

We've quite recently merged changes to what topic names are acceptable. So your question depends whether you are using a Cyclone release or the master branch. In case of using a release a topic name following `[a-zA-Z0-9_/]+` is still accurate. Pull request https://github.com/eclipse-cyclonedds/cyclonedds/pull/1426 changed that to "printable ascii except `*?[]"'#$`". You can look at the `dds_topic.c::is_valid_name` function to see how we validate topic names.

Thus the explicit answer to your last question is "yes" on master and "no" on `version<=0.10.2`.

**Comment by Kischy** [comment]
@thijsmie Thank you for the fast answer :)

**Comment by Kischy** [comment]
@thijsmie I have one more question, that is more or less of topic. Do you know if the DDS standard will change in the future to also allow ROS2 topics? 

Or in other words. Currently the standard allows topic names `[a-zA-Z0-9_]+`. Will the standard in the future allow topic names  `[a-zA-Z0-9_/]+` or even what cyclonedds is doing, e.g.  every ascii character except `*?[]"'#$` (I am really not sure how to do this one with regex, probably `[^?\[\]\"\'\#\$]+`, or as I would call it, _escape_ hell ;).

**Comment by thijsmie** [comment]
The speed of modifications to the DDS standard can be compared to the [pitch drop experiment](https://en.wikipedia.org/wiki/Pitch_drop_experiment) and I am not sure who would win. This means that Cyclone DDS adheres to the standard to achieve interoperability with other vendors but keep it flexible and practical. I have no clue if the ROS2 topic name style will ever be officially allowed by the DDS spec, and even if the ambition to allow it was there it would take a couple years to include it. I am however confident that the actual DDS implementations are all willing to deviate from the standard if that is what it takes.

**Comment by Kischy** [comment]
:D :D 
I had a chuckle over that one. Thank you for your answers.
