### ISSUE TITLE
Usage of dds_create_domain with config

### ISSUE THREAD

**Issue by reasokde** [eclipse-cyclonedds/cyclonedds#1513]
Hello.
I am creating my configuration programmatically. Now I stumbled across the documentation of dds_create_domain, understanding that you can configure an entire domain by means of xml. It is not quite clear to me, how that is applied because I find the documentation rather poor. Did I overlook a piece of documentation regarding this and/or do you provide a complete example?
kr, Robert.

**Comment by eboasson** [comment]
I just looked at the documentation, and I have to admit it is a bit ... lacking 😔 [This](https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/core/ddsc/tests/iceoryx.c#L57) is a fairly serious example, where it dynamically constructs the XML string and then creates the domain.

There are a few things to be aware of:

* When you do `dds_create_participant(X)` (X the domain id), it will create the "domain" entity automatically if it didn't already exist, and when you delete the last participant using the domain, it'll delete that "domain" entity also. However, when you explicitly call `dds_create_domain(X,config)`, you get a domain handle and *you* are the one who has to delete it. As always, the child entities get deleted along with it, so deleting the domain will delete all participants in it (in that one process, of course) and all they own.
* When you write an XML configuration file, it is required that all names are spelled out in full and that it starts with `CycloneDDS`, then `Domain` and then you have the settings. If you use the `CYCLONEDDS_URI` environment variable it will accept unique prefixes and it allows you to omit the `CycloneDDS` and `Domain` elements. `dds_create_domain` intentionally allows you to also omit those two top-level elements. That it is also allows the abbreviations is something I think so be changed.

Other than those two details, it is exactly the same as writing an XML configuration, pointing `CYCLONEDDS_URI` to it, and creating a participant.

There is also `dds_create_domain_with_rawconfig`, which is similar to `dds_create_domain` but allows you to bypass the XML parsing. I would recommend the XML route if you can accept that an XML parser is involved.

**Comment by poetinger** [comment]
Hello @reasokde,
I hope I can help clear things up with the configuration. When you specify a domain id in the configuration XML, the settings defined within are applied to that specific DDS domain unless you specify in the XML a keyword `any` in which case the settings are applied to *all* domains.

I can use the example XML given in our documentation [here](https://cyclonedds.io/docs/cyclonedds/latest/config/cyclonedds_specifics.html) to explain a bit what is going on.

Let's say we want to enable some `tracing` level logging on domain `n` (n being a valid domain id). We can set this in our non-programmatic XML by adding a domain `n`, with the specific settings contained within. Keep in mind, that if omitted, settings will maintain their default values. The XML blurb in our configuration file for the above would be:

```xml
<Domain Id="n">
 <Tracing>
   <Verbosity>config</Verbosity>
   <OutputFile>
     ${HOME}/dds/log/cdds.log.${CYCLONEDDS_PID}
   </OutputFile>
 </Tracing>
</Domain>
```

While I personally have not done it programmatically yet, from what I can tell from the code is that you would include what is inside the `<Domain></Domain>` in the function call as raw XML. So just:

```xml
<Tracing><Verbosity>config</Verbosity><OutputFile>${HOME}/dds/log/cdds.log.${CYCLONEDDS_PID}</OutputFile></Tracing>
```

Let me know if this helps!

**Comment by poetinger** [comment]
Indeed we (or at least I) had a bit of misunderstanding of your question. Configuration of a domain by XML in Cyclone is very different from the configuration provided by RTI Community in the link above. I'm not sure how useful that application creation by XML example is (the links contained are broken for me) as I have not used it before. I have not seen something similar used with Cyclone (though, my experience is limited so far). Now that your intention is a bit clearer, maybe @eboasson knows of something more.

Cyclone DDS domain configuration is for configuring the behaviour of entities in the domain, but not for defining the entities themselves.

**Comment by reasokde** [comment]
Thanks for the help and thanks in general for doing this. kr, Robert.
