### ISSUE TITLE
Built in types

### ISSUE THREAD

**Issue by reasokde** [eclipse-cyclonedds/cyclonedds#1532]
I'm wondering how to use XTypes built in types.
Currently I am using the RoundTrip example, which uses sequence of bytes. There should be a standard built in type for this which I would like to use.
But don't know how. Please provide an example or point to the documetnation.

kr, Robert.

**Comment by reasokde** [comment]
Hi.
Thanks for the response. I'm using C.
Yes, that is how I undestand the XTypes built-in types. Though it will depend on how distinctive the IDL compiler is with regards to target platforms. It might be just like you say with Cyclone. Due to experience, I suspect there to be a catch in it.
I hoped you had had implemented it ready for use, so I needn't worry about anything. At least, it's a piece of standard.

**Comment by reasokde** [comment]
Hi again. I just read the issue "About DDS-XTypes standard and C++ #53". It says, that XTypes is implemented not naming any exclusions. Since the built-in types are an object of the standard, I would not say it is resoundlingly implemented, rather fairly. Anyways, I think you do a great job and am happy that you do it.

**Comment by reasokde** [comment]
@eboasson Do you suggest me to contribute to the SDK with the built-in types? I would love to but I judge myself too fresh to dds to do so. I'm not aware of any consequences that may have.

**Comment by eboasson** [comment]
@reasokde well, it was indeed a suggestion. It is very easy to overlook something in the specs, and certainly Cyclone is not as easy to contribute to as I would like it to be (we do our best, but ...), and so I totally understand that you feel reluctant to give it a go.

There's just one thing that I do feel I have to say: I would not worry about the possible consequences. The way I see it, the worst that can happen is that a PR wouldn't be accepted in one go. I'd be happy to give feedback (on GitHub or discord, even the mailing list that hardly anyone uses 😂) if you change your mind and decide to give it a try. It is entirely up to you, I simply like Cyclone to have as many contributors as possible 🙂
