### ISSUE TITLE
`Iceoryx_LogLevel_Verbose` changed to `Iceoryx_LogLevel_Trace`

### ISSUE THREAD

**Issue by ast** [eclipse-cyclonedds/cyclonedds#1538]
HEAD (38aeacd81ba4f6818ff53d5226b7075b343a60c2) does not build with latest HEAD of iceoryx because `Iceoryx_LogLevel_Verbose` was changed to `Iceoryx_LogLevel_Trace`.

```
/home/albin/src/cyclonedds/src/core/ddsi/src/ddsi_shm_transport.c: In function ‘to_iox_loglevel’:
/home/albin/src/cyclonedds/src/core/ddsi/src/ddsi_shm_transport.c:59:40: error: ‘Iceoryx_LogLevel_Verbose’ undeclared (first use in this function); did you mean ‘Iceoryx_LogLevel_Error’?
   59 |         case DDSI_SHM_VERBOSE : return Iceoryx_LogLevel_Verbose;
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                        Iceoryx_LogLevel_Error
```

**Comment by eboasson** [comment]
Iceoryx changes its interface too often ... There should be no problems if you use Iceoryx 2.0.

**Comment by elBoberido** [comment]
@eboasson  we re-establish compatibility of master with v2.0 with https://github.com/eclipse-iceoryx/iceoryx/pull/1905. Would it be an issue to get a deprecation warning for the old log level?

**Comment by elBoberido** [comment]
@eboasson never mind, it will be merged without generating a warning.

**Comment by dkroenke** [comment]
@eboasson @ast Merged: https://github.com/eclipse-iceoryx/iceoryx/pull/1905

**Comment by eboasson** [comment]
Thanks @dkroenke and @elBoberido!

I don't see any reason to keep this issue open, but please do feel free to reopen it (or create a new one) if you disagree.
