### ISSUE TITLE
Entity limits of Cyclone

### ISSUE THREAD

**Issue by reasokde** [eclipse-cyclonedds/cyclonedds#1565]
Dear you.
I am interested in knowing the limitations of entities with Cyclone. I'm wondering if the kernel has hard limits on how many domains, pubs, subs partition aso. are applicable, apart from those that naturally come with the identifier datatypes. As I understand, it is written in C, so I would expect there to be some limitations. Are there any of them beyond the kernel?
kr, and thanks in advance. Robert.

**Comment by eboasson** [comment]
Interesting question 😀 There are a few, off the top of my head:

1. There can be 2^24-65537 (IINM) handles in a single process (this can be raised, it is basically `(INT32_MAX >> n)-m-1` for smallish but non-zero `n` and `m`). All entities including domains require a handle, so this automatically limits the maximum number of entities.
2. An empty domain requires 1 handle (IINM), so you can have approx. 2^24 domains simultaneously. Each domain instantiates a network stack, which in the default case of UDP generally requires at a unique UDP port number (though there is a configuration where there is just a single multicast socket and then they can share it, albeit very inefficiently).
3. Participants are nothing special, the way the GUIDs are constructed by Cyclone, there are no additional limits imposed other than the handles. (To have a participant, you need a domain, so 1 domain and approx. 2^24 participants is a possibility, but so is approx. 2^23 domains with 1 participant each.)
4. The max number of readers, writers and topics is determined by the maximum number of handles and the availability of entity ids in the GUIDs. The latter has to 24 bits, so with the choice of 2^24 handles, these are limited by the handles. If you were to raise the number of handles, you could theoretically bump into GUID entity id limit.
5. All other entity types (which in Cyclone includes waitsets and guard/read/query conditions) are limited only by handles. (I expect that at some point the publishers and subscribers will shift to category 4.)
6. There are no special limits on the number of readers/writers per subscriber/publisher, or whatever.
7. There are no special limits on the number of entities attached to a waitset, but there are some implementation choices to would have to be revised if you go all out on this point.
8. There are, in principle, no limits on discovered entities.
9. At a variety of places there are 32 bits counters (sometimes signed, or unsigned but with a reserved bit) for tracking all kinds of things (readers for a single subscriber, number of matching remote readers, &c., some of them visible in the API and coming from the spec). There are currently no protections for overflow of these, and I don't know all the exact limits either. Fortunately, hitting these limits in practice is nigh-on impossible, given the network traffic it would require.

I'm sure there are some details I have not thought of, but I expect those will turn out to be more generous than the above. It'd be interesting to know whether I got it right, by the way ...

(And finally, we are working towards the possibility of limiting them in the configuration, but's a different subject.)

**Comment by reasokde** [comment]
Thanks ofr the quick answer.
