### ISSUE TITLE
Some questions about  NetworkInterface

### ISSUE THREAD

**Issue by jahooooo** [eclipse-cyclonedds/cyclonedds#157]
Hi~ I found a strange phenomenon. I have two hosts. host1 has two networkinterfaces, one is _**10.67.164.220**_ and the other is _**192.168.1.3**_     host2 has one networkinterface and the address is **_192.168.1.10_**.   
However, when i config
`host1:
<NetworkInterfaceAddress>10.67.164.220</NetworkInterfaceAddress>
<MulticastRecvNetworkInterfaceAddresses>all</MulticastRecvNetworkInterfaceAddresses>`
`host2:
<NetworkInterfaceAddress>192.168.1.10</NetworkInterfaceAddress>
<MulticastRecvNetworkInterfaceAddresses>all</MulticastRecvNetworkInterfaceAddresses>`
the Helloworld example communicate each other .
i think the `<MulticastRecvNetworkInterfaceAddresses>all</MulticastRecvNetworkInterfaceAddresses>`
only join  all networkinterfaceaddresses into **_239.255.0.1_** and send messages through configed `<NetworkInterfaceAddress>` .
Thoes two hosts use different network segment networkinterface, why they can communicate each other? I use ping -I  and can't ping with each other .look forward to your explaination. Thank you!

**Comment by eboasson** [comment]
Hi @jahooooo ,

Multicasts can be routed, just like normal (unicast) packets are routed. I am not sure what is going on, but I would guess that the IP stack is routing data from one interface to another in the case of Cyclone's packets, but not for the ones sent by ``ping``. I'd try increasing the multicast time-to-live setting for ``ping``.

Just a note: if it works well with Cyclone in this mode and across interfaces, then by all means use it, but I have also seen systems where such routing doesn't work nicely. The general advice is therefore to be careful with that ``MulticastRecvNetworkInterfaceAddresses`` option.

**Comment by jahooooo** [comment]
Thanks for your explanation!  I changed `MulticastRecvNetworkInterfaceAddresses`  attribute from **all** to **specific networkinterfaces** , it seems work~
