### ISSUE TITLE
Linux target reboots when other device stops communication

### ISSUE THREAD

**Issue by reasokde** [eclipse-cyclonedds/cyclonedds#1582]
Hi.
I'm doing the ping-pong example. The ping program is running on my Linux target device. The pong is running on a different device, can be hosted on another Linux machine or a Windows host or even in another process on the same machine.
If I finish the pong program, my Linux target device is hard booting about 10 seconds later. The log file does not really say anything about the reason why it does.
Honestly, I made some bigger changes to the Pong program, but I belive in terms of dds, it behaves like the origin. I use listeners, though, and will try to apply the original pong and try it out during the remainder of this week.
I am using the settings as proposed in [#1337](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1337) but it does not help.
Do you have any idea, what happens there?

**Comment by eboasson** [comment]
> Linux target device is hard booting about 10 seconds later

Wow. That's not normal for Linux, I would say.

Nothing comes to mind immediately, but I do note that 10s is about the default lease duration. You could change the [lease duration in the configuration](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaindiscoveryleaseduration) to test whether this apparent correlation is (highly likely) causation.

If that's the case, at least we know more about the code it is executing, and that might help.

**Comment by reasokde** [comment]
It was not the lease duration. I used //CycloneDDS/Domain/Discovery/LeaseDuration as "1 min" in my configuration but it did all the same.

**Comment by reasokde** [comment]
Ok, I tried the ping-pong example on that very machine and another Windows and it works fine. I guess, I have to look closer at what I did there.
Sorry for bothering.
