### ISSUE TITLE
EntityId for the builtin participant reader

### ISSUE THREAD

**Issue by ex-purple** [eclipse-cyclonedds/cyclonedds#1608]
Hi,
My attempt to link CycloneDDS and EmbeddedRTPS failed. 

Based on my investigation, embeddedRTPS expects readerEntityId to be ENTITYID_BUILTIN_PARTICIPANT_READER but CycloneDDS provides ENTITYID_UNKNOWN:
<img width="1211" alt="Screenshot 2023-03-15 at 00 31 15" src="https://user-images.githubusercontent.com/729995/225144657-2cc965ec-0373-4327-b4f5-333bb4311cac.png">

Is this the expected behavior? For example, FastDDS has ENTITYID_BUILTIN_PARTICIPANT_READER value there.

**Comment by eboasson** [comment]
This is expected behaviour. There is nothing special about the handling of SPDP messages in the protocol, and so both setting the reader id to `UNKNOWN` or to `BUILTIN_PARTICIPANT_READER` are correct.

**Comment by ex-purple** [comment]
Thanks for the reply, I'll dig deeper
