### ISSUE TITLE
HistoryQos not working as expected

### ISSUE THREAD

**Issue by tez1szh** [eclipse-cyclonedds/cyclonedds#1616]
# Goal
Configure the publisher to cache the last 5 samples for the late-joined readers

# Sample Code
## idl
```idl
module HelloWorldData
{
  struct Msg
  {
    @key
    long userID;
    string message;
  };
};
```
## Publisher
```c
    dds_qos_t *qos = dds_create_qos();
    dds_qset_reliability(qos, DDS_RELIABILITY_RELIABLE, DDS_SECS(10));
    dds_qset_durability(qos, DDS_DURABILITY_TRANSIENT_LOCAL);
    dds_qset_history(qos, DDS_HISTORY_KEEP_LAST, 5);  // Not working as expected!
    writer = dds_create_writer(participant, topic, qos, NULL);

    dds_write(writer, {1001,"hello1"});
    dds_write(writer, {1001,"hello2"});
    dds_write(writer, {1001,"hello3"});
    dds_write(writer, {1001,"hello4"});
    dds_write(writer, {1001,"hello5"});
    dds_write(writer, {1001,"hello6"});
    dds_write(writer, {1001,"hello7"});
    dds_write(writer, {1001,"hello8"});
```

## Subscriber
```c
    qos = dds_create_qos();
    dds_qset_reliability(qos, DDS_RELIABILITY_RELIABLE, DDS_SECS(10));
    dds_qset_durability(qos, DDS_DURABILITY_TRANSIENT_LOCAL);
    dds_qset_history(qos, DDS_HISTORY_KEEP_LAST, 5);
    reader = dds_create_reader(participant, topic, qos, NULL);
```

# Test steps
1. start Publisher, send 8 samples(the same instance, with the same "@key") and sleep
2. start the "late-joined" Subscriber

# Observation
The lated-joined subscriber receives only the last sample

# Expectation
The lated-joined subscriber receives the latest 5 samples

According to DDS v1.4 - 2.2.3.18 HISTORY:
> If the kind is set to KEEP_LAST, then the Service will only attempt to keep the **latest values of the instance and
discard the older ones**. In this case, the value of depth regulates the maximum number of values (up to and including
the most current one) the Service will maintain and deliver. The default (and most common setting) for depth is one,
indicating that only the most recent value should be delivered.

Seems that CycloneDDS keeps only the lastest sample for a certain instance, not the one configured in HistoryQos. Is my understanding correct?

**Comment by eboasson** [comment]
> Seems that CycloneDDS keeps only the lastest sample for a certain instance, not the one configured in HistoryQos. Is my understanding correct?

Correct: Cyclone uses HistoryQos strictly for "live" data. It uses DurabilityServiceQos for all "historical" data. Doing that has two benefits:
* It allows you to make a keep-all writer (so all connected readers are guaranteed to get everything) that is at the same time provides the most recent 100 (or however many) to late-joining readers. I know of a few real-world examples where this capability was required, and this is the only clean way to make it possible — and I even know of other DDS implementors who could not help their users in such a case!)
* It provides for a much smoother path between transient-local and transient data (where the use of DSQ is mandated).

Also doing `dds_qset_durability_service(qos, 0, DDS_HISTORY_KEEP_LAST, 5, DDS_LENGTH_UNLIMITED, DDS_LENGTH_UNLIMITED, DDS_LENGTH_UNLIMITED)` on the writer side should do the trick.

**Comment by tez1szh** [comment]
Thanks @eboasson for the clarification! 👍 
And the `dds_qset_durability_service` works for me!
