### ISSUE TITLE
Command (dynsub "DDSPerfCPUStats")  is running incorrectly

### ISSUE THREAD

**Issue by hao47825148** [eclipse-cyclonedds/cyclonedds#1637]
Hi ,
I want to try using example/dynsub to subscribe to the topic "DDSPerfCPUStats" in ddsperf. Then dynsub will crash.
![image](https://user-images.githubusercontent.com/45707235/230265367-fe42c92b-052b-43f1-a3f8-4b0107295a89.png)
I type the command (ddsperf pub) on one terminal, then I type (dynsub DDSPerfCPUStats) on the other terminal.

Debugging in master branch :(ddsperf.c:2282 CPUStats_desc.m_flagset) != (dynsub.c:397 descriptor->m_flagset) .  

Is it caused dynsub crash? How to solve it ? 

thanks

**Comment by eboasson** [comment]
Thanks!

The differences in `m_flagset` was whether the serialised key would always fit in some fixed-size buffer. It was set correctly in `CPUStats_desc.m_flagset` (that is: key doesn't fit), and incorrectly in the dynamically constructed thing (that is: key does fit). That can have all kinds of nasty consequences, in this case a crash on trying to reallocate a non-malloc'd buffer.
