### ISSUE TITLE
When multiple nodes publish a topic simultaneously, the subscribing nodes cannot receive all the published data

### ISSUE THREAD

**Issue by FantasticSaltedFish** [eclipse-cyclonedds/cyclonedds#1661]
Set “time” and “object” topics, a timenode publishes “time” topic, and objectnode1, objectnode2, and objectnode3 subscribe to "time" topic. When objectnodes receive the time data, they also publish "object" topic immediately. Recvnode1 and recvnode2 subscribe to "object" topic, but recvnode1 and recvnode2 cannot receive all three "object" data that sent by three objectnodes.

The purpose of publishing and subscribing to time topics is to create a scenario where three objectnode nodes could publish simultaneously. There seems a flaw in this kind of corresponding scenario for cyclonedds, and I have conducted extensive testing to prove this. Additionally,I used wireshark to capture packets and found that the network datas have been received, but the recvnodes  did not receive all the "object" datas.

Could any one answer? Thanks very much.

**Comment by hansvanthag** [comment]
This might be a case of not having configured a history-depth (QoS) for the "object" reader(s) of you objectnodes.
As the default is a history-depth of 1, this means that its likely that received instances/samples of the "object" topic that arrive as a batch (following your pattern of 'immediately' publishing these samples upon receiving of a time-sample) will overwrite each-other at the reader-cache of your "Recvnode" readers .. which then looks like data is 'lost' but actually its actually correct behavior according to the specified history QoS. Alternatively you could add a key-field to your "object" topic that reflects the 'source' of the data and with that creating specific 'instances' (in DDS-speak) for the "object" data for each objectnode. By doing that, a history-depth of 1 is still ok as each 'flow' (coming from each object-node and identified by that key-attribute-value) and arriving at your recvnodes will have its own 'entry' (with lifecycle and history) in the reader-cache of a recvnode.

But I guess the simplest thing to do is to specify a (reasonable) history-depth for your Recvnode readers

**Comment by FantasticSaltedFish** [comment]
Thanks，you are right.Your method has solved the problem I encountered, but it is recommended to modify the default historical depth of the subscriber to a reasonable value.
