### ISSUE TITLE
building dds for android,but failed

### ISSUE THREAD

**Issue by mjunjun** [eclipse-cyclonedds/cyclonedds#1685]
I have already installed the android sdk.
Compiling the dds follow the steps in windows cmd:
1.cd cyclonedds
2.mkdir build.android
3.cd build android
4.cmake -DCMAKE_TOOLCHAIN_FILE=C:/User/Administrator/AppData/Local/Android/Sdk/ndk/25.2.9519653/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86 -DANDROID_NATIVE_API_LEVEL=28 -DBUILD_SHARED_LIBS=ON ..

An error occurred as :
CMake Error at CMakeLists.txt:13(project)
Running
'nmake' '-?'
failed with:
The system cannot find the specified file
--Configuring incomplete,errors occured!

What should I do to solve this problem? Thanks

**Comment by poetinger** [comment]
I hope the solution @noxpardalis mentioned above helps. @mjunjun if you have any more problems, feel free to re-open this issue!
