### ISSUE TITLE
Couldn't use the same string as enumrator in different enumration in IDL.

### ISSUE THREAD

**Issue by vecenyang** [eclipse-cyclonedds/cyclonedds#1690]
Please check the following IDL:

```
enum e1
{
    up,
    down,
    constant
};

enum e2
{
    cold,
    hot,
    constant
};
```

I declared 2 enumrations **e1** and **e2**, both of them use **constant** as enumrator. When I use idlc to generate the code, a error shows:

> /home/elsie/Desktop/enum.idl:12:5: Declaration 'constant' collides with an earlier declaration of 'constant'

I checked the IDL specification, there's no limitiation about that all enumrator in all enumration must be unique. So, is this an issue? can someone have a look?

**Comment by eboasson** [comment]
I'm afraid you have overlooked a detail in the IDL 4.2 specification:

> 7.5.2 Scoping Rules and Name Resolution
> [...]
> The following kinds of definitions form scopes: modules, structures, unions, maps, interfaces, value types, operations, exceptions, event types, components, homes.
> [...]
> An identifier can only be defined once in a scope. However, identifiers can be redefined in nested scopes.
> [...]
> Enumeration value names are introduced into the enclosing scope and then are treated like any other declaration in that scope. For example:
> ```
> interface A {
>   enum E { E1, E2, E3 }; // line 1
>   enum BadE { E3, E4, E5 }; // Error: E3 is already introduced into the A scope in line 1 above
> }
> ```

Overlooking things in OMG specifications is notoriously easy to do. It is almost as if overlookability is one of the attributes they optimise for 😵‍💫

So IDLC is correct here.

**Comment by vecenyang** [comment]
Sorry to bother you. I don't found that part before.
