### ISSUE TITLE
static discovery ？

### ISSUE THREAD

**Issue by wjbbupt** [eclipse-cyclonedds/cyclonedds#1715]
RTPS supports dynamic discovery, I want to know whether it supports static discovery, because no relevant information can be found, thank you

**Comment by eboasson** [comment]
The protocol is split into the actual pub/sub messaging part and the "simple discovery protocol" part. The messaging part requires that information on remote readers/writers is available, but it doesn't care where that came from.

So yes, static discovery is compatible with RTPS. Cyclone currently doesn't have a friendly interface for static discovery, but it is quite obvious how that can be done: you just have to do the same as the code handling the messages involved in dynamic discovery.
