### ISSUE TITLE
memory initialization in sertype_plist_realloc_samples maybe something wrong

### ISSUE THREAD

**Issue by binbowang1987** [eclipse-cyclonedds/cyclonedds#1735]
In the code below, the initialization action shold be done when `count > oldcount`, because there are some new elements allocated. 
https://github.com/eclipse-cyclonedds/cyclonedds/blob/fc51ab7edcdbecb408d9540a3b987e9aa6a3247f/src/core/ddsi/src/ddsi_sertype_plist.c#L62-L73

But, this code snippet can not initialize new elements.
```c
for (size_t i = count; i < oldcount; i++) 
       ddsi_plist_init_empty (&new[i]); 
```

**Comment by eboasson** [comment]
Thanks @binbowang1987 ! Quite an embarrassing mistake ... it won't have done any harm, but #1736 should fix it.
