### ISSUE TITLE
Assertion `d->identifier == CDR_LE || d->identifier == CDR_BE` can be remotely triggered

### ISSUE THREAD

**Issue by squizz617** [eclipse-cyclonedds/cyclonedds#1751]
Hi,
I've discovered that the following assertion in [ddsi_serdata_pserop.c](https://github.com/eclipse-cyclonedds/cyclonedds/blob/0.10.2/src/core/ddsi/src/ddsi_serdata_pserop.c#L78) can be triggered by sending malformed RTPS packets:
```
  assert (d->identifier == CDR_LE || d->identifier == CDR_BE);
```

After participant discovery packets are exchanged between a reader and a writer, the following malformed DATA submessage triggers the assertion failure (in the subscriber process in this case):

* Hexdump of the DATA submessage:
```
0000   15 05 cc 00 00 00 10 00 00 01 00 c7 00 02 00 c2
0010   00 00 00 00 01 00 00 00 00 03 00 00 15 00 04 00
0020   02 02 00 00 16 00 04 00 01 0f 00 00 50 00 10 00
0030   01 0f 11 3e f6 42 cd 90 00 00 00 00 00 00 01 c1
0040   32 00 18 00 01 00 00 00 f2 1c 00 00 00 00 00 00
0050   00 00 00 00 00 00 00 00 0a 00 00 0f 31 00 18 00
0060   01 00 00 00 f3 1c 00 00 00 00 00 00 00 00 00 00
0070   00 00 00 00 0a 00 00 0f 02 00 08 00 14 00 00 00
0080   00 00 00 00 58 00 04 00 3f 0c 00 00 62 00 10 00
0090   0a 00 00 00 70 75 62 6c 69 73 68 65 72 00 00 00
00a0   59 00 28 00 01 00 00 00 11 00 00 00 50 41 52 54
00b0   49 43 49 50 41 4e 54 5f 54 59 50 45 00 00 00 00
00c0   07 00 00 00 53 49 4d 50 4c 45 00 00 01 00 00 00
```

* stderr:
```
HelloworldSubscriber: /home/seulbae/ddssecurity/targets/cyclonedds-0.10.2/src/core/ddsi/src/ddsi_serdata_pserop.c:78: struct ddsi_serdata_pserop *serdata_pserop_new(const struct ddsi_sertype_pserop *, enum ddsi_serdata_kind, size_t, const void *): Assertion `d->identifier == CDR_LE || d->identifier == CDR_BE' failed.
Aborted
```

Attached are five different RTPS packets from the instances the assertion failure is observed. Thank you.
[cyclonedds-assert-rtps.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/11963955/cyclonedds-assert-rtps.zip)

**Comment by eboasson** [comment]
The problem seems quite obvious and if it really is, then https://github.com/eclipse-cyclonedds/cyclonedds/pull/1756 will fix it.

Clearly I need to improve the fuzzing ... it quickly gets tricky because of the statefulness of the protocols, but "tricky" is not a valid excuse. It looks like you are quite proficient at it, any interest in contributing to Cyclone by helping develop good fuzzers?

**Comment by squizz617** [comment]
Thank you. I'll run my test cases with #1756 applied and see if the fix works.

Regarding the fuzzer, I've developed a stateful fuzzer for DDS implementations. I'm planning to submit a paper soon and open-source the fuzzer once the paper gets accepted. After that, I'd be happy to contribute to CycloneDDS (e.g., adapting, specializing, ...)!

**Comment by squizz617** [comment]
Confirmed that #1756 fixes this issue. Thanks!

**Comment by eboasson** [comment]
Thanks for confirming @squizz617 ☺️
