### ISSUE TITLE
After running idlc,  always get a syntax error

### ISSUE THREAD

**Issue by ge65luz** [eclipse-cyclonedds/cyclonedds#1768]
Hey, 
I am trying to generate a new message type and therefor have written a .idl file. But when i try to run them, I always get a syntax error. These are the files I tried :
```
module std_msgs {
    struct String {
        string data;
    };
};
```

```
module std_msgs {
    module msg {
        struct String {
            string data;
        };
    };
};
```

or 
```

module CalculatorModule {
  interface Calculator {
    long add(in long num1, in long num2);
    long subtract(in long num1, in long num2);
  };
};
```

Do I have to include something else before I can run it?

After the basic installation of cyclone dds, it was not possible to run `idlc <file-name>`. It always showed " command not found". Only after i installed ros2 humble, it was possible to execute the command.

**Comment by xiaoyuyaa555** [comment]
I’m currently trying to use idlc but encountering some difficulties. Could someone please guide me on how to use idlc or provide some resources? Thank you very much!

**Comment by eboasson** [comment]
> I’m currently trying to use idlc but encountering some difficulties. Could someone please guide me on how to use idlc or provide some resources? Thank you very much!

You could try creating an issue for this in which you explain the difficulties. That'll probably improve the likelihood some can give you some help.

**Comment by xiaoyuyaa555** [comment]
> > 我目前正在尝试使用 idlc，但遇到了一些困难。有人可以指导我如何使用 idlc 或提供一些资源吗？谢谢！
> 
> 您可以尝试为此创建一个问题，在其中解释困难。这可能会提高一些人给你一些帮助的可能性。

Thank you for your reply. I’ve just started learning DDS and I’m also not very familiar with GitHub. Previously, I didn’t know how to use the idlc tool, but now I understand that I should install cyclonedds-tools first in order to use idlc tool.
