### ISSUE TITLE
Rebasing Security to Master Branch

### ISSUE THREAD

**Issue by kurtuluso** [eclipse-cyclonedds/cyclonedds#178]
Can you please rebase security branch to master branch?
I have a pull request and there are many changes on master.
Thanks

**Comment by eboasson** [comment]
No worries ...

That pull request is simply a fast-forward from the current state of that branch to one reasonably close to the head of master + 2 new commits, so it doesn't really matter that the PR includes a bunch of commits from master. I can simply ignore them.

And similarly, you can still rebase your own fork to include the latest changes on master if you want. In general, doing so may mean I will have to re-do a review — something I don't really appreciate — but for this particular PR, there is no overlap in the changes, which means that too is somewhat of a non-issue.

Things might change when there are overlapping updates on both branches, but right, it doesn't seem like it would any value.
