### ISSUE TITLE
MaxAutoParticipantIndex

### ISSUE THREAD

**Issue by Titikshaaaa** [eclipse-cyclonedds/cyclonedds#1785]
CycloneDDS/Domain/Discovery/MaxAutoParticipantIndex
Integer

This element specifies the maximum DDSI participant index selected by this instance of the Cyclone DDS service if the Discovery/ParticipantIndex is "auto".

The default value is: 9
Here i am setting this element to 2.
I expect that if i create 3 participant they will be assigned index from 0-2 . But when i will create 4 participant it will not connect. But it is working properly.
Not getting why

**Comment by eboasson** [comment]
Before I start getting worried, did you set `Discovery/ParticipantIndex` to `auto`? The "participant index" is only about UDP port numbers and unicast discovery, and if `Discovery/ParticipantIndex` is set to `none` (the default if multicast works) then it is not bothering with these at all.
