### ISSUE TITLE
identical condition

### ISSUE THREAD

**Issue by maddin200** [eclipse-cyclonedds/cyclonedds#1791]
src/security/builtin_plugins/tests/validate_remote_identity/src/validate_remote_identity_utests.c line 329
Code:
if ((strlen(token->class_id) != 0)             ||
            (token->properties._length != 0)           ||
            (token->properties._maximum != 0)          ||
            (token->binary_properties._buffer != NULL) ||
            (token->binary_properties._length != 0)    ||
            (token->binary_properties._maximum != 0)   ||
            (token->binary_properties._buffer != NULL) ) { // <-- identical
            printf("AuthRequestMessageToken is not a TokenNil\n");
            return 0;
        }

**Comment by dpotman** [comment]
Thanks for reporting! Fixed in https://github.com/eclipse-cyclonedds/cyclonedds/pull/1792
