### ISSUE TITLE
Invalid Discord invite link

### ISSUE THREAD

**Issue by simon-at-spire** [eclipse-cyclonedds/cyclonedds#1804]
Hi, I wanted to ask a question on your discord regarding test best practices with python cyclonedds, but none of the discord invites I could find worked:
- https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/README.md
- https://github.com/eclipse-cyclonedds/cyclonedds-python/blob/master/README.md
- https://cyclonedds.io/ (could be https://github.com/eclipse-cyclonedds/eclipse-cyclonedds.github.io/blob/master/pages/index.html#L80)

The invite link: `https://discord.gg/BkRYQPpZVV` leads me to an error page with the message: `This invite may be expired or you might not have permission to join.`

**Comment by eboasson** [comment]
Quick follow-up: I asked a friend and for him it works using the link in the README, but he did have to disable his adblocker. Or it could be a firewall, I know some corporate firewalls block discord so it can be done.

Given that it seems to work, I think it would be unwise to possibly sow confusion by publishing different invite links, at least until we discover that it is necessary.

**Comment by simon-at-spire** [comment]
My Bad, you are right, I opened another browser and the link worked. I almost never use Discord so I would never have thought that my adblocker/firewall/policies would cause this issue... I would have expected a more explicit error.

Thank you and sorry for raising this issue. At least it's documented now if someone else has the same problem/
