### ISSUE TITLE
Binding data streams to network interfaces. Possibility to use Multicast only.

### ISSUE THREAD

**Issue by i-and** [eclipse-cyclonedds/cyclonedds#181]
![3pc](https://user-images.githubusercontent.com/25042800/57554385-fb8bf000-7379-11e9-9c75-481aee3f914c.png)
1. The figure shows an example of a network configuration with 3 PCs and each has 2 network cards. In the PC 1 is N Datawriters with a total flow capacity greater than a single network interface card. In this regard, the question is: how can Cyclone explicitly bind each DataWriter and DataReader to a specific network card (within a single application)?
2. Can you briefly describe the algorithm of the Discovery procedure for this configuration with the appropriate configuration parameters (NetworkInterfaceAddress, ....)? 
3. Is it possible in Cyclone to disable rollback to unicast addressing usage (even when there is only one DataWriter and one DataReder) i. e. for any kind of interaction (discovery, transfer of samples) to use only Multicast with binding to network cards?
4. Is it impossible to create multiple Domains in the current implementation?

**Comment by eboasson** [comment]
> The figure shows an example of a network configuration with 3 PCs and each has 2 network cards. In the PC 1 is N Datawriters with a total flow capacity greater than a single network interface card. In this regard, the question is: how can Cyclone explicitly bind each DataWriter and DataReader to a specific network card (within a single application)?

At the moment, it can't. The primary limitation is that it currently shares sockets between the readers and writers, and routing multicast traffic to a certain network interface is done via socket options.

For creating multiple sockets, I've thought a few times that it would be better if the "network partitions" would (optionally) map to separate sockets. If they'd then also specify a network interface, you'd already be 90% there. It's probably a straightforward thing to do — it even dynamically joins/leaves multicast groups based on the multicast addresses in those network partitions, so how hard can it be to also use a separate socket? — but I don't think you can trick it into doing this today.

> Can you briefly describe the algorithm of the Discovery procedure for this configuration with the appropriate configuration parameters (NetworkInterfaceAddress, ....)?

Sadly, I think the answer to the first question means this one becomes irrelevant.

Except ... in extremis ... if the kernel performs multicast routing for outgoing traffic according to its routing tables if no interface has been set for outgoing traffic, then the following will most likely work:
* skip the ``setsockopt(..., IF_MULTICAST, ...)`` calls;
* setting ``General/MulticastRecvNetworkInterfaceAddresses`` to ``all``;
* specifying network partitions mapping the topics to different multicast addresses;
* using a _firewall_ to block traffic for these specific multicasts from going out on the "wrong" interface.

It is somewhat crazy, though 😁

> Is it possible in Cyclone to disable rollback to unicast addressing usage (even when there is only one DataWriter and one DataReder) i. e. for any kind of interaction (discovery, transfer of samples) to use only Multicast with binding to network cards?

Not without a patch. I've done it once or twice before, though, and I have problem with adding an option to select such behaviour. The nice thing is that the decision which address(es) to use is taken by a single function (``rebuild_writer_addrset``). Ignore the unicast addresses and it automatically switches to multicast only — you could even check whether that reader is advertising multicast addresses and use the unicast addresses if not.

This:

https://github.com/eclipse-cyclonedds/cyclonedds/blob/dba4e6d391a75440654b740f389e72256858a3bf/src/core/ddsi/src/q_entity.c#L980-L987

is the loop where it collects the advertised addresses of all the readers, which is the input to the simple greedy set cover algorithm that it uses. If you'd do something like:
```C
if (!addrset_empty_mc(all_addrs, prd->c.as))
  copy_addrset_into_addrset_mc(all_addrs, prd->c.as);
else
  copy_addrset_into_addrset(all_addrs, prd->c.as);
```
I'm pretty sure you'd have just that. (The test is just there for the odd case where some readers might be running without multicast support, which seems unlikely in your setup.)

> Is it impossible to create multiple Domains in the current implementation?

At the moment it is impossible: there are some global variables in the way. The vast majority of them are stuck in the ``config`` and ``gv`` structs. I've not yet got around to passing round a pointer to a domain structure that stores this data, but that is very much something that's on the agenda.

**Comment by i-and** [comment]
> For creating multiple sockets, I've thought a few times that it would be better if the "network partitions" would (optionally) map to separate sockets. If they'd then also specify a network interface, you'd already be 90% there. It's probably a straightforward thing to do — it even dynamically joins/leaves multicast groups based on the multicast addresses in those network partitions, so how hard can it be to also use a separate socket? — but I don't think you can trick it into doing this today.

Regarding the use of DDSI_INCLUDE_NETWORK_PARTITIONS to bind topics for physical interfaces: 
1. There is an "Address" parameter in the configuration, but it is not enough to bind to the interface. It is necessary to enter additional parameters - with indexes/Unicast-addresses of interfaces;
2. From the writer's probably have to adjust the logic to work with sockets so as to send the samples need to be a specific Ethernet port; 
3. Restructuring in terms of work with sockets probably makes sense to implement with modifications in DDSI_INCLUDE_NETWORK_CHANNELS (DSCP prioritization+flow control #72 )? 
4. Maybe it makes sense to abandon the use DDSI_INCLUDE_NETWORK_PARTITIONS and integrate functions of the address and interface selection to the DDSI_INCLUDE_NETWORK_CHANNELS? At the same time, it may be worth changing the algorithm for linking topics to channels - to implement the possibility of redundancy, when the topic can be sent/received on several specific interfaces (can use QOS::transport_priority as a bit mask with the numbers of logical channels used)?

>*using a firewall to block traffic for these specific multicasts from going out on the "wrong" interface.
It is somewhat crazy, though :grin:

Very creative offer, but I would like to do without firewall. :grin:

> I've done it once or twice before, though, and I have problem with adding an option to select such behaviour. 

Is it possible to support disabling Unicast at the Cyclone configuration level?

**Comment by eboasson** [comment]
Thanks for your thoughtful comments

> Regarding the use of DDSI_INCLUDE_NETWORK_PARTITIONS to bind topics for physical interfaces:
>
> 1. There is an "Address" parameter in the configuration, but it is not enough to bind to the interface. Probably, it is necessary to enter additional parameters - with indexes/Unicast-addresses of interfaces;

Sorry for being rushed when I wrote that: yes, it would require that additional information.

> 2. Writer have to adjust the logic to work with sockets so as to send the samples need to be a specific Ethernet-port;

Indeed. A dynamic address-to-socket lookup shouldn't be too expensive, but pre-computing it would still be faster as it already has to iterate over the elements in an ``addrset``. So I do think it would be worth seeing whether those can be enhanced to include the socket to use.

> 3. Given the relative stability of the structure of embedded applications, it would be nice to be able to possibility of static configuration of interaction participants (unicast addresses, multicast addresses, UDP-port, Ethernet-port, DSCP, flow control,....), . This will speed up the delivery of the first sample and provide more reliable operation for some scenarios;

True, and I know various other implementations offer the possibility of static discovery to do just that, so there is precedent in the context of a DDSI implementation as well. I think those all require configuring the GUIDs as well, but that is but a minor step.

Skipping participant discovery would create problems with reliable communications when an expected participant isn't present, but I imagine there is a large class of systems for which that would not actually be a problem — many hard real-time systems run on best-effort data anyway.

> 4. Restructuring in terms of work with sockets probably makes sense to implement with modifications in DDSI_INCLUDE_NETWORK_CHANNELS (DSCP prioritization+flow control #72 )?

Yes. I had the plan of reworking those network channels to become what several other implementations call "asynchronous publishers", and where you would define channels as a region in the priority, topic, partition and latency budget. Any writer not matching a channel would then behave as it does now, giving you the lowest possible latency.

> 5. Maybe it makes sense to abandon the use DDSI_INCLUDE_NETWORK_PARTITIONS and integrate functions of the address and interface selection to the DDSI_INCLUDE_NETWORK_CHANNELS? At the same time, it may be worth changing the algorithm for linking topics to channels - to implement the possibility of redundancy, when the topic can be sent/received on several specific interfaces (can use QOS::transport_priority as a bit mask with the numbers of logical channels used)?

I am not yet ready to abandon the split between address mapping and channels; but the idea that you could define a network partition in such a way that it forces data over multiple interfaces for redudancy is something I rather like.

That said: I'm trying to think what uses I have seen of network partitions ... in reality they indeed might go quite well together. Then it becomes more a matter of limiting resource usage (sockets & threads) than anything else.

It is an interesting suggestion ...

> Very creative offer, but I would like to do without firewall. 😁

Wise decision!

> Is it possible to support disabling Unicast at the Cyclone configuration level?

I've pushed a commit to a branch on my own fork that makes it possible to configure this by setting General/PreferMulticast to true: 9499384af0c6beb0bf2012c8fa9f8eacd98494e2. In principle I am happy to merge it into the master, but it sits on top of PR #183 ... and I want to give others a chance to comment on that PR as well. (The one has absolutely nothing to do with the other.)

**Comment by thijsmie** [comment]
PreferMulticast was merged and released. This discussion is at an end, although it contains useful info!
