### ISSUE TITLE
Any way to get topic of a incoming msg?

### ISSUE THREAD

**Issue by wanghaEMQ** [eclipse-cyclonedds/cyclonedds#1813]
Hello everyone.

I created a DDS client and subscribed to multiple topics like the example roundtrip did.
Is there any way to know which topic an incoming msg from?

Thanks.

**Comment by wanghaEMQ** [comment]
I think I have resolved this problem.
I created a map whose key is a reader (type of dds_entity_t) and the value is a topic.
When data is available, I could get the topic by query map with a reader (the first argument in callback).

**Comment by eboasson** [comment]
@wanghaEMQ  That sounds like a reasonable approach 👍
