### ISSUE TITLE
cross compile error.

### ISSUE THREAD

**Issue by wuyanze0226** [eclipse-cyclonedds/cyclonedds#1827]
Hello ,i'm doing corss_compile in linux, to use it  in android, I use NDK,. In CMakeLists.tx file, i set "set(CMAKE_C_COMPILER "/opt/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang")".but i failed. Error like this:

/bin/sh: 1: ../../../bin/idlc: Exec format error
make[2]: *** [src/tools/ddsperf/CMakeFiles/ddsperf_types_generate.dir/build.make:64: src/tools/ddsperf/ddsperf_types.c] Error 2
make[1]: *** [CMakeFiles/Makefile2:520: src/tools/ddsperf/CMakeFiles/ddsperf_types_generate.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

Could you help me? Thanks so much.

![屏幕截图 2023-09-15 201442](https://github.com/eclipse-cyclonedds/cyclonedds/assets/78069913/5c7c7a53-d6e1-4e48-ae48-c7e4ff98f837)

**Comment by XQSwx** [comment]
How did you solve it? I have the same problem now
