### ISSUE TITLE
OpenEuler 22.03SP2  use cyclonedds

### ISSUE THREAD

**Issue by gongqinpeng** [eclipse-cyclonedds/cyclonedds#1849]
I want to use cyclonedds on openEuler, but I have this question

In cyclonedds.xml, I write this
`<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain Id="any">
        <General>
            <Interfaces>
                <NetworkInterface autodetermine="true" priority="default" multicast="false" />
            </Interfaces>
            <AllowMulticast>default</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
        </General>
        <Discovery>
            <EnableTopicDiscoveryEndpoints>true</EnableTopicDiscoveryEndpoints>
        </Discovery>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>cdds.log.${CYCLONEDDS_PID}</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
`
multicast = false

But I am currently using cyclonedds on multiple computers in my local area network, if I change the "multicast", I can't even achieve publish and subscribe on one computer.
I need you help, thanks!

**Comment by eboasson** [comment]
Usually the two best settings are "true" and "spdp": "true" if you want to use it for everything, "spdp" if you only want to use it to discover other participants and then use unicast for everything else.

If neither works, then I am wondering if perhaps there's a firewall that blocks them (has happened to me quite a few times!) or if there multiple network interfaces on different machines and the `<NetworkInterface autodetermine="true"` screws it up.

If multicast just doesn't work, not all is lost, by the way: then you need to go full unicast discovery mode. In that case, you need to set `Discovery/ParticipantIndex` to `auto` and add the machines in `Discovery/Peers` with a `<Peer address="..."/>` for each machine.

If this is not enough to get help you get moving again, let me know. I'm in a rush now, but I can give a more detailed answer or links to other responses some other time ...

**Comment by gongqinpeng** [comment]
> Usually the two best settings are "true" and "spdp": "true" if you want to use it for everything, "spdp" if you only want to use it to discover other participants and then use unicast for everything else.
> 
> If neither works, then I am wondering if perhaps there's a firewall that blocks them (has happened to me quite a few times!) or if there multiple network interfaces on different machines and the `<NetworkInterface autodetermine="true"` screws it up.
> 
> If multicast just doesn't work, not all is lost, by the way: then you need to go full unicast discovery mode. In that case, you need to set `Discovery/ParticipantIndex` to `auto` and add the machines in `Discovery/Peers` with a `<Peer address="..."/>` for each machine.
> 
> If this is not enough to get help you get moving again, let me know. I'm in a rush now, but I can give a more detailed answer or links to other responses some other time ...

Thank you very much ! I already solved this question yesterday. As you said, the firewall blocks them, after closing the firewall, all programs can be discovered normally. Thank you very much!

**Comment by eboasson** [comment]
Thanks for letting me know ☺️
