### ISSUE TITLE
Cyclone IDL Parser crash when using a magic variable name

### ISSUE THREAD

**Issue by trittsv** [eclipse-cyclonedds/cyclonedds#1852]
Using CycloneDDS 0.10.4.

Hey when i name a variable `BitMask` then idlc crashes.

It works with opensplice and rti - so i guess its allowed in the standard to name a variable like that.
Do you agree with that @eboasson ?

### Error Case
```
struct VMaskLS
{
    boolean Polygon;
    boolean BitMask;
};
```
It crashes with the message `test.idl:4:24: syntax error`
Cyclone ⛔ 
Opensplice   🆗 
RTI Connext  🆗 

### Good Case
```
struct VMaskLS
{
    boolean Polygon;
    boolean BitMaskX;
};
```
Cyclone 🆗
Opensplice  🆗 
RTI Connext 🆗

**Comment by dpotman** [comment]
Identifiers in IDL are case-insensitive by default (IDL spec section 7.2.3), so that's why `idlc` reports the collision with the keyword. If you add the `-f case-sensitive` option to `idlc` on the command line, it won't complain anymore.
