### ISSUE TITLE
Is shared memory no longer supported?

### ISSUE THREAD

**Issue by ex-purple** [eclipse-cyclonedds/cyclonedds#1883]
Hi there,
I have a problem with shared memory usage on master:
`config: //CycloneDDS/Domain/SharedMemory: 'Enable': deprecated element`
`config: //CycloneDDS/Domain/SharedMemory: 'LogLevel': deprecated element`

Is shared memory no longer supported? Or maybe [this documentation](https://cyclonedds.io/docs/cyclonedds/latest/shared_memory/shared_mem_config.html) is deprecated?

**Comment by eboasson** [comment]
Oops. The documentation is outdated.

The code for integrating Iceoryx used to be "hard-coded", with references to Iceoryx in various place in the Cyclone sources. We refactored it out into a plugin-based mechanism (see #1676) and added a plugin for Iceoryx in the sources. The "correct" way of configuring now looks like:

```
<General>
  <Interfaces>
    <PubSubMessageExchange name="iox" library="psmx_iox" config="LOG_LEVEL=INFO;"/>
  </Interfaces>
</General>
```

The old settings continue to work with a warning. They just translate the old (unchanging) configuration to the new format so they'll probably be around for quite some time.

**Comment by ciandonovan** [comment]
Are there plans to use this new plugin interface to provide other shared-memory providers beside Iceoryx? Maybe a daemon-less one, similar to what FastDDS does? Use the loopback just for discovery, handshakes, etc. before coordinating on the shared-memory segment to use? Have had issues with Iceoryx crashing with a large amount of nodes, would be nice if there wasn't a single point of failure as currently everything must be restarted if Iceoryx crashes AFAIK.

**Comment by Gummum** [comment]
The shared memory example has been removed. How can I test it

**Comment by dibsonmuad** [comment]
On ROS2 Humble, 
```
<General>
  <Interfaces>
    <PubSubMessageExchange name="iox" library="psmx_iox" config="LOG_LEVEL=INFO;"/>
  </Interfaces>
</General>
```
did not work. I 
What worked for me was 
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/iceoryx/etc/cyclonedds.xsd">
    <Domain id="any">
        <SharedMemory>
            <Enable>true</Enable>
            <LogLevel>info</LogLevel>
        </SharedMemory>
    </Domain>
</CycloneDDS>
```
Do I still have to launch `iox-roudi -c iox_config.toml` separately if using shared memory?

Thanks
