### ISSUE TITLE
Cyclone DDS - Issue with Enum Type generation 

### ISSUE THREAD

**Issue by Aman568** [eclipse-cyclonedds/cyclonedds#1899]
Hello,

When the Enum is provided in the IDL file of the Cyclone DDS then it does not generate Topic descriptor. In this case how to create a topic without a topic descriptor.  Could you please check and let us know how we can use enum in the Cyclone DDS.

IDL Contents
![Uploading image.png…]()
module HelloWorldData
{
enum A {
    ALITERAL,
    BLITERAL
};
};

IDL OUTPUT
![image](https://github.com/eclipse-cyclonedds/cyclonedds/assets/66157831/4dec1688-fbcc-4d7d-a893-4695ef8a6210)

Thank You
Best Regards
Aman

**Comment by eboasson** [comment]
That's correct: it generated the enum definition in C and nothing else, as expected.

If you want to define a type to be used as a topic, it must be a `struct`. So if you want to send only an enum, you still need to define a struct with just that enum as its contents.

**Comment by Aman568** [comment]
Dear @eboasson ,

Thanks for providing the clarification. 

Best Regards 
Aman
