### ISSUE TITLE
Create reader or writer with participant mismatch.

### ISSUE THREAD

**Issue by martinbremmer** [eclipse-cyclonedds/cyclonedds#190]
Consider the following.
There are two participants.
A publisher (and/or subscriber) is created on participant A.
A topic is created on participant B.

Now, I can create readers and writers with this publisher/subscriber and topic. I would expect it to fail because they have different participants, but it doesn't fail. Is my expectation correct? Can this cause issues?

Test example can be found here:
https://github.com/martinbremmer/cyclonedds/commit/2a196d75480914252697bdf22250087e435960a4

**Comment by eboasson** [comment]
Certainly there is plenty of reason to expect failure and I do think the principle of least surprise would require the topic to be owned by the same participant (and consequently, to allow two independent topic objects to exist in two participants for the same topic, though with the requirement that they have a compatible definition).

As to problems ... if I reversed-engineerd this part correctly, the topic will be referenced by the reader/writer in A and won't actually be deleted until both participant B and the readers/writers that use the topic are deleted. So I think in practice the practical problems will be limited to topic discovery (which isn't there yet — #42).

**Comment by eboasson** [comment]
@martinbremmer, #246 fixes this — I just forgot to reference the issue. Your test would of course still be a welcome addition.
