### ISSUE TITLE
does cyclone support LastValue Cache？

### ISSUE THREAD

**Issue by wjbbupt** [eclipse-cyclonedds/cyclonedds#1910]
Hello, there are a few questions I need to consult,

1. Excuse me, does cyclone support LastValue Cache?

2. If supported, how can this be used?

3. If not supported, do we need to make some changes to the protocol layer by combining QoS to achieve it?

Or there are some suggestions and ideas on how to implement the function of LastValue Cache

We are also interested in this area and look forward to your reply. Thank you very much

**Comment by wjbbuptwjb** [comment]
@clalancette @kartben @lygstate @rotu

**Comment by eboasson** [comment]
@wjbbupt @wjbbuptwjb Please don't spam random people if you have a question on Cyclone. I am sorry your question remained unanswered for a while, please bear in mind that it was the holiday season and lots of people were offline. (Including me.)

The answers to your questions:

1. Yes. It is basic DDS functionality, and as the README specifies, all the basic stuff is there.
2. The `KEEP_LAST` policy (the default) does it.
3. Not applicable.
