### ISSUE TITLE
Configure Cyclone 0.10.0 to use multiple network interfaces

### ISSUE THREAD

**Issue by benoit-robotics** [eclipse-cyclonedds/cyclonedds#1915]
I am using ROS 2 Humble with cyclonedds ( 0.10.0 ). Here is my setup : 
Machine A has two network interfaces : enx00e04c1028d9 ( 192.168.4.100 ) and eno1 ( 192.168.0.100).
Machine B has a single network interface and is connected to machine A. Its ip is 192.168.0.43. 
Machine C has a single network interface and is connected to machine A. Its ip is 192.168.4.101. 

Machine A has the following cyclone.xml configuration file :

![image](https://github.com/eclipse-cyclonedds/cyclonedds/assets/41473839/42f992f0-e4bf-409f-b07d-be7af32a5c46)

If I publish a topic on machine A, only C can see it. But if I change the order of the interfaces in the xml file : 
>       <Interfaces>
>         <NetworkInterface name='eno1'/>
>         <NetworkInterface name='enx00e04c1028d9'/>
>       </Interfaces>

Then only B can see the topic. I would like the topics published on A to be visible on all the computers on the network, ie B and C. How can I do that on Humble with cyclone 0.10.0 ? With the same network topology, I used to be able to do that with ROS 2 galactic ( cyclone 0.8.0 ). Thanks.

PS : 
I have read https://github.com/eclipse-cyclonedds/cyclonedds/issues/1190 and https://github.com/eclipse-cyclonedds/cyclonedds/issues/1422 but I couldn't figure out a solution to my problem from these two issues.

**Comment by tonynajjar** [comment]
Hi @benoit-robotics, I have the same case as you. I see you closed the issue, did you manage to solve it? how?

**Comment by krishnakanthatartpark** [comment]
@benoit-robotics how did you achieve sending it to two different interfaces
