### ISSUE TITLE
flowcontronal   is  ok  ？

### ISSUE THREAD

**Issue by wjbbuptwjb** [eclipse-cyclonedds/cyclonedds#1918]
Hello, I experimented and looked at the source code, and found that the current version does not have flow control-related content;
I have a few thoughts on flow control development:
1. I want to make a cache queue in writer_sample for flow control. I should need two queues, one is the cache queue and the other is the consumption queue.
2. Flow control sending needs to be sent at a certain interval. I am thinking about sending modified timers and sending them at a certain period.
3. The advantage of doing the above is that you can control the cycle of sending messages.

my question is:
1. Is the above method reasonable?
2. Or do you have any other suggestions?
3. Does the current architecture really need flow control?

**Comment by wjbbuptwjb** [comment]
@rotu @lygstate @kartben @clalancette

**Comment by wjbbuptwjb** [comment]
But I also found that the function sent is ddsi_xpack_send, which is called extra times. Do you have any suggestions on how to implement this logic?

**Comment by eboasson** [comment]
@wjbbuptwjb please do not go spam random people when you are not getting a response quickly. First try bumping the issue. There times when holidays or various obligations cause long latencies, but we do pay attention.

Flow control is useful, no question about it. The idea of scheduling it is also often good although there are also cases where you really don't want to wait until the next cycle, so the idea needs some refinement.

About the queues, what you really want to do is use the writer history caches as the buffering mechanism for the data, then have a thread to extract the data from the various writer history caches in the order in which it was published (ideally taking into account the "latency budget" and the transport priority QoS settings). Within a writer the order is easy (you have sequence numbers), across writers you could look at time stamps, but that could well be a bit tricky if you want to use O(n writers) memory.

It does involve some careful bookkeeping ...
