### ISSUE TITLE
New release of the 0.10.x branch (probably 0.10.5)

### ISSUE THREAD

**Issue by clalancette** [eclipse-cyclonedds/cyclonedds#1979]
I'd like to request a new release of CycloneDDS from the 0.10.x branch so we can have the latest fixes from it.  That would help out with the ROS 2 Jazzy release.

Let me know if you need any information or anything else from me.

**Comment by kumar-akshay324** [comment]
Can we get any updates here @eboasson ? We haven't had a new release in almost 8 months. Would be really helpful to use a tagged verified release than deploying the top of `develop`

**Comment by clalancette** [comment]
My understanding is that this is blocked on https://github.com/eclipse-cyclonedds/cyclonedds/pull/1980 at the moment.

**Comment by eboasson** [comment]
Sorry it took so long ... but it is finally done. As @clalancette guessed, it is called `0.10.5`.

You were using the `releases/0.10.x` branch, so I'm pretty sure the only change for ROS 2 is the version number and the existence of a tag.
