### ISSUE TITLE
Python lib determination is not platform independent

### ISSUE THREAD

**Issue by trittsv** [eclipse-cyclonedds/cyclonedds#2050]
It uses `python3` executable to determine the python libs, but on windows there is no `python3.exe`.
The windows python3 installer creates only `python.exe`.

See here:
https://github.com/eclipse-cyclonedds/cyclonedds/blob/d7db65c7f9def668af029890c351de6186977d58/src/tools/idlc/src/idlc/generator.c#L167

Of course a easy workaround is to duplicate the `python.exe` on windows and rename it to `python3.exe` ...

**Comment by eboasson** [comment]
What could go wrong if, on failure of the existing test, we simply tried again but using plain `python`? It would still need to have `cyclonedds.__idlc__` available and so even if that causes it to start python 2 it seems to me it should be ok.
