### ISSUE TITLE
looks like DDS_OP_JSR is not needed anymore

### ISSUE THREAD

**Issue by binbowang1987** [eclipse-cyclonedds/cyclonedds#2056]
As descripted in dds_opcodes.h, DDS_OP_JSR is used for recursive types.
https://github.com/eclipse-cyclonedds/cyclonedds/blob/ce7cf3dc05041db863396466c20971ba6fca6bd5/src/core/ddsc/include/dds/ddsc/dds_opcodes.h#L289-L295

I try to generate type support code with the following idl. There is no `DDS_OP_JSR` operator in the generated code.
```idl
module HelloWorldData
{
    struct MsgSubRecursive {
        unsigned long submsg_field1;
        sequence<MsgSubRecursive> submsg_field2;
        long submsg_field3;
    };

    struct MsgRecursive {
        unsigned long msg_field1;
        MsgSubRecursive msg_field2;
        unsigned long msg_field3;
    };
};
```

```C
static const uint32_t HelloWorldData_MsgSubRecursive_ops [] =
{
  /* MsgSubRecursive */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (HelloWorldData_MsgSubRecursive, submsg_field1),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (HelloWorldData_MsgSubRecursive, submsg_field2), sizeof (HelloWorldData_MsgSubRecursive), (4u << 16u) + 65534u /* MsgSubRecursive */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (HelloWorldData_MsgSubRecursive, submsg_field3),
  DDS_OP_RTS
};

const dds_topic_descriptor_t HelloWorldData_MsgSubRecursive_desc =
{
  .m_size = sizeof (HelloWorldData_MsgSubRecursive),
  .m_align = dds_alignof (HelloWorldData_MsgSubRecursive),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "HelloWorldData::MsgSubRecursive",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = HelloWorldData_MsgSubRecursive_ops,
  .m_meta = ""
};
```

So, does `DDS_OP_JSR` still needed?

**Comment by eboasson** [comment]
Wow, you've been reading the code closely 😀☺️🙏

You're right, it doesn't generate `DDS_OP_JSR` anymore. We've kept it around because it was pretty easy to maintain backwards compatibility for IDLC output, and then at some point it became somewhat of a sport 😂

We did stop checking it, but I expect you can use the output from the IDLC in the initial commit of Cyclone without any modifications.

**Comment by binbowang1987** [comment]
Yeah, I got it, thanks for your reply.
