### ISSUE TITLE
An implementation for dds_stream_writeLE could not be found

### ISSUE THREAD

**Issue by ff20509** [eclipse-cyclonedds/cyclonedds#2060]
Hello, why did I search globally for the dds_stream_writeLE function and only found the function declaration but not the implementation?

**Comment by dpotman** [comment]
To avoid code duplication for the little-endian, big-endian and native byte order variants of these functions, we use an include file with a generic implementation. The definition for this function is in [dds_cdrstream_write.part.h](https://github.com/eclipse-cyclonedds/cyclonedds/blob/d9172120ef0f84c7bcc80b93a0595f082d022010/src/core/cdr/src/dds_cdrstream_write.part.h#L636) that is included [here](https://github.com/eclipse-cyclonedds/cyclonedds/blob/d9172120ef0f84c7bcc80b93a0595f082d022010/src/core/cdr/src/dds_cdrstream.c#L1429).

**Comment by ff20509** [comment]
Thanks for the answer, I still have some premature questions. Is dds_stream_writeLE and dds_stream_writeBE the common implementation of dds_stream_writeBO?I see that the header of dds_cdrstream.c has the macro definition #define dds_stream_writeBO NAME_BYTE_ORDER(dds_stream_write), But it does not include the file dds_cdrstream_write.part.h until after it. There seems to be a missing step to make a connection between dds_stream_writeLE and dds_stream_writeBO.

**Comment by dpotman** [comment]
[`dds_stream_writeBO`](https://github.com/eclipse-cyclonedds/cyclonedds/blob/d9172120ef0f84c7bcc80b93a0595f082d022010/src/core/cdr/src/dds_cdrstream.c#L79) is a macro that is expanded each time `dds_cdrstream_write.part.h` is included, and the `NAME_BYTE_ORDER` macro concatenates the function name (`dds_stream_write`) and the byte order extension (`LE`, `BE` or empty string for native) that results in the actual function name (as declared in [dds_cdrstream.h](https://github.com/eclipse-cyclonedds/cyclonedds/blob/d9172120ef0f84c7bcc80b93a0595f082d022010/src/core/cdr/include/dds/cdr/dds_cdrstream.h#L175)) The function body is expanded three times for these three function names.

**Comment by eboasson** [comment]
Presumed answered in sufficient detail.
