### ISSUE TITLE
MultiThread Assert Issue

### ISSUE THREAD

**Issue by stillsimon** [eclipse-cyclonedds/cyclonedds#208]
Hi, when I use CycloneDDS in multi thread environment. It will show "assert (thread_states.ts[i].state != THREAD_STATE_ALIVE);". Can you have a look at this problem? Thanks!

Seems relevant to this issue:
#91

**Comment by eboasson** [comment]
There is only a single place where that assert is in the code, fortunately, and it is in shutting down Cyclone. So this assertion should occur when you delete a (the last, if you had multiple) participant — is that right?

Before I start worrying about it, can you check what commit you are using? Commit f27baa71e4f28cac8c085b73ea8e91ddcdff7bd9 from early May addressed the one cause of this assertion that I ever encountered myself, where "delete_participant" is called and Cyclone shuts down before all application threads that have made Cyclone API calls have terminated, and consequently before the clean-up routines have done their work.

What that particular commit does is distinguish between internal threads of Cyclone and application threads, and it only requires that the internal threads have stopped. That was the original intent anyway.

If you already have that commit included in the version you are using, I'll need a little bit more information on what is going on, I'm afraid ...

(I really need to do a new release ...)

**Comment by eboasson** [comment]
@stillsimon I have a suspicion I may have finally had the good fortune — 🤔 — of running into this or one of its compatriots. In my case, an application thread terminating at essentially the same time as a thread tearing down all data structures from Cyclone.

I have done some further mitigating changes in #246 to reduce the likelihood of major trouble, basically by hoping for the best if I leak a little memory on shutdown in such a case, but that thread state management really needs a rework. Looking at it now, I don't quite see why I would not simply let each thread allocate its own memory for its own state, and before freeing it, synchronize with the two other threads that ever look at it (ddsi_threadmon.c and q_gc.c).

Meanwhile, I hope things have improved a bit and that #246 will do a bit more ...

**Comment by eboasson** [comment]
@stillsimon I'm closing this one on the assumption that I indeed caught it and the problem no longer appears.
