### ISSUE TITLE
How to config dds if using VLAN?

### ISSUE THREAD

**Issue by luzizheng** [eclipse-cyclonedds/cyclonedds#2080]
Two devices are connected by vlan, how can I configure dds to allow these two devices to discover?

**Comment by eboasson** [comment]
You probably simply need to configure Cyclone to use the network interface associated with the VLAN. The `CYCLONEDDS_URI` environment variable is used to point to an XML file (or embed the config directly). I expect you need something like:

    <?xml version="1.0" encoding="UTF-8" ?>
    <CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
        <Domain Id="any">
            <General>
                <Interfaces>
                    <NetworkInterface name="eth0.123" />
                </Interfaces>
            </General>
        </Domain>
    </CycloneDDS>

**Comment by eboasson** [comment]
Presumed solved — if not, please reopen.
