### ISSUE TITLE
Questition: what is the ddsi2 participant for ?

### ISSUE THREAD

**Issue by binbowang1987** [eclipse-cyclonedds/cyclonedds#2084]
Does this DDSI2 used for cloud discovery service ?

https://github.com/eclipse-cyclonedds/cyclonedds/blob/4c510fd29d973911fbdda6540257d3153623eb37/src/core/ddsi/src/ddsi__proxy_participant.h#L40-L42

**Comment by eboasson** [comment]
Hi @binbowang1987 that's something from the ancient days, it comes from OpenSplice (https://github.com/ADLINK-IST/opensplice/blob/a4818af5f5931834501055cd7ce2339de4f0af13/src/services/ddsi2e/core/q_entity.h#L557) and dates back to a time PrismTech was shipping a product called Vortex Cloud (it got renamed later to Vortex Link.

That was indeed a rather nice discovery and routing service that would do completely transparent discovery/routing for DDSI. Alas, it is no more. I should remove it from Cyclone ...
