### ISSUE TITLE
Allow colon and period in topic names

### ISSUE THREAD

**Issue by a-zw** [eclipse-cyclonedds/cyclonedds#2089]
Currently, topic names with colons or periods are not allowed.

The binding specified by Autosar requires those because it defines a naming scheme for topics like "ara.com://services/<InterfaceID>/<InstanceId>". See the [AUTOSAR_AP_SWS_CommunicationManagement](https://www.autosar.org/fileadmin/standards/R23-11/AP/AUTOSAR_AP_SWS_CommunicationManagement.pdf) SWS_CM_1101 requirement.

**Comment by a-zw** [comment]
I'm confused about the versions. We use 0.10.4. On the master branch the issue seems already fixed via #1426 ?

**Comment by dpotman** [comment]
The 0.10.x branch was created before the commit in that PR was merged into master, which is why it isn't included in the 0.10.4 release (or any other 0.10.x release). We could backport this commit to 0.10.x, but since we're also working towards the 0.11 release, I'll need to check with @eboasson.

**Comment by eboasson** [comment]
I'm fine with backporting it. There is also #2119 that I think needs backporting, so I suspect there'll even be a 0.10.6 release.

**Comment by a-zw** [comment]
Apparently, b8fed028213882f6466b6b8757bd7eb82a0cd578 fixed this in the releases/0.10.x branch. Thanks @clunietp @eboasson @dpotman !

Referencing #1393.

Is there anything one could do to support a 0.10.6 reelase?
