### ISSUE TITLE
Inclusion of mcpp as preprocessor for IDL compiler

### ISSUE THREAD

**Issue by k0ekk0ek** [eclipse-cyclonedds/cyclonedds#210]
Hi @eboasson.

I would like to request the inclusion of [mcpp](http://mcpp.sourceforge.net/), so that I can create an initial version of the IDL compiler based on the work by @FransFaase in the xtypes branch. While the compiler will not be feature complete enough to replace the Java compiler initially, I hope that I can get it in a good enough state that it can be used to build Eclipse Cyclone DDS. 

This has a couple advantages:
1. Faster builds. Retrieval of Java dependencies by Maven accounts for a significant portion of the time it takes to build the product.
2. Less build failures. Retrieval of Java dependencies by Maven often causes builds to fail.
3. Less complicated builds. Java is not officially supported on the Travis CI Windows build environment. While that problem has been solved by using a version of OpenJDK that ships with the Android SDK, it would be great if we don't depend on a hack anymore to build on Windows. Apart from that we can also eliminate installing Maven using Chocolatey in that environment. Which should also shave some time of the builds.
4. Dogfooding the new IDL compiler shows that we're committed to new compiler and hopefully leads to bug reports or even contributions from the community.

A while back (last year already), I proposed mcpp, a c99 standards compliant preprocessor, to serve as the preprocessor for the IDL compiler. At the time I consulted the iot-pmc mailing list if inclusion was allowed wrt intellectual property and licensing, as can be read in this [thread](https://www.eclipse.org/lists/iot-pmc/msg05106.html).

Normally I would opt to add the upstream project as a dependency, but since there has not been much activity (including bug fixes) due to lack of time from the author(s), I think it's best we maintain a fork dedicated for Eclipse Cyclone DDS.

I've started work on a CMake based build system, so that it integrates nicely with the Eclipse Cyclone DDS build system.

I propose mcpp is maintained in a separate repository (`eclipse-cyclonedds/mcpp` seems like a good place) and that the cyclonedds repository adds it as a submodule.

Please let me know if you have questions/reservations, would like more information, there's anything I can do to help create the repository or speed things up. Thanks in advance.

**Comment by k0ekk0ek** [comment]
Well I've created an initial version of the build system on my [mcpp repository](https://github.com/k0ekk0ek/mcpp/tree/cmake). There's a "nice" trick to reliable determine the target cpu architecture in there and it seems to build something. There's at least a couple of warnings that we need to fix and I know some distributions keep a set of patches as well.

Was hoping to get a little discussion going on whether or not this is the desired approach...

**Comment by eboasson** [comment]
I'm not sure whether there will be much on discussion on this topic, the approach you outline is sensible, use of the mcpp has been approved (CQ18134), and so the remaining detail is whether or not it should be a separate repository and a submodule.

As mcpp is rather small and further updates from the original repository certainly appear highly unlikely (and it certainly looked that way to me last time I looked at it), I wonder if it wouldn't be more practical to just embed it in the Cyclone repository.

**Comment by k0ekk0ek** [comment]
Well, this is exactly the type of reaction I was looking for, so thank you for that. Of course, we both knew that mcpp has been approved, but giving everybody a chance to pitch in seemed like the right thing to do.

With dependencies like this the monorepo vs polyrepo discussion is inevitable. It's true that mcpp:

1. isn't a big project in terms of loc,
2. updates or new release in upstream are unlikely,
3. and the integration will more-or-less be the same.

There's no real technical benefit with keeping it in a separate repo. However, I still lean towards maintaining it in a separate one for the following reasons:

1. While it's a fork dedicated for use within Eclipse Cyclone DDS, there's no reason why people cannot use it for something else. The fact that it's in a repo within the Eclipse Foundation alone might be beneficial to others and, in turn, we may benefit from contributions/fixes that come in.

2. mcpp ships with tests to verify it's fully compliant. There's no benefit in running those tests for every commit that comes into Eclipse Cyclone DDS, but it would be good to run them for changes to mcpp. A separate Travis CI environment makes that a little easier.

3. Should the official upstream project come back to life, unlikely but still. I would be in favour of switching Eclipse Cyclone DDS back to that. We could even go as far as pulling in mcpp through Conan so that it's really just a dependency. Remember, we're only forking because even fixes are not getting into upstream.

4. We could have separate permissions for the mcpp repository if needed.

5. And lastly, mcpp doesn't use the ddsrt module which could be considered a bit weird if it would reside in the Eclipse Cyclone DDS repository.

**Comment by k0ekk0ek** [comment]
After having thought this through a bit more, I think I opt to just have mcpp included in the repository for now as I don't want to maintain yet another project. We can always change it if necessary.

The current plan is to include it in a pull request to the xtypes branch once I have a first "working" version of idlc. Working meaning: it preprocesses an idl file and can feed it to the flex/bison IDL parser by @FransFaase. As it turns out, it's a little more difficult than initially anticipated as there's (I think) no such thing as a push-based lexer, simply because mcpp outputs a stream, not tokens, like flex. While keeping everything in memory might be fine for small data models, I know from experience that there might be users who have very complex data models, so I'm currently looking into using a sliding buffer to keep memory usage to a minimum. Since IDL is mostly C-like (correct me if I'm wrong), it is (almost) as simple as watching whitespace and calling `yylex` on transitions. I'm planning on using mcpp as a library, so that I can register output functions to differentiate between "standard" output, error output and debug output.

If other contributors have suggestions/pointers, please share them if you think I'm overlooking something or just want to contribute.

**Comment by FransFaase** [comment]
Assuming that there is a way to let flex call multiple times (by calling yylex ??), you could replace mcpp_fputs and mcpp_fputc with your own implementation. mcpp_fputs is called from the function put_a_line in main.c, which (for some compilers) is called by devide_line and putout. The function devide_line splits a line in segments not bigger than NWORK, which is defined being equal to 0x1000. (I have no idea if it would be possible to give this a smaller value.)
It seems that mcpp_fputc is only called in a limited number of places (in support.c only if keep_comments is true).

**Comment by k0ekk0ek** [comment]
@FransFaase, I noticed the `mcpp_fputs` function and friends and indeed intend to use those. The problem in this case though is not the line length, it's knowing when to refill the buffer. The print function does not have knowledge about where a token will start or end and does not know if a token has been written or partially written or if it's currently receiving "tokens" located within a comment. The challenge is therefore to keep enough state to know what can be discarded and what not. I whipped up a [prototype](https://github.com/k0ekk0ek/push-lexer) that basically does line buffering and makes sure that it never shrinks past the second-to-last line and does not shrink if the lexer expects more input, i.e. `yymore` was called.

The plan now is to migrate this code back into Eclipse Cyclone DDS (*xtypes* branch) together with mcpp and modify the IDL compiler that you started on.

If you can find the time, please have a look and tell me what you think.

**Comment by FransFaase** [comment]
@k0ekk0ek , I will have a look at it.

**Comment by FransFaase** [comment]
I understand that the program is to test a method to combine yylex with a sliding buffer. The main function is idl_putn, which when the buffer is too small to hold the extra data and does contain a newline, keeps calling yylex until all (old) data is processed up and including the last newline in the old data. (Then, if yy_more_flag is != 1, data covering the token is removed and the old data is shift to the front.) If, after this, the buffer is still too small to hold the extra data, the buffer is enlarged to contain the (remaining) old and new data.
I have ran the program and make some tweaks to it to verify that it works as presented and that the buffer does not grow arbitrary large. It seems it does not grow much larger than the longest line or longest 'token' stored in yytext (such as the multi-line comment). (It took me some time to understand why multi-line comments are processed correctly: the use of yymore() and the check on yy_more_flag.)

However, I do not understand why you do not start the loop in which yylex is called as soon as the sliding buffer contains a newline. Why wait until it is too full? Is that only to reduce the number of times you have to 'slide' the data with memmove?

Probably not the kind of comments you were asking for, but I got some warning when compiling with GNU C al in idl.l.
On line 139 and 262: '%d' maybe needs to be changed in '%u'.
On line 226: implicit declaration of function ‘vasprintf’
On line 333: I guess ", str" should be added.

**Comment by k0ekk0ek** [comment]
Wow! I didn't expect you'd look at this fast. The answer to "why I don't run it every time?" is actually pretty simple: performance. I know it's probably not that big of a deal, but I want to do as little memory operations as possible. The idea is to allocate in chunks (the CHUNK define should normally be something like 1024 bytes or something) and work in batches. Normally I wouldn't expect the buffer to grow (much) beyond the initial size.

I know it's not perfect (yet) :wink:, but thanks for pointing the additional errors out. I mainly focussed on how it's put together for now, but all help is greatly appreciated.

**Comment by eboasson** [comment]
@k0ekk0ek as ``mcpp`` has been added since, I'm closing this issue.
