### ISSUE TITLE
Intermittent ddsrt_select_timeout failure on macos

### ISSUE THREAD

**Issue by martinbremmer** [eclipse-cyclonedds/cyclonedds#212]
I noticed that ddsrt_select_timeout fails sometimes on macos on Travis. I can't remember seeing it on another platform.
I tried reproducing it locally (ubuntu 16.04), but was unable to.

**Comment by k0ekk0ek** [comment]
Hi @martinbremmer. Saw the same failure on macOS some days ago. I don't currently have a macOS machine at my disposal (I seem to recall the ADLINK office has one of those nice little Mac minis though :wink:), but I'll try to find out what causes the test to fail. Thanks for the report!

**Comment by martinbremmer** [comment]
@k0ekk0ek, ah yes. I forgot about that macmini.

I've cloned today's master onto it and ran the ddsrt_select_timeout test 5101 times. It didn't fail once.

(rhetorical) Is it a timing issue on Travis or has it magically been fixed in one of the latest commits? I don't know. So, I've tried the master of about 1 month old (aa2715f4fe2e6bebfab9936ec5d369a4becd74d4) and ran the test a thousand times. Again, no failure.

**Comment by eboasson** [comment]
I strongly suspect it to be a timeout that's set just a little bit too short — the intermittent failures started some time ago without any change to the code, and besides I never have any problem locally on my laptop, &c. — but I haven't spent the time needed to prove that it must be either that or a bug in macOS ...

**Comment by eboasson** [comment]
I haven't seen this particular failure anymore after my tweaking the timeout a bit. Given the observed failure frequency, I am quite sure I would have seen it at some point given the pretty large numbers of builds done since. Therefore, I think it can safely be considered "fixed".
