### ISSUE TITLE
[Help] HelloWorldData.idl not executing in Visual Studio 2022

### ISSUE THREAD

**Issue by avelin0** [eclipse-cyclonedds/cyclonedds#2128]
Hello! I'm trying to run this Hello World example in C from [CycloneDDS on GitHub](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/examples/helloworld/publisher.c). However, Visual Studio is not recognizing the HelloWorldData.idl file, even though I have imported it. The dds.h file imports correctly via vcpkg, so there are no issues there. Could someone guide me on how to properly import the IDL file and resolve this issue to run the code successfully? Thank you in advance!
Also, Can i put .idl file inside c code instead of a separated .idl file?

![image](https://github.com/user-attachments/assets/8f59211f-06d3-4afe-bfe6-4c9f04df8c45)

**Comment by aratar-orome** [comment]
Did you try to build it from command line with

`cmake -Bbuild
cmake --build build`

The only problem I can see is that HelloWorldData.h is missing which is obviously generated using the idl file.

**Comment by avelin0** [comment]
I understand now that helloworld.h generates helloworlddata.idl, which I wasn’t aware of before.

Currently, I'm not using CMake—just Visual Studio with vcpkg. Is it possible to:

    Compile the code using only Visual Studio and vcpkg, without CMake, while incorporating this IDL?
    Integrate the IDL directly within the C++ code?

Thank you in advance!

**Comment by aratar-orome** [comment]
Sorry, I have no idea how to use vcpkg in combination with CMake. But you can generate the idl file by your own. Here you find an explanation:

https://cyclonedds.io/docs/cyclonedds/latest/getting_started/helloworld/helloworld_idl.html

**Comment by avelin0** [comment]
I will try. Thankx @aratar-orome
