### ISSUE TITLE
dds_instance_get_key() returns  DDS_RETCODE_ILLEGAL_OPERATION when applied on readconditions or queryconditions

### ISSUE THREAD

**Issue by TheFixer** [eclipse-cyclonedds/cyclonedds#213]
Hi,

I have been playing around with Cyclone a bit and stumbled on the following. 

One of the nice things is that dds_read() and dds_take() can be applied to a readcondition or querycondition. For example, you can write something like
`
samplecount = dds_read (rc, samples, info, MAX_SAMPLES, MAX_SAMPLES);
`
where rc is readcondition. If there is data matching the condition specified in the readcondition, then this data will be returned in the samples list, and info list contains the sampleinfo of the data that is retrieved. For example, the handle tto the instance of the the j-th sample can be retrieved as
info[j].instance_handle.

To get the key of the handle you can use dds_instance_get_key(), but unfortunately this function requires a reader. I could add extra code to retrieve the reader, but this is a bit silly since I have the readcondition, and a readcondition is already tied to the reader.  I therefore would have expect that I could do somehting like
`
ret = dds_instance_get_key(rc, ...)
`
but this returns DDS_RETCODE_ILLEGAL_OPERATION.

Although this is not a bug, I believe it is more convenient and user friendly to allow dds_instance_get_key() to use a readcondition instead of requiring the reader. It is safe to do this because a readcondition is tied to a single reader anyway. The same holds for querycondition.

Allowing this would make the usage of dds_instance_get_key() a bit more user friendly in the context of readcondition and querycondition, and would lead to slightly less application code. 

In an attempt to see whether this indeed works I slightly changed the code and managed to get this working with very limited effort. As I did the code change already I am preparing a pull request, so you can decide yourself whether or not this is a useful contribution.

**Comment by eboasson** [comment]
Implemented by #214
