### ISSUE TITLE
Is there a way to record and replay cyclonedds?

### ISSUE THREAD

**Issue by gaochengGG** [eclipse-cyclonedds/cyclonedds#2135]
I want to record the published data when using cyclonedds, and then store it in some way, so that I can replay the data when needed. Does cyclonedds provide tools to do this? If not, can you give me some pointers? I want to develop this tool. What I think may be stuck in my points. Does cyclonedds provide tools like "topic list" to let me know the node information? What format and how to store the data after I create a subscription to publish the message, and how to read the data for replay?

**Comment by gaochengGG** [comment]
> There is not currently a recorder, but it can be made fairly easily, especially in Python. Indeed, it would be a nice extension for the python command-line tool (see https://github.com/eclipse-cyclonedds/cyclonedds-python). It can also be done fairly easily in C, all the basic primitives exist.
> 
> You might want to look at the discussion in #2099, that contains some suggestions for reading/writing any topic, and getting the CDR in/out without even bothering with the types. The scenario there is different, but those would also be the basic operations for you, I think.
> 
> The type of the data can also be obtained, and then you can write the CDR representation and the type definitions. That way you have a self-contained recording. If you want the types, you might also want to have a look at https://github.com/eclipse-cyclonedds/cyclonedds/tree/master/examples/listtopics and https://github.com/eclipse-cyclonedds/cyclonedds/tree/master/examples/dynsub.

still have some questions I hope to get your advice. As for how to store the received data, I investigated cyberrt reord and ros2 bag record. Cyberrt uses a custom data structure to store data, and ros2 uses sqlite3 to store data. What facility do you suggest I use to store cyclonedds data?

**Comment by eboasson** [comment]
> What facility do you suggest I use to store cyclonedds data?

I don't think there is a single answer to that question, other than "it depends". Some of the things it depends on are:
* is disk space overhead an issue?
* is performance during recording an issue?
* do you want to replay small fractions of a recording?
* do you want to analyze a recording by querying it?

If you need the least overhead in recording possible and don't mind having to scan it from beginning to end, then simply file to which you keep appending is probably a sensible choice. (It's also what Wireshark does when recording packets from the network.)

If you want to select a small subset, and you to change the subset, it might be useful to have an index. sqlite3 will happily store a lot of data while maintaining an index. There is also something to be said a time series database ...

I have used sqlite3 occasionally, and it would probably be a sensible choice. You probably already know *what* you will be storing — something like a mapping of writer id -> topic, type, QoS and list of samples ordered on time by writer id, data. (Maybe you'd like some redundant info like topic names, or you'd rather leave the writer id out and just use topic/partition, there many sensible ways.) If you want to play it safe, you might want to do a minimal abstraction from a storage layer that provides a function for each type of record to store. Then you can start with sqlite3 but you're tied to it.

**Comment by gaochengGG** [comment]
thanks a lot，I will try as you suggest. @eboasson

**Comment by eboasson** [comment]
> Hi, is there any updates on this or forks that implement recording and replay?

Perhaps #2311 ? (I haven't had a chance to review it yet)
