### ISSUE TITLE
debian package or binary installer

### ISSUE THREAD

**Issue by cwyark** [eclipse-cyclonedds/cyclonedds#234]
@eboasson Do you plan to release cyclonedds into debian package or binary (tar file) ? ros2 rmw_cyclonedds users can easily get cyclonedds without compile it by themself. If you think debian package will be better, I can help on the .deb metadata.

**Comment by eboasson** [comment]
I would like such a package to be available, but it'll be a while before that happens if I have to do it. Any contributions for this would be very welcome.

**Comment by thijsmie** [comment]
There is a [debian package available](https://tracker.debian.org/pkg/cyclonedds).
