### ISSUE TITLE
Ignoring dds_fatal() and DDS_[IC]LOG(DDS_LC_FATAL) processing and a few other things

### ISSUE THREAD

**Issue by i-and** [eclipse-cyclonedds/cyclonedds#270]
1. There is no emergency exit of the application when calling DDS_FATAL(). 
The situation is the same with DDS_CLOG(DDS_LC_FATAL), provided that the 
Tracing/Verbosity parameter takes the default value (gv.config.tracemask=0). 
Apparently this is due to the fact that the log file.c by default, only 
DDS_LC_ERROR | DDS_LC_WARNING events are allowed globally:
~~~
static struct ddsrt_log_cfg_impl logconfig = {
  .c = {
    .mask = DDS_LC_ERROR | DDS_LC_WARNING,
    .tracemask = 0,
    .domid = UINT32_MAX
  },
  .sink_fps = {
    [LOG] = NULL,
    [TRACE] = NULL
  }
};
~~~

As a solution, I suggest adding the value DDS_LC_FATAL to the 'mask' initialization.

2. File ddsi_iid.c: 
~~~
void ddsi_iid_init (void)
{
  union { uint64_t u64; uint32_t u32[2]; } tmp;

#if ! DDSRT_ATOMIC64_SUPPORT
  ddsrt_mutex_init (&dds_iid.lock);
#endif

  for (size_t i = 0; i < sizeof (dds_iid.key) / sizeof (dds_iid.key[0]); i++)
    dds_iid.key[0] = ddsrt_random ();
...
~~~

2.1 Is there incomplete key(dds_iid.key[]) initialization with random values above?
2.2 Taking into account the fact that ddsrt includes emulation of 64-bit operations, 
it would be logical to exclude the use of DDSRT_ATOMIC64_SUPPORT (there are also q_entity.h, ddsi_uud.h).

3. In file attributes.h:
~~~
#if __clang__
# define ddsrt_gnuc (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)
#else
# define ddsrt_gnuc (0)
#endif

#if __GNUC__
# define ddsrt_clang (__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__)
#else
# define ddsrt_clang (0)
#endif
~~~

Perhaps '#if \__GNUC__' and '#if \__clang__' need to be swapped.

**Comment by eboasson** [comment]
Thanks @i-and !

> 1. There is no emergency exit of the application when calling DDS_FATAL().
>    The situation is the same with DDS_CLOG(DDS_LC_FATAL), provided that the
>    Tracing/Verbosity parameter takes the default value (gv.config.tracemask=0).
>    Apparently this is due to the fact that the log file.c by default, only
>    DDS_LC_ERROR | DDS_LC_WARNING events are allowed globally:
> [...]
> As a solution, I suggest adding the value DDS_LC_FATAL to the 'mask' initialization.

You are totally correct — thank you for catching that, one suspects it could've gone undetected for much longer ...

> [...]
> ```
>   for (size_t i = 0; i < sizeof (dds_iid.key) / sizeof (dds_iid.key[0]); i++)
>     dds_iid.key[0] = ddsrt_random ();
> ```
> 
> 2.1 Is there incomplete key(dds_iid.key[]) initialization with random values above?

Yes, there is. The other elements remain 0 this way, and that's not the intent. Fortunately it is quite benign in that the instance ids are meaningless and they are still pretty likely to be different sequences from run to run (which is of interest to make it harder to "game" the hash function).

> 2.2 Taking into account the fact that ddsrt includes emulation of 64-bit operations,
> it would be logical to exclude the use of DDSRT_ATOMIC64_SUPPORT (there are also q_entity.h, ddsi_uud.h).

It would be, yes.

> 3. In file attributes.h:
> 
> ```
> #if __clang__
> # define ddsrt_gnuc (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)
> ```
> [...]
> 
> Perhaps '#if __GNUC__' and '#if __clang__' need to be swapped.

It certainly looks like that to me, too. Modern gcc and clang (for some value of "modern") both define ``__has_attribute``, so I reckon the consequences will have been minor up to now.

While I think I can simply go with your suggestions for fixing these problems, I'll have another look at a better time of day before changing anything.

**Comment by i-and** [comment]
@eboasson, thanks for the quick response,
I continue to look closely at the code and here is what else is seen at the moment:

3. file "retcode.c". 
~~~
const char *dds_strretcode (dds_return_t rc)
{
...
else if (rc >= (-DDS_XRETCODE_BASE) && rc < (-DDS_XRETCODE_BASE) + nxretcodes)
    return xretcodes[rc - (-DDS_XRETCODE_BASE)];
...
~~~
In the expression it is not quite correct to use DDS_XRETCODE_BASE as the initial offset 
since the first error code starts with (DDS_XRETCODE_BASE - (1))

4.  File hopscotch.c
~~~
static void *ddsrt_hh_lookup_internal (const struct ddsrt_hh *rt, const uint32_t bucket, const void *template)
{
  const uint32_t idxmask = rt->size - 1;
  uint32_t hopinfo = rt->buckets[bucket].hopinfo;
  uint32_t idx;
  for (idx = 0; hopinfo != 0; hopinfo >>= 1, idx++) {
    const uint32_t bidx = (bucket + idx) & idxmask;
    void *data = rt->buckets[bidx].data;
    if (data && rt->equals (data, template))
      return data;
  }
  return NULL;
}
~~~

I propose to optimize the cycle time by executing the body function according to the condition "if (hopinfo & 1) {"

5. Is there a parameter in the configuration file similar to "Tracing/Verbosity",  but applied to the global log (logconfig)? Its default value should be "DDS_LC_ERROR | DDS_LC_WARNING | DDS_LC_FATAL". During system initialization, the "dds_set_log_mask(new_param)" function must be called.

**Comment by eboasson** [comment]
> @eboasson, thanks for the quick response,
> I continue to look closely at the code and here is what else is seen at the moment:

Thank you very much for making that effort!

> [...] ``dds_strretcode`` [...]
> In the expression it is not quite correct to use DDS_XRETCODE_BASE as the initial offset since the first error code starts with (DDS_XRETCODE_BASE - (1))

Indeed. PR extended with a fix + test added just in case.

> File hopscotch.c
> ```C
> static void *ddsrt_hh_lookup_internal (const struct ddsrt_hh *rt, const uint32_t bucket, const void *template)
> [...]
> for (idx = 0; hopinfo != 0; hopinfo >>= 1, idx++) {
>    const uint32_t bidx = (bucket + idx) & idxmask;
> ```
> I propose to optimize the cycle time by executing the body function according to:
> ```C
> for (idx = 0; hopinfo != 0; hopinfo >>= 1, idx++) {
>    if (hopinfo & 1) {
>      const uint32_t bidx = (bucket + idx) & idxmask;
> ```

An interesting suggestion. I can't think of a reason why it can't be done like that and one would think it'd be a little faster on average, especially because you'd avoid testing buckets that are "squatted on" by a different home bucket.

> Is there a parameter in the configuration file similar to "Tracing/Verbosity", but applied to the global log (logconfig)? Its default value should be "DDS_LC_ERROR | DDS_LC_WARNING | DDS_LC_FATAL". During system initialization, the "dds_set_log_mask(new_param)" function must be called.

If I understand your question correctly, then the answer is no, there is not (currently) such a parameter. You're not missing out on much, because the vast majority of them are errors and warnings anyway and you can intentionally do this from the application prior to initialising the library. (You can even provide your own handlers for messages via ``dds_set_log_sink`` and ``dds_set_trace_sink``.)

It is also not self-evident how exactly that would work: should it read an additional configuration file? Should these be child elements of the ``CycloneDDS`` root element (that seems reasonable), but then, what if a different domain is created with a different setting?

**Comment by i-and** [comment]
> Indeed. PR extended with a fix + test added just in case.

Thanks.

> An interesting suggestion. I can't think of a reason why it can't be done like that and one would think it'd be a little faster on average, especially because you'd avoid testing buckets that are "squatted on" by a different home bucket.

Yes, it is true. The main motivation is not to make unnecessary calls to the comparison function of the current element and the desired one.

> (You can even provide your own handlers for messages via dds_set_log_sink and dds_set_trace_sink.)

In some usage scenarios, it may be useful to enable log / trace without recompiling the application.

> It is also not self-evident how exactly that would work: should it read an additional configuration file? Should these be child elements of the CycloneDDS root element (that seems reasonable), but then, what if a different domain is created with a different setting?

.If we assume that the dds_set_log_mask(new_param) call controls global logging settings: logging (and possibly tracing) of DDS_LC_ERROR | DDS_LC_WARNING | DDS_LC_INFO events for all created domains and for general **logconfig**, as well as tracing of global **logconfig**, then it would be logical not to bind this parameter to a specific domain (make it common to all created domains).

**Comment by i-and** [comment]
File xmlparser.c
~~~ C
static int make_chars_available (struct ddsrt_xmlp_state *st, size_t nmin)
{
...
if (st->cbufp + st->cbufmax < nmin) {
            st->cbufmax = st->cbufp + nmin;
            st->cbuf = ddsrt_realloc (st->cbuf, st->cbufmax);
        }
...
}
~~~
Apparently an incorrect condition that leads to non-allocation of memory (for this, the initial buffer size must be less than the size of the readable XML file). It seems to me that the condition is better rewritten as:
~~~ C
 if (st->cbufmax < nmin + st->cbufp) {
...
        }
~~~

**Comment by eboasson** [comment]
Thank you very much, @i-and!

I have applied your suggestions, only swapping the terms in ``nmin + st->cbufp`` because I liked it better given the line below.

Building a test suite for this parser is a bit out of scope at the moment, but a bit of testing beyond the handful of trivial inputs it gets from configurations used in the tests is clearly needed. So I figured it is as good a time as any to play with [American Fuzzy Lop](https://github.com/google/AFL) for a bit 😁. It turns out that as the input buffer was as a plain ``char``, some values in the input would get mapped to special tokens. For example, ``\376`` — a.k.a. 254 — would sometimes be considered an opening tag. These misinterpretations also caused hangs and crashes. So now the buffer is unsigned.

**Comment by i-and** [comment]
In order to avoid duplication of search paths and H-files, I propose to modify the src/ddsrt/CMakeLists.txt as follows (added lines in bold):
...
 if(HAVE_${feature_uc})
      # Code that is more-or-less the same for all targets can placed in
      # src/<feature>.c. An example would be ddsrt_freeifaddrs.
      if(EXISTS "${source_path}/${feature}.c")
        list(APPEND sources "${source_path}/${feature}.c")
      endif()
      set(system_exists FALSE)
      **set(include_exists FALSE)**
      # Allow custom implementations for a feature. e.g. lwip as opposed to
      # windows or posix.
      set(_system_name "${system_name}")
      if(NOT HAVE_${feature_uc} MATCHES "[tT][rR][uU][eE]")
        set(_system_name "${HAVE_${feature_uc}}")
      endif()
      foreach(system ${_system_name} posix)
        # Headers that must remain private but are required by other runtime
        # source files must be located in src/<feature>/dds/ddsrt.
          **if(IS_DIRECTORY "${source_path}/${feature}/include" AND NOT include_exists)**
          file(GLOB_RECURSE
                 files
               CONFIGURE_DEPENDS
                 "${source_path}/${feature}/include/*.h")
          list(APPEND headers ${files})
          target_include_directories(
            ddsrt INTERFACE
              "$<BUILD_INTERFACE:${source_path}/${feature}/include/>")
          **set(include_exists TRUE)**
        endif()
...

**Comment by eboasson** [comment]
@i-and it appears that CMake is friendly enough to not have the duplicates in the include paths passed to the compiler, but it is certainly less than elegant that the system-independent paths are gone over multiple times.

As they are processed at least once (because of the "posix") case in the ``foreach``, it makes more sense to me to move that part out of the loop.

**Comment by i-and** [comment]
@eboasson, thank you, all my suggestions are taken into account in the master branch. The only thing left is a question related to adding a new configuration parameter for later calling dds_set_log_mask (new_param). What do you think about it?

**Comment by eboasson** [comment]
@i-and you'll get your setting 😀

I need to work on my pile of pull requests first though ... reviewing is terribly time-consuming, as I'm sure you know. (You're welcome to add to the pile, if you wish! 😁)

**Comment by thijsmie** [comment]
There was a lot of discussion on this ticket up until 2 years ago, but as far as I can tell all relevant suggested code changes are considered and relevant PR's merged so I will close this. @i-and if there are any remaining tidbits please split them out into multiple issues that are more "stand-alone" if you will, that will make my "can-this-issue-be-closed-now?" job easier in the future 😄.
