### ISSUE TITLE
Many partial CMakeLists files

### ISSUE THREAD

**Issue by rotu** [eclipse-cyclonedds/cyclonedds#277]
There are a bunch of files in the cmake tree that are called CMakeLists.txt but don't build independently.

If a CMakeLists.txt should build independently, it should have a project() declaration at the top.

A CMake file that should not build independently belongs in a cmake module (suffixed with `.cmake` and imported with `include(foo.cmake)`), not a CMakeLists.txt.

**Comment by thijsmie** [comment]
While you are maybe technically correct on that, as the [add_subdirectory](https://cmake.org/cmake/help/latest/command/add_subdirectory.html) documentation indeed suggests that, I don't know of a single project that strictly adheres to this definition. I definitely don't agree with the second form: cmake modules are for external functionality and make dealing with paths a headache, and the way we are using the `CMakeLists.txt` files is also hinted at in the same docs: "*Note that inter-target dependencies supersede this exclusion.*".
