### ISSUE TITLE
xml files don't validate

### ISSUE THREAD

**Issue by rotu** [eclipse-cyclonedds/cyclonedds#283]
In doing #282, I realized that the xml files in the repo don't validate against the cyclonedds schema.

Either the schema or the xml files should be fixed.

**Comment by eboasson** [comment]
I'd say the XML files should be fixed. If I am not mistaken the only problems are options that have been moved, so that should be easy.

**Comment by eboasson** [comment]
Closed via #326 — ``config_simple_udp.xml`` still doesn't validate, but that is because of its reliance on environment variable expansion.
