### ISSUE TITLE
Documentation of 'Building Cyclone DDS' incomplete

### ISSUE THREAD

**Issue by TheFixer** [eclipse-cyclonedds/cyclonedds#30]
Hi,

I tried to install CycloneDDS on a clean Kubuntu 18.04 LTS and bumped into a few issues when following the steps in section ' Building Cyclone DDS'  (see https://github.com/eclipse/cyclonedds) along the way. I thought it might benefit the project to let you know about these issues so the documentation can be improved.

The issues I bumped into are:

1. The prerequisites are incomplete. Besides cmake, java and maven you also need  git and g++ which are not present on a clean install. They can simply be installed using sudo apt-get install
2. OpenJDK is by default installed on Ubuntu, but this causes problems. It seems better to use oracle-java, but this is not clear from the instructions. I followed https://www.linuxuprising.com/2018/10/how-to-install-oracle-java-11-in-ubuntu.html
3. When I tried to ' make'  the stuff in the build directory I ran into the following issue
`Scanning dependencies of target idlc
[  0%] Building JAR file /home/lex/Repositories/cyclone/cyclonedds/build/idlc/target/idlc-jar-with-dependencies.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ERROR] Plugin org.antlr:antlr4-maven-plugin:4.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.antlr:antlr4-maven-plugin:jar:4.5: Could not transfer artifact org.antlr:antlr4-maven-plugin:pom:4.5 from/to central (https://repo.maven.apache.org/maven2): Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
idlc/CMakeFiles/idlc.dir/build.make:183: recipe for target 'idlc/target/idlc-jar-with-dependencies.jar' failed
make[2]: *** [idlc/target/idlc-jar-with-dependencies.jar] Error 1
CMakeFiles/Makefile2:85: recipe for target 'idlc/CMakeFiles/idlc.dir/all' failed
make[1]: *** [idlc/CMakeFiles/idlc.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2`
This is a known problem (see https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty). Reinstalling ca-certificates-java worked for me
`$ sudo dpkg --purge --force-depends ca-certificates-java`
`$ sudo apt-get install ca-certificates-java`
4. The command `make install` gave permission errors. Changing it to `sudo make install` (assuming the user has sudo priviliges) works.

With these changes I was able to build and install.

**Comment by k0ekk0ek** [comment]
1. That's a bug that we'll need to resolve. Adding the LANGUAGES option to CMake's project command ensures CMake doesn't check for C++ support, but leads to problems when checking for compiler options in the os directory. Thanks for reporting the issue.
2. Runs find on OpenJDK on my machine. Any chance you can provide CMake's output?
3. At first glance this seems to be an issue with you Java installation, not so much with Cyclone, but I'll try on a freshly installed Kubuntu 18.04 machine.
4. Don't use `make install` unless you want to install the headers and libraries on you machine. As Cyclone isn't stable, that might not be what you want. Using ~/.local might be a good alternative, or simply point the compiler/linker towards your Cyclone build directory for now. That being said, this is not actually an issue with Cyclone. Copying files to /usr/lib etc will always require root privileges. If you simply want to run examples, building the project is enough. Just use `cmake --build .` in the build directory and run the examples from there.

**Comment by k0ekk0ek** [comment]
1. For know we'll have to leave the dependency on C++. If only C is enabled you'll run into the following bug: https://gitlab.kitware.com/cmake/cmake/issues/16967. We'll make sure to mention it in the README.md.

**Comment by TheFixer** [comment]
@k0ekk0ek As far as 1-3 is concerned that's fine with me. I'll recheck 2. As far as 4 is concerned I do think it is a bit inconsistent that the README.md (https://github.com/eclipse/cyclonedds/blob/master/README.md) recommends to use `make install` despite the current version being unstable. Wouldn't it be better to recommend to use `cmake --build` in the README.md as long it is unstable?
