### ISSUE TITLE
dds_create_domain() does not return an entity

### ISSUE THREAD

**Issue by martinbremmer** [eclipse-cyclonedds/cyclonedds#300]
The dds_create_domain() returns a return code instead of an entity. The result is that an domain entity was created that can not be deleted by the application*.

A side effect of this is that manually running cunit_ddsc test application does not work anymore. Rogue domains keep existing and interfering in various tests.
Running through ctest doesn't have this issue, because every test runs in its own process.

@eboasson, can you assign me to this issue please?

Note, see also https://github.com/eclipse-cyclonedds/cyclonedds/pull/268#discussion_r333608411

\* It can be deleted by calling dds_get_parent() on a related participant and delete the returned entity.

**Comment by eboasson** [comment]
@martinbremmer I had become sufficiently annoyed by to try and figure out what would be a sane way of dealing with things, and trying to capture that in working code. I've created #302 for your (or anyone's, for that matter) perusal. Feel free to shoot that down, use it, or whatever.

**Comment by eboasson** [comment]
Closed via #319. Thanks @martinbremmer for helping resolve this.
