### ISSUE TITLE
Missing 0.5.0 release?

### ISSUE THREAD

**Issue by hansfn** [eclipse-cyclonedds/cyclonedds#320]
Reading the project page at https://projects.eclipse.org/projects/iot.cyclonedds I notice there is a 0.5.0 (Eusebius) release. Both the 0.5.0 tag and release is missing here on GitHub.

**Comment by eboasson** [comment]
@hansfn I had started the paperwork but I am afraid too many papers ended up on top of it and it got lost. Please accept my apologies.

I have updated the release date with a new ETA — in December this time, to allow for getting approval for releasing from the Eclipse foundation.

**Comment by hansfn** [comment]
No problem at all. I was just confused.
