### ISSUE TITLE
Install (CMake) config files in correct location

### ISSUE THREAD

**Issue by hansfn** [eclipse-cyclonedds/cyclonedds#321]
On our IPCs and Linux (Gentoo) PCs we build many libraries for both 32- and 64-bit since we have old 32-bit applications that needs 32-bit libraries. The problem is that when you install both 32 and 64 bit the CMake config files will be overwritten. 

Currently the CMake config files are installed into ${CMAKE_INSTALL_DATADIR}/${PROJECT_NAME}. That is /usr/share/CycloneDDS/ on Gentoo. According to https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure the config files should be not placed under /usr/share Typical location on Linux would be  
/usr/lib32/cmake/CycloneDDS/ and /usr/lib64/cmake/CycloneDDS

See also https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#example-generating-package-files

Sorry about not providing a patch, but you don't set LIB_INSTALL_DIR which I normally use when fixing these issues.

**Comment by eboasson** [comment]
Thanks @hansfn for pointing that out — and no worries about not providing a patch.

CMake and I have a difficult relationship and if I hadn't inherited the CMake files it would probably still be using old-fashioned makefiles … and so I am not too surprised such issues exist.

This sort of thing I have typically solved using ``CMAKE_INSTALL_PREFIX`` but that is arguably rather simplistic (if effective) and always having to set include paths for CMake is also annoying. I'll see if I can figure out how to change this to fit better with the conventions. Or perhaps some kind soul will save me from having to figure it out 🙂

**Comment by hansfn** [comment]
Since your CMake setup is using GNUInstallDirs, the fix was easy enough:

```patch
diff --git a/cmake/Modules/Packaging.cmake b/cmake/Modules/Packaging.cmake
index a635869..bbc59f2 100644
--- a/cmake/Modules/Packaging.cmake
+++ b/cmake/Modules/Packaging.cmake
@@ -18,7 +18,7 @@ include(CMakePackageConfigHelpers)
 include(GNUInstallDirs)
 
 set(PACKAGING_MODULE_DIR "${PROJECT_SOURCE_DIR}/cmake/Modules/Packaging")
-set(CMAKE_INSTALL_CMAKEDIR "${CMAKE_INSTALL_DATADIR}/${PROJECT_NAME}")
+set(CMAKE_INSTALL_CMAKEDIR "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}")
 
 # Generates <Package>Config.cmake.
 configure_package_config_file(
```

I know I should make a pull request and so on, but for thus tiny change this will have to do.

**Comment by eboasson** [comment]
Thanks!

It is quite a big mess if you read the documentation. With the change you propose (one that makes perfect sense to me when I read your description) building the examples now fails when I set ``CMAKE_PREFIX_PATH`` to the value of ``CMAKE_INSTALL_PREFIX``, but with the old one that works.

If I interpret https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure correctly (and assuming it actually searches in the locations listed, which I haven't yet been able to verify — I'll do a bit of system call tracing later) the best paths would be:

```CMake
<prefix>/<name>*/(lib/<arch>|lib*|share)/cmake/<name>*/         (W/U)
<prefix>/<name>*/(lib/<arch>|lib*|share)/<name>*/               (W/U)
<prefix>/<name>*/(lib/<arch>|lib*|share)/<name>*/(cmake|CMake)/ (W/U)
```

because those are the only ones searched on both Unix (presumably including macOS) and Windows. However, that requires knowing what to put in place of ``(lib/<arch>|lib*|share)``. So one just goes from problem to problem.

Perhaps I should go look for some more examples on the web ...

**Comment by hansfn** [comment]
Yes, the documentation is quite unclear. Anyway, I discovered why the examples failed. When we move the config files, we have to mode the idlc component too:

```patch
 diff --git a/src/idlc/CMakeLists.txt b/src/idlc/CMakeLists.txt
index ae210c3..a6b2ea2 100644
--- a/src/idlc/CMakeLists.txt
+++ b/src/idlc/CMakeLists.txt
@@ -45,17 +45,17 @@ include(cmake/IdlcGenerate.cmake)
 
 install(
   FILES "cmake/IdlcGenerate.cmake"
-  DESTINATION "${CMAKE_INSTALL_DATADIR}/${PROJECT_NAME}/idlc"
+  DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}/idlc"
   COMPONENT idlc)
 
 install(
   FILES "${IDLC_SCRIPT_IN}"
-  DESTINATION "${CMAKE_INSTALL_DATADIR}/${PROJECT_NAME}/idlc"
+  DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}/idlc"
   COMPONENT idlc)
 
 install(
   FILES "${IDLC_JAR}"
-  DESTINATION "${CMAKE_INSTALL_DATADIR}/${PROJECT_NAME}/idlc"
+  DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}/idlc"
   PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_WRITE GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
   COMPONENT idlc)
```

After that update the (installed) examples compile again. 

The reason I chose ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME} was that is the most common I have seen, at to me it makes sense to have all the CMake stuff in one folder.

[In the example](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#example-generating-package-files) at the end of the CMakePackageConfigHelpers documentation, you'll notice that they have switched the order ${LIB_INSTALL_DIR}/${PROJECT_NAME}/cmake

**Comment by eboasson** [comment]
Thanks again, @hansfn! I've updated the docs and CI build things to match and merged it.
