### ISSUE TITLE
Support mixed-language processes in Cyclone

### ISSUE THREAD

**Issue by eboasson** [eclipse-cyclonedds/cyclonedds#339]
Data representation is language dependent (or even language-mapping) but only a single ``struct sertopic`` that handles the conversion between serialised form and application representation can be associated with a single topic. Consequently, you can't have a mixed-language program that uses the same topic from two languages that use different mappings (e.g., one combining C with C++).

This is a problem for the ROS1 bridge as well: https://github.com/ros2/rmw_cyclonedds/issues/72

**Comment by dirk-thomas** [comment]
@eboasson Is there any update on this? If not, can you please prioritize this?

**Comment by eboasson** [comment]
Other things have kept me busy lately, but I'll make this my next project.

I noticed ros2/rmw_cyclonedds#87 and it specifically mentions "multiple nodes" and today that means multiple DDS DomainParticipants. That detail does make a number of technical details slightly more. Do you think this would be a reasonable restriction if it turns out to be a useful restriction? (Obviously there is ros2/design#250 which might break that assumption ... I am grudgingly in favour of that one for 100s of nodes in a process, but where I have my doubts that that scale is common.)

**Comment by dirk-thomas** [comment]
> Other things have kept me busy lately, but I'll make this my next project.

Great, thanks.

> I noticed ros2/rmw_cyclonedds#87 and it specifically mentions "multiple nodes"

I don't see where it does?

**Comment by eboasson** [comment]
> I don't see where it does?

Hmm ... I don’t see it either. I must unwittingly have been smoking something rather powerful, it seems 😄 . Anyway, doesn’t matter all that much, it simply has to work.

**Comment by hidmic** [comment]
@eboasson any chance we can get the ball rolling here? This is a necessary fix for https://github.com/ros2/ros1_bridge/pull/233 to land.

**Comment by eboasson** [comment]
@hidmic the ball is rolling properly, with a bit of luck I'll be able to do a pull request this week.

**Comment by eboasson** [comment]
There's not going to a PR today because the Cyclone commits need "some" cleaning up, and furthermore some small enhancements are needed in the RMW layer to handle the slightly extended notion of a sample.

But it does now allow having the same topic with multiple underlying type definitions, converting between them on the fly. For those who don't like vaporware: https://github.com/eboasson/cyclonedds/commits/multiple-sertopic-per-topic

**Comment by dirk-thomas** [comment]
> There's not going to a PR today because the Cyclone commits need "some" cleaning up, and furthermore some small enhancements are needed in the RMW layer to handle the slightly extended notion of a sample.

@eboasson Any update on this?

**Comment by eboasson** [comment]
That would be my fondness (or the absence thereof) of doing the paperwork. https://github.com/eclipse-cyclonedds/cyclonedds/pull/382 got merged (and https://github.com/ros2/rmw_cyclonedds/issues/72 closed because of that), but I forgot to update this one.

**Comment by dirk-thomas** [comment]
> ... but I forgot to close this one.

@eboasson So can you close this ticket then?
