### ISSUE TITLE
Cannot understand what IDL types you support

### ISSUE THREAD

**Issue by olssonsimon** [eclipse-cyclonedds/cyclonedds#350]
This shit is crazy. The documentation does not specify what types you can use. Do you have a link or explanation?

**Comment by eboasson** [comment]
If I didn't feel a bit responsible for your troubles I'd be laughing out loud at your succint summary of the state of the IDL compiler and its documentation 🙂 It supports "most" of the plain data types in traditional IDL: see [CORBA](https://www.omg.org/spec/CORBA/1.0/PDF) section 4.

The short summary:
```C++
module M {
  typedef long U[10]; // array of 10 longs

  struct V {
    boolean a; // boolean
    octet b; // uint8_t
    char c; // char
    short d; // int16_t
    unsigned short e; // uint16_t
    long f; // int32_t
    unsigned long g; // uint32_t
    long long h; // int64_t
    unsigned long long i; // uint64_t
    float j;
    double k;
    string l, n;
  };

  typedef sequence<V> W; // unbounded sequence of V

  // An enumerated type with constants taken from the first line of "Kleine gedigten voor
  // kinderen" by Hieronymus van Alphen (1778, so out of copyright :))
  enum X {
    JANTJE,
    ZAG,
    EENS,
    PRUIMEN,
    HANGEN
  };

  union Y switch (X) {
    case JANTJE:
      W w;
    case ZAG: case EENS:
      string something;
    default:
      long silly;
  };
};

struct Z {
  string key;
  M::Y data;
};

// tell IDLC to generate a topic descriptor
#pragma keylist Z key
```
that should work and give a pretty good coverage of what is supported.

**Comment by eboasson** [comment]
P.S.: We actually really will add support for the full XTypes spec.

**Comment by i-and** [comment]
> P.S.: We actually really will add support for the full XTypes spec.

In this regard, maybe someone will take up the development of XML-schema for CycloneDDS based on https://www.omg.org/spec/DDS-XML.  (https://github.com/eclipse-cyclonedds/cyclonedds/issues/309#issuecomment-551027112) :smiley:   It would also be desirable that the developed scheme took into account the features and extensions of the schemes of existing implementations of DDS (open and commercial). This would allow for compatible XML descriptions and corresponding data models.

**Comment by olssonsimon** [comment]
Thanks for the detailed response guys!
