### ISSUE TITLE
How to handle multiple topics in single application efficiently

### ISSUE THREAD

**Issue by sjames** [eclipse-cyclonedds/cyclonedds#352]
Hi,
I'm a newcomer to DDS and was looking for a C implementation and happily stumbled upon this project.

The examples are trivial and publish only a single topic.  A real-world application will publish many more topics. 

What is the recommended pattern to deal with subscribing to several topics? I won't want to have to poll multiple readers continuously.  Is there a more reactive way of doing this with poll/select?

Thanks and regards,
Soj

**Comment by k0ekk0ek** [comment]
Hi @sjames. Glad you like it so far! :slightly_smiling_face: DDS offer two ways to deal with this. You can use waitsets, which behave like poll/select or you can use listeners, which allow you to use more of an event based way to read the data. The roundtrip example shows how to use either one.

**Comment by sjames** [comment]
Thank you for the quick answer.  I will try out waitsets and listeners.
Cheers!
Sj
