### ISSUE TITLE
An 'optimistic' cast in DDSI

### ISSUE THREAD

**Issue by martinbremmer** [eclipse-cyclonedds/cyclonedds#359]
In the function nn_xmsg_addpar_keyhash(), ```ddsi_serdata``` is cast to ```ddsi_serdata_default```. In theory, this cast can be incorrect. In practice, when calling  nn_xmsg_addpar_keyhash(), it's always a default serdata type (currently). But it should be fixed to be future proof and more consistent with other serdata operations.

To fix this, ```ddsi_serdata_ops``` should be extended with a function that'll get the keyhash, just like all(?) the other serdata operations. That way, when re-directed, it's sure that the serdata type is actually default.

This problem was spotted on the security branch. A pull request on that branch is currently under construction that'll include a fix for this issue.

**Comment by martinbremmer** [comment]
The related Security PR is #361.

**Comment by thijsmie** [comment]
The fix for this bug was merged.
