### ISSUE TITLE
configurator issues

### ISSUE THREAD

**Issue by hansvanthag** [eclipse-cyclonedds/cyclonedds#38]
When trying to use the configurator (tools/config/cycloneddsconf.jar), a couple of issues were observed:

1. the domainId 'any' isn't understood (it rejects non-integer values, needs updating to latest source)
2. the 'internal' section is empty (needs to be generated from the doc's embedded in the sources)
3. the default directory it opens to look for configs points to some opensplice-related directory (cause not investigated but 'smells' like its looking in the location pointed to by OSPL_URI)

What I'd suggest is:
1. to include additional to 'cyclonedds.xml' also default configs for 1gpbs and 10gbps networks in the etc. directory (or use a config-directory under 'etc' as is common with other dds-products)
2. once proper installers are available, it makes sense to set the CYCLONEDDS_URI environment variable to point to the 'cyclonedds.xml' file in that etc/[config] directory

**Comment by eboasson** [comment]
It works again.
