### ISSUE TITLE
armhf build warnings

### ISSUE THREAD

**Issue by emersonknapp** [eclipse-cyclonedds/cyclonedds#388]
Starting about a month ago, we started getting build warnings in the packaging armhf build 

https://ci.ros2.org/view/packaging/job/packaging_linux-armhf/290/warnings23Result/

They are present in the latest build https://ci.ros2.org/view/packaging/job/packaging_linux-armhf/330/warnings23Result/
* atomics.c
* sync.c
* time.c

**Comment by emersonknapp** [comment]
Note we'll need approval for contribution to Cyclone - tracking ticket P32983843

**Comment by dirk-thomas** [comment]
@eboasson Can you please address these compiler warnings: https://ci.ros2.org/view/packaging/job/packaging_linux-armhf/357/warningsResult/category.-612026412/

**Comment by dirk-thomas** [comment]
And a different compiler warning on aarch64: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_extra_rmw_release/644/warningsResult/

**Comment by eboasson** [comment]
These have been fixed
