### ISSUE TITLE
Cyclone on ARM 

### ISSUE THREAD

**Issue by DungChau1996** [eclipse-cyclonedds/cyclonedds#419]
I have not found any statement claiming that CycloneDDS supports ARM. I appreciate that if I can have a confirmation about ARM support or any link to this issue. I apologize if I have not search well and missed something. 

Thanks in advance!

**Comment by eboasson** [comment]
Hi @DungChau1996, it runs fine on ARM. The reason you're not seeing much about it is that the differences between ARM and x86 are pretty much abstracted away by the compiler and operating system.

Cyclone DDS CI does yet build and test on ARM, but now that Travis CI has support for 64-bit ARM in alpha stage, that'll probably change. ROS2 CI does include 32- and 64-bit ARM builds, so indirectly there is coverage.

**Comment by sjames** [comment]
Confirmed. It does run on aarch64.

**Comment by DungChau1996** [comment]
@eboasson @sjames Thanks both of you :)! I think my question is sufficiently answered. I will close this issue after this.

**Comment by wjbbupt** [comment]
Hello, how did you cross-compile through arm, I have a problem with the compilation of the library corresponding to idlc
