### ISSUE TITLE
Mentions of PrismTech in Eclipse code

### ISSUE THREAD

**Issue by rotu** [eclipse-cyclonedds/cyclonedds#430]
CycloneDDS mentions PrismTech in the source code many times. Since ADLINK acquired PrismTech, it probably makes sense to change these mentions to ADLINK.

**Comment by eboasson** [comment]
Yes, I agree. It makes sense to include the name of the vendor in vendor-specific extensions, but it doesn't make sense to continue calling it PrismTech instead of ADLINK. I'll do a PR.

**Comment by eboasson** [comment]
Closed via #431
