### ISSUE TITLE
set proxy in cmake command

### ISSUE THREAD

**Issue by rainbowdn** [eclipse-cyclonedds/cyclonedds#434]
Hi, 
I am trying to build Cyclone and I am behind corporate proxy.
I set the HTTP_RPOXY, HTTPS_PROXY, http_proxy and https_proxy env variables via export command as well as in bashrc file.
I also added these proxies into the cmakelists.txt file as follows
```
set(ENV{http_proxy} "http://ip:port")
set(ENV{https_proxy} "http://ip:port")
set(ENV{HTTP_PROXY} "http://ip:port")
set(ENV{HTTPS_PROXY} "http://ip:port")
```
However, This cmake command ` cmake --build . --target install` keeps failing due to this error: 
`Plugin org.antlr:antlr4-maven-plugin:4.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.antlr:antlr4-maven-plugin:jar:4.5: Could not transfer artifact org.antlr:antlr4-maven-plugin:pom:4.5 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.120.215] failed: Connection timed out (Connection timed out) -> [Help 1]`
I am assuming that maven will get proxy config from env variables i set and therefore I have no clue where else I must set up Proxy.
any idea?

Best regards
However,

**Comment by trickapm** [comment]
Maven unfortunately has little regard for de-facto standards like the env. variables you've tried. You can setup proxy in maven configuration (~/.m2/settings.xml), see http://maven.apache.org/guides/mini/guide-proxies.html for more info

**Comment by rainbowdn** [comment]
thanks @trickapm
