### ISSUE TITLE
Clang-tidy warning in focal, printf %s argument is null

### ISSUE THREAD

**Issue by brawner** [eclipse-cyclonedds/cyclonedds#452]
There is a NULL pointer being passed to printf, which creates a clang-tidy warning and it looks like causes undefined behavior. This was recently discovered in [this nightly build](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1493/clang-tidy) after ci.ros2.org recently switched to focal for its default OS.
 
In https://github.com/eclipse-cyclonedds/cyclonedds/blob/5d53e740296873b2a70ee62536b2fe513526678c/src/tools/ddsperf/netload.c#L81, a call to record_netload() is passed with a NULL `prefix` argument, which is passed to printf() unchecked. It's unclear what the prefix argument is used for, but it may be possible to replace it with an empty string if the function definition requires consistency for API compatibility reasons.

**Comment by eboasson** [comment]
Thanks @brawner for reporting it. I'd say clang-tidy is wrong in warning because this null pointer is never actually passed to printf because ``data_valid`` is always false in this call. But I have no problem with changing it to an empty string if that makes clang-tidy happy.

**Comment by brawner** [comment]
This was addressed in #454
