### ISSUE TITLE
CycloneDDS V.0.5.1 Release Notes

### ISSUE THREAD

**Issue by yakuporhan** [eclipse-cyclonedds/cyclonedds#457]
Hi, 
I could not see release notes of V.0.5.1. What is the difference between v.0.5.0 and v.0.5.1? if you don't mind, can you share with us?

Thanks

**Comment by eboasson** [comment]
0.5.1 is just a snapshot that was kinda needed for updating the ROS2 binary packages and I was told it has to be of the x.y.z form for that process. There should be a proper 0.6 release soon, prior to merging the DDS Security support into master.

As to what changed, I was intending to prepare that change log for the 0.6 version and so I don't have it at hand, but it's basically support for liveliness, deadline and lifespan QoS settings and a bunch of bug fixes.

**Comment by yakuporhan** [comment]
@eboasson Thanks for information. 

But I missed a point. For now, does 0.5.1 support for liveness, deadline and lifespan?  Or should I wait v.0.6 for these ?

**Comment by eboasson** [comment]
> But I missed a point.

Thanks for asking, my reply was indeed rather confusing.

> For now, does 0.5.1 support for liveness, deadline and lifespan?

It does support it.
