### ISSUE TITLE
Default config

### ISSUE THREAD

**Issue by rotu** [eclipse-cyclonedds/cyclonedds#469]
It would be nice to have cyclone dds install a well-commented and sensible default config file in /etc with some configuration options. This would make the config options more discoverable and allow the user to edit cyclone behavior system-wide.

**Comment by thijsmie** [comment]
We consider the internal defaults to be quite decent, and in the repository and website there is quite extensive documentation on how to write configuration files. I've also just created [an issue on the python repository](https://github.com/eclipse-cyclonedds/cyclonedds-python/issues/100) that calls for the creation of a guided config creation tool. All this together seems better to me than a nebulous config file that applies system-wide, which could have unintended side-effects.
