### ISSUE TITLE
install package.xml ?

### ISSUE THREAD

**Issue by mikaelarguedas** [eclipse-cyclonedds/cyclonedds#473]
This project has a `package.xml` in it's source tree, but does not install it.
This makes it harder to install it's dependencies when downloading a compiled version like the one provided in the "fat" archives from ci.ros2.org.
The consumer of these archive cannot use tools like `rosdep` to install cyclonedds dependencies as the `package.xml` file is not present in install space.

Would the maintainers here be ok with installing the package manifest? (something similar to  https://github.com/ros2/poco_vendor/blob/3f23e18f8d71e979e03395d860bc3053d3162ae6/CMakeLists.txt#L100-L102)

**Comment by k0ekk0ek** [comment]
Hi @mikaelarguedas! I'd be fine with that. You want to open a PR for that?

**Comment by mikaelarguedas** [comment]
I actually have a doubt of where this file should be installed exactly. In the case of GNUInstallDirs I would just install it to `${CMAKE_INSTALL_DATADIR}/${PROJECT_NAME}`.
But the package name in the `package.xml` is `cyclonedds` (lowercase) so builds using e.g. colcon install all the resources related to this package in a `cyclonedds` directory.
So now it's unclear if it should be installed in under `share/cyclonedds` or `share/CycloneDDS`.

Maybe @cottsay or @dirk-thomas would have a recommendation?

**Comment by dirk-thomas** [comment]
The package name is lower case: https://github.com/eclipse-cyclonedds/cyclonedds/blob/9239547d34a634657b9fdb2a3fe124f1b2b2bc74/package.xml#L4

So `share/cyclonedds`.

**Comment by mikaelarguedas** [comment]
Thanks for the quick answer.
One concern i had with this is that the `ros-eloquent-cyclonedds` deb currently installs all it's cmake files under `/opt/ros/$ROS_DISTRO/share/CycloneDDS`, but will now install the `package.xml` in a different (previously non-existent) `/opt/ros/$ROS_DISTRO/share/cyclonedds` directory. Is it an expected difference between packages built with colcon and the debs provided by the ROS buildfarm ?

**Comment by thijsmie** [comment]
While no real conclusion or solution was reached, it doesn't seem that there is a dire need for this given there has been no new developments for two years. I'd be happy to re-open this if anyone runs into this, or even better: just submits a PR :innocent:!
