### ISSUE TITLE
Crash if using many threads

### ISSUE THREAD

**Issue by DensoADAS** [eclipse-cyclonedds/cyclonedds#479]
We are using cyclondds for ROS2 on a machine with 80 cores. By executing multithreaded executor (ROS2) results in a SIGABRT while "lookup_thread_state_real". By default for each core a thread is created. Limiting the number of threads in multithreaded executor to 32 solves the issue for now.

Backtrace:
`#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6069801 in __GI_abort () at abort.c:79
#2  0x00007ffff2efa9e2 in dds_log () from /home/ros/workspace/ros2_ws/ros2_core/install/cyclonedds/lib/libddsc.so.0
#3  0x00007ffff2ed2b4b in lookup_thread_state_real () from /home/ros/workspace/ros2_ws/ros2_core/install/cyclonedds/lib/libddsc.so.0
#4  0x00007ffff2ef5805 in dds_write_impl () from /home/ros/workspace/ros2_ws/ros2_core/install/cyclonedds/lib/libddsc.so.0
#5  0x00007ffff2ef58cb in dds_write () from /home/ros/workspace/ros2_ws/ros2_core/install/cyclonedds/lib/libddsc.so.0
#6  0x00007ffff31570e5 in rmw_publish () from /home/ros/workspace/ros2_ws/ros2_core/install/rmw_cyclonedds_cpp/lib/librmw_cyclonedds_cpp.so
#7  0x00007ffff721039f in rcl_publish () from /home/ros/workspace/ros2_ws/ros2_core/install/rcl/lib/librcl.so
`

Probably cause could be caused by the fixed number of max. allocated threads here:
https://github.com/eclipse-cyclonedds/cyclonedds/blob/b84eee5abbd4e935d3e47186e07ed93e4730b5f1/src/core/ddsc/src/dds_init.c#L113

**Comment by eboasson** [comment]
@DensoADAS you are correct. Once again proof that every quick workaround comes back to bite one ... I'd prefer a change that removes the limit altogether but that will take a bit of time.

You can safely raise the number, i.e., change the "64" in that line to "128" and you should no longer have to limit the number of threads in the executor.

**Comment by thijsmie** [comment]
This was solved, once and for all, by https://github.com/eclipse-cyclonedds/cyclonedds/pull/1290 :tada:.
