### ISSUE TITLE
compiling DDS with cmake 3.6.0-

### ISSUE THREAD

**Issue by xu3stones** [eclipse-cyclonedds/cyclonedds#48]
Hi，
In my special linux, the repo only offers cmake 3.4, but it seems that CycloneDDS compiling requried cmake 3.6+ (claimed at the Readme.md).
So, i want to know what's the necessity. In another word, which features in the CMakefile.txt are advanced that only supported by cmake 3.6+.

Thanks a lot~~!

**Comment by eboasson** [comment]
Hi @xu3stones, I don't know, it might be as simple as it requiring the version that was used at the time the CMakeFiles were originally written ... the cmake release notes don't suggest that there are major changes, certainly not ones that seem relevant for building it on Linux.

If I were you, I'd change the minimum required version to 3.4 and give it a shot. That sure does the trick on macOS :)

**Comment by xu3stones** [comment]
Thanks a lot! Based on your suggestion, i feel more confident.

 Before that, i worry about that i may miss some technical details. So, i will have a try on my special linux distro.

**Comment by eboasson** [comment]
I suppose it must have worked; so closing.
