### ISSUE TITLE
Create a branch to track latest major release

### ISSUE THREAD

**Issue by rotu** [eclipse-cyclonedds/cyclonedds#482]
Right now, there are tags `V0.5.0`, `0.5.1` to track specific releases. We should have a branch to track compatible releases (maybe `releases/0.5.x`, `releases/1.x`) https://github.com/ros2/ros2/pull/891#discussion_r405828804

@ThijsSassen, @eboasson

**Comment by eboasson** [comment]
That should not be a problem (release/0.5.x sounds fine to me). I think it should be from current master because that's what it has been up to now. Ok?

**Comment by rotu** [comment]
I'm okay with putting it at 0.5.1 or with creating a commit on master with current release notes and maybe new version number.

**Comment by eboasson** [comment]
Done (at the tag)
