### ISSUE TITLE
[Question] Is DDS useful for intermittent local communications without a fixed network?

### ISSUE THREAD

**Issue by msmcconnell** [eclipse-cyclonedds/cyclonedds#524]
I am investigating whether DDS is appropriate for my use case where IoT devices need to share local data with each other. Consider the situation below:
Imagine I have two IoT devices which can move (a cell phone, car, drone, etc.). These devices need to share data about their local environment with other devices near by. To reduce delivery time, this data is shared using local broadcast communications such as Bluetooth or radio transmission. In other words the data is not going over a cellular data connection like 4G. 

For example you could have a situation like this where no device sees another.
<img src="https://user-images.githubusercontent.com/10292079/82373602-cd5cd980-99eb-11ea-976d-5701fc4d6492.png" width="250" height="250">

But later on they could interact:
<img src="https://user-images.githubusercontent.com/10292079/82374272-ce423b00-99ec-11ea-8a3a-19ebe9a6a1a0.png" width="250" height="150">

So, new data transmission on topics would only occur in the second image. 
It seems to me that this could be done using a new transport layer leveraging the local communication method like bluetooth. However, I am not sure if this is something DDS is really designed to support. Would this be practical or would it make more sense to just use more traditional broadcast communication protocols and reserve DDS for internal or internet based communications?

**Comment by k0ekk0ek** [comment]
Hi @msmcconnell. I think using DDS makes perfect sense for this use case. The device going in and out of range isn't that different from a device being connected and disconnected from a network when you think of it and that sort of thing is handled really well by DDS. Not that DDS is tied to Ethernet. As you suspect, It's indeed designed to be transport agnostic (hence the abstraction). You are right that another transport would be needed (the `raweth` transport may or may not provide a good example).

I'm not familiar enough with Bluetooth or requirements on the transports to give implementation advice right this instant, but @eboasson can probably provide you with a couple of pointers. It'd definitely be a fun project, so if do decide to give Cyclone DDS a try, I'd love to help out where I can. It's very likely other people are interested in this as well.

**Comment by joespeed** [comment]
@msmcconnell you and your friends there would probably be interested in this bit of work integrating cyclonedds with its Eclipse Zenoh sister project. This also enables V2V, V2X. Putting the two together is good carma😉
[EclipseCon: Edge Robotics with ROS2 and Eclipse Zenoh](https://www.eclipsecon.org/2020/sessions/edge-robotics-ros2-and-eclipse-zenoh ) by @kydos 
https://github.com/eclipse-zenoh
http://zenoh.io

**Comment by msmcconnell** [comment]
@joespeed Haha thanks for sharing Joe! That does look very promising, I will try to addend.

**Comment by thijsmie** [comment]
Anno 2022 Zenoh is probably the best choice for this kind of deployments, especially if you are using extremely resource limited devices. Building custom transports for DDS is still possible, more on that front is coming.
