### ISSUE TITLE
Relation/difference to OpenDDS

### ISSUE THREAD

**Issue by ConradGroth** [eclipse-cyclonedds/cyclonedds#545]
How is this project related to OpenDDS (www.opendds.org)? Was it forked from there?
What's the intent of building another open DDS version?

**Comment by eboasson** [comment]
Eclipse Cyclone DDS is entirely unrelated to OpenDDS, and unlike any of the other open-source DDS implementations is outside the control of a single company but rather overseen by the Eclipse Foundation.

From a technical perspective, the aims of the other open-source implementations at the time Cyclone started (I think it is still true, but with Fast-RTPS recently having become Fast-DDS, who knows) seem to be more limited than those of Cyclone DDS. Cyclone DDS aims to support the full complement of the OMG DDS specifications, in particular including all the profiles in the DCPS specification. For example, that means it will come to properly support transient data, content-based subscriptions and group coherent data. DDS Security is supported now, work is underway for XTypes and transient data, and so on so forth.

As far as I know it is also the only one capable of running on somewhat constrained embedded platforms, e.g., FreeRTOS on a Cortex M4, but I haven't investigated the others closely enough to be certain. Performance-wise it already outclasses a good few of the other available implementations (open-source and commercial), judging by the scarce publicly available information.

So I'd say the real question is why the others still bother 😀

**Comment by thijsmie** [comment]
A clear and consice answer was provided, and clearly no more confusion exists about this topic :eyes:.
