### ISSUE TITLE
[Question] Rust language wrapper around cyclonedds ?

### ISSUE THREAD

**Issue by hjwillems** [eclipse-cyclonedds/cyclonedds#573]
Question:
As some other opensource DDS implementations are written in C++, it's not very doable to link it to Rust.
cyclonedds is the only opensource DDS implementation in C, and therefore it should be technically possible to generate a cyclonedds-sys (autogenerated FFI) for Rust and write a Wrapper for Rust. 
There is currently no DDS implementation for Rust, and the next closest thing is cyclonedds with FFI bindings and a Rust wrapper around it. 

Does anyone know somewhere or something like this is happening? cyclonedds is a very nice implementation and i applaud this project. (love the story that it started out in Thales in the Netherlands, i like the company)

**Comment by k0ekk0ek** [comment]
Hi @hjwillems! There's definitely interest and there's also [cdds-rust](https://github.com/atolab/cdds-rust). I haven't tried it myself, so I don't know how good it is, but it might be what you're looking for. I also don't know if/how they solved type generation, but on ticket #539 some people are discussing that specifically. Perhaps the best way is to just give cdds-rust a try(?)

**Comment by joespeed** [comment]
@hjwillems we love Rust! cdds-rust is by @esteve & @kydos so will be great if it isn't already

**Comment by esteve** [comment]
@joespeed thanks for the shout out! @hjwillems we're (@kydos and I) working on Rust bindings for CycloneDDS at https://github.com/atolab/cdds-rust, as @k0ekk0ek point out. The bindings can be installed from the crates registry (https://crates.io/crates/libddsc-sys https://crates.io/crates/ddsc).

The low-level API is generated from bindgen but the high-level API is still a work in progress, you can have a glimpse of it on my fork (https://github.com/esteve/cdds-rust/tree/add-pubsub). I plan to add minimum pubsub and then expand it to provide more features.

The current goal for `cdds-rust` is mostly for integrating CycloneDDS with zenoh-router, but if there's anything you'd like to see in `cdds-rust` for your usecase, please feel free to file issues and/or submit PRs to it, we'd be delighted :slightly_smiling_face:  Thanks!

**Comment by hjwillems** [comment]
Clear response! Yes i saw the libddsc-sys as autogenerated bindings. But on top of that you still need to write a clean "rust" api for CycloneDDS right? Maybe it's better for me to first use CycloneDDS in C to get a feeling of how DDS C api's fully work, and more "advanced" rust knowledge to be able to do some PRs. Certainly going to monitor it. This is probably the only closest opensource effort out there to get DDS in Rust. Hope i can help any in the future. Thanks for the initial effort. Am also going to check into zenoh, seems also very interesting! Think my question is answered perfectly.
