### ISSUE TITLE
update CHANGELOG to 0.7.0

### ISSUE THREAD

**Issue by joespeed** [eclipse-cyclonedds/cyclonedds#575]
@eboasson please update to 0.7.0
https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/CHANGELOG.rst

**Comment by eboasson** [comment]
For 2 weeks I kept it in "release candidate" state so any late show-stoppers could be adressed and *now* you mention I forgot to update the change log? 🙄 (Although in fairness, that 🙄 applies at least as much to me for forgetting it!)
