### ISSUE TITLE
When to release the first version

### ISSUE THREAD

**Issue by xu3stones** [eclipse-cyclonedds/cyclonedds#62]
I want to know when can release the first version of cyclonedds, just like 0.1.0.
 It will help us to know what the new features are introduced between two versions, and will be easier to follow this project.
Haha, maybe you already have a plan or a roadmap (like, before the Christmas Day)...

**Comment by k0ekk0ek** [comment]
Hi @xu3stones. There currently is no hard release date set. That being said, the core isn't likely to change all that much wrt wire compatibility. Maybe you can state what features you require and what you're going to use it for? That way we maybe able to help you a bit better.

**Comment by xu3stones** [comment]
Thanks for your reply @k0ekk0ek . I'm now working in a team that wants to introduce cyclonedds as our commnication middleware on an Antomotive Vehicle demo. We'd like to choose all opensource softwares inside our system with a specific version number, that becauses we want to form our baseline. Tracking the updating of each opensource software that we choose in our system is a luxury. That being said, we only replace each of them util new version releases. So, if you release 0.1.0, we introduce it and update it at the time you release 0.2.0. _I know it is a strange way that we work~~_

By now, the features cyclonedds provides fit us well. Maybe later, we want to use more features, like priority/ latency_budget/deadline QoS, SharedMemroy Tranport, C++/JAVA binding and improvement on deterministic latency(important in our case, we want to achieve 2MB/1ms between 2 nodes in most time).

**Comment by k0ekk0ek** [comment]
Hi @xu3stones, sorry about the late reply. We're planning on releasing a first commercial version in Q1, so we're likely to create a release somewhere in that time period.

A shared memory transport isn't on the roadmap yet (but we welcome pull requests ;)). C++ and Java are planned for next year, I'm not sure about the time frame for those. The biggest challenge for supporting more languages is the IDL compiler. Which is being worked on as we speak. Keep an eye on the xtypes branch that.

Hope that answers your question(s) for now?

**Comment by xu3stones** [comment]
@k0ekk0ek , thanks for your reply. We will keep our watch on this project.

**Comment by i-and** [comment]
Hi, k0ekk0ek. Explain what it means "We're planning on releasing a **first commercial version** in Q1"? What kind of project do you mean? What is the license of the cyclonedds? Based on which version of OpenSplice was created cyclonedds?

**Comment by k0ekk0ek** [comment]
Hi @i-and. What I meant was: we have a commercial offering based on Cyclone DDS and we're hard at work on getting a release out the door. No promises or eta's etc. That's simply not up to me.

I don't know which version of OpenSplice it's based on exactly.

Apart from that, I really think that the Cyclone DDS project isn't the place to discuss OpenSplice or any commercial product that ADLINK as a company offers. If you have any questions regarding the project, I'm happy to help you out, but for commercial inquiries please go through the appropriate channels.

**Comment by eboasson** [comment]
Hi @i-and, Eclipse Cyclone DDS is an Eclipse project: a non-commercial, open source project, overseen by the [Eclipse Foundation](https://www.eclipse.org). It is dual-licensed under the EPL and the EDL — the full text is readily available, for example in the [LICENSE](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/LICENSE) file.

Eclipse Cyclone DDS has a common heritage with OpenSplice in the DDSI-RTPS implementation and in some utility functions, but the two have evolved independently. This common heritage constitutes only part of Cyclone and but a small fraction of the code base of OpenSplice. There is no such thing as a version of OpenSplice “Based on which [...] was created cyclonedds”.

Discussions of commercial products and other projects, their roadmaps, features or anything else, have no place here — except insofar as they concern technical matters relevant to the design and implementation of Eclipse Cyclone DDS.

**Comment by eboasson** [comment]
The original question seems to have been satisfactorily answered, so I am closing this issue.

**Comment by i-and** [comment]
Thank you for the detailed answer.
