### ISSUE TITLE
add ROS2 Quality Declaration to cyclonedds repo

### ISSUE THREAD

**Issue by joespeed** [eclipse-cyclonedds/cyclonedds#637]
@k0ekk0ek please copy this [ROS2 CycloneDDS Quality Declaration](https://github.com/ros2/rmw_cyclonedds/blob/master/CYCLONEDDS_QUALITY_DECLARATION.md) to this repo.

Please update "Cyclone DDS meets all the requirements ..." to say "Cyclone DDS including rmw_cyclonedds meets all the requirements ..."

**Comment by k0ekk0ek** [comment]
:heavy_check_mark:
