### ISSUE TITLE
package.xml Missing Dependency on Java

### ISSUE THREAD

**Issue by JWhitleyWork** [eclipse-cyclonedds/cyclonedds#642]
When building a ROS package which depends on IDLC in a clean ROS Foxy environment (currently uses CycloneDDS 0.7.0 from the build farm), the build fails with the following CMake error:

```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Java (missing: Java_JAVA_EXECUTABLE Java_JAR_EXECUTABLE
  Java_JAVAC_EXECUTABLE Java_JAVAH_EXECUTABLE Java_JAVADOC_EXECUTABLE)
  (Required is at least version "1.8")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindJava.cmake:332 (find_package_handle_standard_args)
  /opt/ros/foxy/lib/x86_64-linux-gnu/cmake/CycloneDDS/idlc/IdlcGenerate.cmake:12 (find_package)
  /opt/ros/foxy/lib/x86_64-linux-gnu/cmake/CycloneDDS/CycloneDDSConfig.cmake:43 (include)
  CMakeLists.txt:34 (find_package)
```

This is because Java is not automatically installed to the ROS environment when CycloneDDS is installed due to a missing entry in `package.xml`. A different error is presenteded if building CycloneDDS from source but that error is for another issue and both are resolved by installing `default-jdk` in Ubuntu. The missing line from `package.xml` should be:

```
<build_depend>java</build_depend>
```

as the `rosdep` key for all supported OSs is `java`. Since the build farm builds IDLC by default and it requires Java on the host system to be able to use it, either building it by default should be disabled or the JDK should be added as a dependency.

**Comment by thijsmie** [comment]
Note that we no longer depend on Java: `idlc` was rewritten in pure C.
