### ISSUE TITLE
Integrate deepcode

### ISSUE THREAD

**Issue by prasannabhat** [eclipse-cyclonedds/cyclonedds#644]
[Deepcode](https://www.deepcode.ai/) is AI assisted code review tool. (Think of it like a robo assisting in code reviews)
At times, it gives good suggestions, which can be helpful in improving coding practices.
Its possible to setup deepcode to analyse PR. (it need not be a mandatory checkpoint)

Setting up Deepcode requires github's permission.

Ex : deepcode [badge](https://github.com/prasannabhat/cyclonedds/tree/user/deepcode) looks like this. (I think it might not be possible to browse the report, without logging into github and providing access to deepcode)

**Comment by k0ekk0ek** [comment]
Hi @prasannabhat! Could be interesting depending on the errors it found. I noticed it found 10 errors in your fork, would it be possible to share them somewhere so we have a little more information? The GitHub app required me to give permission to "act on my behalf", which I'm not willing to give just to find out if it's any useful.

**Comment by prasannabhat** [comment]
Hi @k0ekk0ek 
There is no export feature in deepcode. May be the workflow of integrating deepcode is so simple that authors may have found that export feature is not necessary for the workflow ! (May be its possible by running it on the desktop)

For now , I attach screenshot for your quick reference.
![deepcode](https://user-images.githubusercontent.com/1105952/100402445-436c8800-3082-11eb-945d-24f4c4068a9f.png)

Clicking on **More Details** leads to suggestions as to how fellow developers have fixed similar kind of issue.

**Comment by thijsmie** [comment]
While interesting we have Coverity to catch issues and it seems deepcode was also aquired/transitioned to something called snyk? We will continue with the current setup and take Coverity/user reports instead, and they are free to use tools like these.
