### ISSUE TITLE
add related tickets to roadmap items

### ISSUE THREAD

**Issue by joespeed** [eclipse-cyclonedds/cyclonedds#645]
per @mikeferguson one high level piece of feedback - for each of the bullet points, if there is like a related ticket with more detail of what that feature really entails, that'd probably make the roadmap make more sense to a larger audience (they could dig into whether that feature is really what they think it is, and give input about how they want to use that feature)

**Comment by eboasson** [comment]
We're working hard on cleaning up the old issues and preparing a proper roadmap, so I am closing this.
