### ISSUE TITLE
Questions about performance test results

### ISSUE THREAD

**Issue by aohwang** [eclipse-cyclonedds/cyclonedds#665]
Hi friends,

I searched online for a DDS implementation for resource-constraint embedded devices, and the Cyclone DDS is what I want. The most attractive part for me is the performance according to the README. But after the performance test by myself, I find that the performance is not good as the described. Are there something wrong with my operations?

Thanks sincerely

The testing environment is shown below.

    Two ThinkPad laptops connected with each other directly using Ethernet cable.
    OS: Windows 10 1909
    RAM: 16GB
    CPU:  Intel Core I7-10510U 2.3GHZ

The Cyclone DDS configuration is shown below.

    <CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <NetworkInterfaceAddress>auto</NetworkInterfaceAddress>
            <AllowMulticast>spdp</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>65000B</FragmentSize>
        </General>
        <Internal>
            <Watermarks>
                <WhcHigh>5000kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>warning</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
    </CycloneDDS>

Parts of the test results are shown below.

    E:\CycloneDemo\win-cyclonedds-roundtrip-bin>.\RoundtripPing.exe 0 2000 0
	# payloadSize: 0 | numSamples: 2000 | timeOut: 0
	
	# Waiting for startup jitter to stabilise
	# Warm up complete.
	
	# Latency measurements (in us)
	#             Latency [us]                                   Write-access time [us]       Read-access time [us]
	# Seconds     Count   median      min      99%      max      Count   median      min      Count   median      min
        1       718      668      336     1001     1034        718      124       30        718       18        3
        2       638      752      334     1016     1026        638      124       93        638       18       14
        3       644      750      397     1017     1033        644      125       94        644       18       14

	# Overall      2000      717      334     1014     1034       2000      124       30       2000       18        3

    E:\aohwang\CycloneDemo\win-cyclonedds-roundtrip-bin>.\RoundtripPing.exe 128 2000 0
	# payloadSize: 128 | numSamples: 2000 | timeOut: 0

	# Waiting for startup jitter to stabilise
	# Warm up complete.

	# Latency measurements (in us)
	#             Latency [us]                                   Write-access time [us]       Read-access time [us]
	# Seconds     Count   median      min      99%      max      Count   median      min      Count   median      min
        1       590      858      422     1049     1062        590      125       97        590       20       15
        2       637      761      447     1031     1056        637      125       45        637       20        5
        3       591      856      412     1053     1065        591      126       92        591       20       15

	# Overall      2000      815      377     1046     1065       2000      125       45       2000       20        5

    E:\aohwang\CycloneDemo\win-cyclonedds-roundtrip-bin>.\RoundtripPing.exe 4096 2000 0
	# payloadSize: 4096 | numSamples: 2000 | timeOut: 0
	
	# Waiting for startup jitter to stabilise
	# Warm up complete.
	
	# Latency measurements (in us)
	#             Latency [us]                                   Write-access time [us]       Read-access time [us]
	# Seconds     Count   median      min      99%      max      Count   median      min      Count   median      min
        1       403     1337      525     1840     1876        403      170      117        403       29       19
        2       430     1014      482     1853     1884        430      172      127        430       29       21
        3       370     1522      469     1851     1878        370      170      134        370       29       21
        4       360     1539      444     1850     1864        360      169      133        360       29       23
        5       364     1513      470     1849     1885        364      170       66        364       29       11

	# Overall      2000     1466      444     1847     1885       2000      170       64       2000       29       11

	E:\aohwang\CycloneDemo\win-cyclonedds-roundtrip-bin>.\RoundtripPing.exe 8192 2000 0
	# payloadSize: 8192 | numSamples: 2000 | timeOut: 0

	# Waiting for startup jitter to stabilise
	# Warm up complete.

	# Latency measurements (in us)
	#             Latency [us]                                   Write-access time [us]       Read-access time [us]
	# Seconds     Count   median      min      99%      max      Count   median      min      Count   median      min
        1       515      853      354     1871     1886        515      163       41        515       27        5
        2       351     1570      545     1870     1883        351      183      128        351       30       21
        3       364     1528      469     1875     1894        364      180      115        364       30       20
        4       427     1038      491     1867     1887        427      177      129        427       30       21

	# Overall      2000     1380      354     1872     1916       2000      180       41       2000       30        5

	E:\aohwang\CycloneDemo\win-cyclonedds-roundtrip-bin>
	E:\aohwang\CycloneDemo\win-cyclonedds-roundtrip-bin>.\RoundtripPing.exe 16384 2000 0
	# payloadSize: 16384 | numSamples: 2000 | timeOut: 0

	# Waiting for startup jitter to stabilise
	# Warm up complete.
	
	# Latency measurements (in us)
	#             Latency [us]                                   Write-access time [us]       Read-access time [us]
	# Seconds     Count   median      min      99%      max      Count   median      min      Count   median      min
        1       359     1595      609     1917     1948        359      189      157        359       31       23
        2       418     1166      419     1907     1939        418      182       59        418       32        8
        3       355     1601      628     1923     1931        355      200      143        355       33       23
        4       345     1631      663     1952     1967        345      202      158        345       32       25
        5       347     1617      632     1954     1971        347      209      156        347       33       25

	# Overall      2000     1578      419     1933     1971       2000      200       59       2000       32        8

**Comment by eboasson** [comment]
A minimum latency for tiny messages of about 300µs over GbE? That's a long time ...

GbE itself should be below 50µs, and your machine is a perfectly normal that should easily be able to do all the processing within another 10µs, even with a "Debug" build. The only thing I can think of right now is that the CPU power management kicks in every round on both sides, and waking up from idle states does seem to take quite some time: I once guesstimated on my i7-based macbook pro that it took ~80µs.

Keeping the CPU busy with a low priority process should prevent that; and maybe Windows gives you a "performance" setting for power management that would prevent this from happening. Perhaps you could check whether power management might be a factor here?

I don't think a Cyclone trace or a wireshark capture would give much information because everything seems to working properly (albeit slowly) but if you want I'll have a look at it.

**Comment by hansvanthag** [comment]
I assume it was verified that the connection was indeed a GbE connection ?
A highres-ping should be able to show a <50us roundtrip too ..

**Comment by aohwang** [comment]
@eboasson  @hansvanthag 
Thanks for your explanations. I think the latency is big because of the USB 3.0-to-Ethernet adapter I used. I will perform a new performance test later. Thanks again.

**Comment by thijsmie** [comment]
Problem was most likely the users hardware, will re-open if there are further problems.
