### ISSUE TITLE
Questions about Qos in cycloneDDS 

### ISSUE THREAD

**Issue by Jingzhao123** [eclipse-cyclonedds/cyclonedds#682]
Hi, 
I am a freshman in cyclonedds. I have a few questions about Qos in DDS. Could you please help to check it?
I notice there are 22 Qos-options in [DDS Spec](https://www.omg.org/spec/DDSI-RTPS/2.3/PDF) (8.7.2). And some of them have been implemented in dds_qset_xxx functions. My questions are:

- Have all Qos features been implemented in the latest cyclonedds version?

- Is there any document describing those Qos features in cycloneDDS?

Thanks very much!

**Comment by eboasson** [comment]
> Have all Qos features been implemented in the latest cyclonedds version?

The `dds_qos_t` object can handle all QoS settings, but the functionality behind them is not yet implemented for all of them. The incomplete ones are:
* presentation (publisher/subscriber)
* time based filter
* durability kinds transient and persistent
* transport priority and latency budget (they are only hints, but still)
* reader data lifecycle

The rest is fully supported.

Do note that the "durability service" QoS setting is a bit of a odd one. Given that Cyclone does not yet implement the "transient" or "persistent" settings for the durability setting, most of the "durability service" setting is meaningless. Its "history" component is used by writers with "transient-local durability".

> Is there any document describing those Qos features in cycloneDDS?

There ought to be one, but there isn't currently. So it is good of you to ask!

**Comment by Jingzhao123** [comment]
Thanks for your comments. It is a very good answer!
