### ISSUE TITLE
Can cyclonedds be built without SSM?

### ISSUE THREAD

**Issue by asobhy-qnx** [eclipse-cyclonedds/cyclonedds#710]
I would like to build cyclonedds for QNX. When removing DDSI_INCLUDE_SSM definition from src/CMakeLists.txt and adding a few patches to help find header files the source builds just fine, but when testing with local nodes I keep getting the error "ddsi_udp_create_conn: failed to bind to ANY:7400: address in use", although setsockopt with SO_REUSEADDR was used.

**Comment by eboasson** [comment]
It could be that QNX also requires `SO_REUSEPORT` to be set — I know macOS and the BSDs do: https://github.com/eclipse-cyclonedds/cyclonedds/blob/1f37789ec4223b66aa2170327165992d27da9ea5/src/ddsrt/src/sockets/posix/socket.c#L319

**Comment by asobhy-qnx** [comment]
Yes that is the reason. Thank you for your quick feedback
