### ISSUE TITLE
Multi ECU configuration

### ISSUE THREAD

**Issue by wep21** [eclipse-cyclonedds/cyclonedds#729]
I would like to achieve a system as below.
![system](https://user-images.githubusercontent.com/42202095/112346519-60038e80-8d09-11eb-9313-4423c653a528.png)
- Main PC should receive topics from logging PC(usb camera), edge PC(camera detection result),
- Logging PC should receive topics from main PC(lidar, imu, etc), edge PC(camera).
There are over 50 nodes in Main PC to achieve autonomous driving application.
I successfully received topics only from logging PC in main PC by specifying NIC for multicast as below.
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <NetworkInterfaceAddress>xxx</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
However, I guess specifying multiple network is not supported yet https://github.com/eboasson/cyclonedds/tree/multi-home-red-netw, so I have to disable multicast and specifying all target ip addresses in Peer as below, right?
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <AllowMulticast>false</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
        <Discovery>
            <ParticipantIndex>auto</ParticipantIndex>
            <MaxAutoParticipantIndex>100</MaxAutoParticipantIndex>
            <Peers>
                <Peer Address="192.168.2.1" />
                <Peer Address="192.168.2.2" />
                <Peer Address="192.168.2.3" />
                <Peer Address="192.168.2.4" />
                <Peer Address="192.168.2.5" />
                <Peer Address="192.168.2.6" />
                <Peer Address="192.168.3.20" />
            </Peers>
        </Discovery>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```

**Comment by eboasson** [comment]
Hi @wep21 that should work, but I would expect you could specify a configuration that specifies the 192.168.2.x network on the main and edge PCs that allows multicast, and do a configuration that disables multicast on the other nodes (it doesn't have to be configured the same throughout the system). You'd still need Peer entries, but there'd be fewer, and of course you'd have multicast in the core part of the system

Also it probably is wise to set `MaxAutoParticipantIndex` no larger than necessary because with this configuration, there will be participant discovery bursts of one 100 packets each to 7 peers, so that adds up.

As to:

> However, I guess specifying multiple network is not supported yet https://github.com/eboasson/cyclonedds/tree/multi-home-red-netw

That branch should do the trick. If you're feeling adventurous, then I would appreciate it very much if you would give it a try, that would make me feel much better about merging the work without having proper tests in place. Those "proper tests" on random CI machines in the cloud will, I fear, involve writing a virtual network stack just for testing. So that's non-trivial in itself.

Using it should be no more complicated than checking it out, building it and listing the relevant network interfaces in the `NetworkInterfaceAddress` field. (That branch allows up to 4 interfaces, so that should be fine.)

**Comment by wep21** [comment]
@eboasson Thank you for your reply. So you mean multicast and peer entries can work simultaneously as below right?
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <NetworkInterfaceAddress>(NIC which is connected to hub2)</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
        <Discovery>
            <ParticipantIndex>auto</ParticipantIndex>
            <MaxAutoParticipantIndex>100</MaxAutoParticipantIndex>
            <Peers>
                <Peer Address="192.168.3.20" />
            </Peers>
        </Discovery>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```

> Also it probably is wise to set MaxAutoParticipantIndex no larger than necessary because with this configuration, there will be participant discovery bursts of one 100 packets each to 7 peers, so that adds up.

When `MaxAutoParticipantIndex` is default, many nodes died with an error as below, so I increased `MaxAutoParticipantIndex`.
```
[rviz2-66] 1616688436.289744 [1]      rviz2: using network interface wlp2s0 (udp/192.168.150.52) selected arbitrarily from: wlp2s0, virbr0, docker0, br-9950e95b9a7b
[rviz2-66] 1616688436.291201 [1]      rviz2: Failed to find a free participant index for domain 1
[rviz2-66] [ERROR 1616688436.291438313] [rmw_cyclonedds_cpp]: rmw_create_node: failed to create domain, error Error
[rviz2-66] 
[rviz2-66] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[rviz2-66] This error state is being overwritten:
[rviz2-66] 
[rviz2-66]   'error not set, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/node.c:276'
[rviz2-66] 
[rviz2-66] with this new error message:
[rviz2-66] 
[rviz2-66]   'rcl node's rmw handle is invalid, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/node.c:428'
[rviz2-66] 
[rviz2-66] rcutils_reset_error() should be called after error handling to avoid this.
[rviz2-66] <<<
[rviz2-66] [ERROR 1616688436.291577105] [rcl]: Failed to fini publisher for node: 1
[rviz2-66] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[rviz2-66]   what():  failed to initialize rcl node: rcl node's rmw handle is invalid, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/node.c:428
[rviz2-66] 1616688436.289744 [1]      rviz2: using network interface wlp2s0 (udp/192.168.150.52) selected arbitrarily from: wlp2s0, virbr0, docker0, br-9950e95b9a7b
[rviz2-66] 1616688436.291201 [1]      rviz2: Failed to find a free participant index for domain 1
```

**Comment by eboasson** [comment]
> @eboasson Thank you for your reply. So you mean multicast and peer entries can work simultaneously as below right?

Yes, that looks fine to me. The key thing is that on the logging PC you will then need to disable multicast because otherwise both sides will be advertising multicast support and it will therefore rely on it even though it doesn't actually work because of the different networks. You probably then also don't have to specify a peer on the logging PC: if two-way traffic works, you only need one participant discovery message to start the discovery process.

> 
> > Also it probably is wise to set MaxAutoParticipantIndex no larger than necessary because with this configuration, there will be participant discovery bursts of one 100 packets each to 7 peers, so that adds up.
> 
> When `MaxAutoParticipantIndex` is default, many nodes died with an error as below, so I increased `MaxAutoParticipantIndex`.
> [...]
> Is `MaxAutoParticipantIndex` relevant to the number of ros nodes?

I am very happy to you increased `MaxAutoParticipantIndex`, it is just that the "100" made me concerned about the size of those discovery bursts. The relationship between ROS nodes and these indices is that you consume one participant index for each process that uses ROS (or DDS) on a machine. So if you have (for the sake of the argument) 40 ROS nodes on the main PC, and they are all in a single process, you consume only 1 index, even though there are 40 ROS nodes. If instead you have one ROS node per process, you need 40 indices. Anything in between is possible, too, of course.

The participant index figures in the port number calculation and those discovery bursts I mentioned exist because it doesn't know on which ports there may be participants listening (that's the point of discovery, after all). It periodically sends packets to all these port numbers even though it gets all kinds of "port unreachable" ICMP messages back because you never know when circumstances change.

In all "normal" circumstances, you could simply stop sending to port X if after a few tries you haven't received a response yet, because it would be perfectly reasonable to expect a process that starts to use port X to ping you on startup. What that doesn't cater for is all kinds of weird and unlikely scenarios, such as where you start up on two machines while the network cable is broken and it gets fixed later on. So until I figure out a guaranteed correct way to avoid periodically sending packets to all possible port numbers, I have to let it spam the network.

And therefore I always suggest using the smallest value for `MaxAutoParticipantIndex` that works. If it works fine with 100 for you and those discovery bursts cause no problems of their own, then of course 100 is fine, too.

**Comment by wep21** [comment]
@eboasson 
I tried with this configurations as below.
- main
```
 <?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
	    <NetworkInterfaceAddress>enp8s0(connected to hub2)</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
    	</General>
	<Discovery>
	    <MaxAutoParticipantIndex>120</MaxAutoParticipantIndex>		
            <ParticipantIndex>auto</ParticipantIndex>
	    <Peers>
                <Peer Address="192.168.3.20" />
            </Peers>
	</Discovery>
	<Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
- logger
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
	    <NetworkInterfaceAddress>enp9s0(connected to hub2)</NetworkInterfaceAddress>
            <AllowMulticast>false</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>    
	<Discovery>
            <ParticipantIndex>auto</ParticipantIndex>
	    <Peers>
	        <Peer Address="192.168.3.10" />
	    </Peers>
    	</Discovery>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
	<Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
- edge
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
	    <NetworkInterfaceAddress>eth0</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
First I removed peer entity in logger configuration, but I did not find any topic in logger PC, so I added peer entity into logger configuration. Then, I found topics from main PC in logger PC.  However this configuration is not enough because logger PC cannot receive camera image topics from edge PC.

**Comment by wep21** [comment]
Also I forgot that all PCs are connected with hub2, so I guess this configuration as below is the most easiest way.
- main
```
 <?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
	    <NetworkInterfaceAddress>enp8s0(connected to hub2)</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
    	</General>
	<Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
- logger
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
	    <NetworkInterfaceAddress>enp9s0(connected to hub2)</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>    
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
	<Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
- edge
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
	    <NetworkInterfaceAddress>eth0</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
This configuration achieved the topic discovery which I wanted to establish, but the camera topic rate measured in logger PC is slow.

**Comment by wep21** [comment]
> That branch should do the trick. If you're feeling adventurous, then I would appreciate it very much if you would give it a try, that would make me feel much better about merging the work without having proper tests in place. Those "proper tests" on random CI machines in the cloud will, I fear, involve writing a virtual network stack just for testing. So that's non-trivial in itself.
I tried this branch in main PC. Configurations are as below.
- main
```
 <?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
	    <NetworkInterfaceAddress>enp8s0,logging_bond0</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
	<Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
- logger
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
	    <NetworkInterfaceAddress>logging_bond0</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
	<Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
- edge
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
	    <NetworkInterfaceAddress>eth0</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
With these configurations, I can see topics from both logger PC and edge PC, so I guess this branch works correctly.

**Comment by wep21** [comment]
@eboasson https://github.com/eboasson/cyclonedds/tree/multi-home-red-netw will be merged into v0.8.0?

**Comment by eboasson** [comment]
That's the plan, yes! 😀

That branch actually fixes a number of issues in the v0.8.0 pre-release branch when rebased on top of it, so it is doubly important that it gets done. https://github.com/eboasson/cyclonedds/tree/iox-multihome is the same branch rebased on the current v0.8.0 beta tag, but it needs a bit of TLC before it can be merged.

I'm likely to do some force-pushes to it still, but you're more than welcome to try it.

**Comment by wep21** [comment]
@eboasson hi, I have a question about multihome. When there are two cables bewtween ecu1 and ecu2 and these interfaces are added in `<NetworkInterfaceAddress>`, which one is selected as data communication? Also, is it possible to select a interface as data pipeline like `NetworkPartitions`?

**Comment by eboasson** [comment]
@wep21 it'll pick the address it deems best (unless you enable the experimental "RedundantNetworking", in which case it'll use both). The address it considers best is (roughly) the one that reaches the most readers (with a penalty for any readers that will be served duplicates). All else being equal, it'll pick an arbitrary one (which currently happens to be the one the lower IP address if you just write out the digits). The idea that you should prefer the address that gives you the most benefit makes sense, but the "arbitrary" bit when there is a tie isn't very helpful.

This is something I'd like to do something about, and indeed using `NetworkPartitions` is an attractive option. I've also thought of allowing the configuration to specify a cost for sending a packet over an interface (and perhaps do both). Neither hasn't been done yet, although that "cost" idea is partially implemented by assigning lower cost to a loopback interface and Iceoryx than to other network interfaces and could probably be done with a small patch.

**Comment by thijsmie** [comment]
The features discussed here were merged and also updated since then 🎉
