### ISSUE TITLE
Functions in header files but missing in library .so

### ISSUE THREAD

**Issue by jeanmarline** [eclipse-cyclonedds/cyclonedds#75]
While generating the jna interface for java API we noticed that the following functions are defined in headers file but there are no corresponding symbols in libddsc.so : 
dds_ssl_plugin
dds_durability_plugin
dds__builtin_participant_cb
dds__builtin_cmparticipant_cb
dds_set_allocator
dds_set_aligned_allocator
dds_rhc_add_waitset
dds_rhc_remove_waitset
dds_stream_from_buffer
dds_ssl_plugin
dds_durability_plugin
serdata_hash

**Comment by eboasson** [comment]
@jeanmarline, thanks for compiling this list. I'll try to figure out where came from and whether they are indeed remnants of things that have been removed a long time ago or not. In all likelihood they are, and in that case I'll delete them.
