### ISSUE TITLE
New tag for the 0.8.0/iceoryx branch for ROS 2 Rolling

### ISSUE THREAD

**Issue by clalancette** [eclipse-cyclonedds/cyclonedds#760]
It looks like there are a few fixes on the iceoryx branch for CycloneDDS since the last tag (0.8.0beta3).  Could we please have a new tag so we can get those fixes released into the binary Debian packages for Rolling?  Thanks.

**Comment by cottsay** [comment]
In particular, it looks like the lack of #755 is causing the `rmw_cyclonedds` build to fail: https://build.ros2.org/job/Rbin_uF64__rmw_cyclonedds_cpp__ubuntu_focal_amd64__binary/97/

**Comment by eboasson** [comment]
Done. I hadn't realised you were building tagged versions only at the moment, I'll try not to keep that detail in mind from no won.

**Comment by clalancette** [comment]
> Done. I hadn't realised you were building tagged versions only at the moment, I'll try not to keep that detail in mind from no won.

While we *can* build non-tagged versions, it is more difficult in our infrastructure to do so.

At the end of the day, this was my fault.  I didn't realize that an updated `rmw_cyclonedds_cpp` package wouldn't build without an updated `cyclonedds`.  I released the former, and then we didn't have a tag for the latter.

In any case, thanks @eboasson for the new tag.  We'll do a new release of CycloneDDS with that.
