### ISSUE TITLE
How to use log function for cyclonedds?

### ISSUE THREAD

**Issue by raiars** [eclipse-cyclonedds/cyclonedds#77]
Hi, I've been trying with log functions for cyclonedds. dds_public_log.h is included in my project, but when I use it nothing happens. How can I use it in a proper way? Thanks!

**Comment by eboasson** [comment]
Hi @raiars, I'm sorry, but I can't quite figure out exactly what you are doing ... not even sure whether you are using them in conjunction with Cyclone or standalone ...

If you're trying to use it as a standalone logging facility, that's cool but not really something we have given thought to. In that case, you'll probably have to dig through the initialisation code and some of the thread management code to figure out which bit you're missing. There might be some hint here in test code as well: https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/os/tests/log.c

Feel free to give some more details on what exactly you are doing. With a bit more information I might be able to help you better.

**Comment by eboasson** [comment]
Presumably no longer relevant ... so closing it.
