### ISSUE TITLE
Use enum as key in IDL

### ISSUE THREAD

**Issue by evshary** [eclipse-cyclonedds/cyclonedds#804]
I met some problems while using enum as key in IDL. It seems that enum can't be key in the latest CycloneDDS.

How to reproduce:

1. Get the latest CycloneDDS
```bash
git clone https://github.com/eclipse-cyclonedds/cyclonedds.git
```

2. Modify the example code Helloworld IDL `examples/helloworld/HelloWorldData.idl` like the following:
```
module HelloWorldData
{
  enum TYPE {
    TYPE1,
    TYPE2
  };
  struct Msg
  {
    long userID;
    string message;
    TYPE type;
  };
  #pragma keylist Msg type
}; 
```

3. Build the code
```bash
cmake -DBUILD_EXAMPLES=ON -Bbuild -H. && cmake --build build
```

4. Then it'll pop up the following error message.
```
/home/chenying/cyclonedds/examples/helloworld/HelloWorldData.idl:13:21: Invalid key 'type' type in keylist directive
examples/helloworld/CMakeFiles/HelloWorldData_lib_generate.dir/build.make:62: recipe for target 'examples/helloworld/HelloWorldData.c' failed
make[2]: *** [examples/helloworld/HelloWorldData.c] Error 1
CMakeFiles/Makefile2:1125: recipe for target 'examples/helloworld/CMakeFiles/HelloWorldData_lib_generate.dir/all' failed
make[1]: *** [examples/helloworld/CMakeFiles/HelloWorldData_lib_generate.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

However, the problem doesn't exist in version 0.7.0. I'm not sure whether it's legal to use enum as key in IDL.
If it's ok to use, maybe the problem is related to the if-condition here:
https://github.com/eclipse-cyclonedds/cyclonedds/blob/46eda2d7786b55ca9704470b58c15cff3b93621f/src/idl/src/directive.c#L339

**Comment by k0ekk0ek** [comment]
Thanks for reporting @evshary. Much appreciated! Seems we don't allow arrays of primitive types either, which is allowed by the IDL3.5(?) spec, and with IDL4 there are no restrictions at all.
