### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by zhenfei0601** [eclipse-cyclonedds/cyclonedds#81]
/*
 * Copyright(c) 2006 to 2018 ADLINK Technology Limited and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */

As the code said, this project is licensed with epl-v2.0 or edl-v1.0.
But it seems that those two licenses have some conflict.
Such as the epl-v2.0 required all the modified code need to be open, but the edl-v1.0 does not have the requirement.

So if we import the Cyclone into our project, do we need to open all the code which we have modified.

**Comment by k0ekk0ek** [comment]
Hi @zhenfei0601,

I've given my personal interpretation below. It may be correct, but I'm certainly not a lawyer. I think it's best to check with the Eclipse Foundation. They can be reached via email at license@eclipse.org.

If I read the license text, which does not follow the EPL-2.0 with Secondary License format example, I'd say it indeed appears to be dual-licensed under either the EPL-2.0 or the EDL-1.0. I think you are allowed to choose whichever license suits you best.

If my interpretation is correct, and you choose to go with the EDL-1.0, I don't think you are obligated to publish modifications to the sources, whereas with the EPL-2.0 you must publish them at least on request.

**Comment by hansvanthag** [comment]
Like other projects within Eclipse, CycloneDDS is indeed dual-licensed where the EDL addition allows to incorporate the code in non-opensource projects without any 'contamination' (i.e. without the need to open any other code)

**Comment by zhenfei0601** [comment]
Thanks for all the answers!
