### ISSUE TITLE
Compatibility between opendds and cyclonedds

### ISSUE THREAD

**Issue by Yingliangzhe** [eclipse-cyclonedds/cyclonedds#813]
Hello everyone,
I have a question about the compartibility of opendds as mentioned in title. Because I would like to use the zenoh plugin dds, which is leveraging the cyclone DDS to discover the reader and writer. But I'm not sure, if the zenoh plugin dds will really find the reader and writer, which are implemented using opendds. If the opendds and cyclone dds can interoperate, the zenoh plugin dds will find them. 
If I would like to write a publisher in opendds and a subscriber in cyclone. Would it be possible, that the subscriber receives the messages from the publisher, which is writen in opendds? Have you already tested the compartibility? 
Thank you!

**Comment by eboasson** [comment]
Hi @Yingliangzhe, interoperability with OpenDDS has been demonstrated in the past and it should still be fine. However, it doesn't get tested regularly and with a fairly complex system like DDS, there's always the chance that something broke. If you run into something, just file an issue and we'll do our best to help.

**Comment by thijsmie** [comment]
No further feedback was received, so I am assuming no problems where encountered.
