### ISSUE TITLE
What's the meaning of payload._release and payload._maximum,

### ISSUE THREAD

**Issue by lygstate** [eclipse-cyclonedds/cyclonedds#815]
The generate header have no document about it

https://github.com/eclipse-cyclonedds/cyclonedds/blob/46eda2d7786b55ca9704470b58c15cff3b93621f/examples/roundtrip/ping.c#L295

**Comment by k0ekk0ek** [comment]
Hi @lygstate! Sequence types can be bounded, aka can have a maximum number of elements defined for them, that's the *_maximum* member of the struct you mention. The *_release* member indicates whether or not the buffer with individual elements of that sequence should be freed if you use the associated free function, in this case `RoundTripModule_DataType_free`. Important to note is that the buffer must have been allocated with the relative alloc function (`dds_sequence_octet_allocbuf` in this case). While currently they are simply mapped to `free` and `malloc` respectively, that could potentially change in the future.
