### ISSUE TITLE
Why I cannot find idlc_generate() when I cmake helloworld? 

### ISSUE THREAD

**Issue by I4learn** [eclipse-cyclonedds/cyclonedds#817]
I installed cyclonedds in usr/local,I have added it in environment variables.

**Comment by k0ekk0ek** [comment]
Hi @I4learn! That definitely shouldn't be the case. Given that the example builds fine in our CI setup, could it be that you have not used `find_package(CycloneDDS REQUIRED)` to locate Eclipse Cyclone DDS in the project you're trying to build?

**Comment by thijsmie** [comment]
No further feedback was received, so I am assuming the proposed fix worked.
