### ISSUE TITLE
What are the dual licenses this package is available under

### ISSUE THREAD

**Issue by fizanaaz1995** [eclipse-cyclonedds/cyclonedds#821]
is it EPL 2.0 and EDL 1.0

or

EPL 2.0 and BSD 3 clause ?

**Comment by eboasson** [comment]
Officially it is EPL 2.0 + EDL 1.0, but EDL 1.0 is identical to BSD 3-clause. When we can't reference EDL somewhere, for example because there's no standard license identifier for it, we have to use BSD 3-clause instead.
