### ISSUE TITLE
Implementing Certificate Revocation Lists in Secure communications

### ISSUE THREAD

**Issue by clalancette** [eclipse-cyclonedds/cyclonedds#829]
One of the projects I'm working on has a need to use Certificate Revocation Lists.  Looking around at the code, it looks to me like this is not currently implemented: https://github.com/eclipse-cyclonedds/cyclonedds/blob/93c8f8420f11d898854902bd6386c4ae5c09e9a9/src/security/builtin_plugins/authentication/src/auth_utils.c#L484

I'd like to go ahead and implement this.  To start with, I just want to deal with CRLs that are available when the participant is created (reacting to CRLs that happen during runtime may also be needed, but I'll leave that for later).

From what I can tell, there are at least 3 ways that CRLs get made available to clients that want to use them:
1. Via [crlDistributionPoints](http://pkiglobe.org/crl_dist_points.html).  That is, it looks like a CA can embed a distribution point into a certificate, and then clients are expected to fetch the CRL from that distribution point to use it.
2. Via a standalone CRL file.  This is typically in the PEM format, and when using OpenSSL is generated by doing something like:
```
$ openssl ca -revoke enclaves/talker_listener/listener/cert.pem -keyfile private/ca.key.pem -cert public/ca.cert.pem -config crl_openssl.conf  # Revokes listener cert
$ openssl ca -gencrl -keyfile private/ca.key.pem -cert public/ca.cert.pem -out crl.pem -config crl_openssl.conf  # regenerates CRL with revoked cert
```

(I'm obviously leaving out a lot of details here; if you want a full example, let me know and I can provide instructions)

3. By appending the CRL to the public certificate as issued by the CA.  That is, generate a CRL PEM file as above, and then concatenate it onto the public cert with:
```
cat crl.pem >> public/ca.cert.pem
```

I've been playing around with Options 2 and 3 above.  I have a prototype locally successfully implements option 2.  The issue with option 2 is that we need some way for the application to tell Cyclone where the CRL file is.  We could possibly do that via QoS properties (like we do for the [identity CA](https://github.com/eclipse-cyclonedds/cyclonedds/blob/93c8f8420f11d898854902bd6386c4ae5c09e9a9/src/security/builtin_plugins/authentication/src/authentication.c#L703)), but that would be a non-standard extension to the [DDS-SECURITY spec](https://www.omg.org/spec/DDS-SECURITY/1.1/PDF).  Maybe there is some way to add non-standard things here that doesn't violate the spec; I'll admit to not having read it closely.

Option 3 could also work (instead of or in combination with Option 2), but is a lot more invasive.  In particular, to make it work we need to check more than just *one* X509 certificate in [verify_certificate](https://github.com/eclipse-cyclonedds/cyclonedds/blob/93c8f8420f11d898854902bd6386c4ae5c09e9a9/src/security/builtin_plugins/authentication/src/auth_utils.c#L476); we need to check all of the certificates that were in the public cert.  To successfully do that, we probably need to create an `X509_STORE` and pass that around instead of the `X509`, at which point we can have multiple parts in the cert.  The problem is that the `X509` object is passed around a lot, so we'd have to rework a lot of the authentication APIs to pass along an `X509_STORE` instead.

I'm willing to do whichever we think is better, but I'm looking for advice on which way to proceed.  Pinging @eboasson and  @dennis-adlink for any kind of advice here.  Thanks in advance!

**Comment by dennis-adlink** [comment]
For the first step, without support for CRL updates during runtime, I would pick option 2 (as option 1 does not allow to use a local CRL file, and 3 is more invasive as you mentioned). 

The DDS spec allows to use the property QoS for implementation-specific properties, and because the security spec does not provide a standardized way for CRL usage, I think this is the right way to pass the CRL to the plugin (URI with file or data scheme). Section 7.2.1 of the [DDS Security spec](https://www.omg.org/spec/DDS-SECURITY/1.1/PDF) shows the usage of implementation specific properties. So the property name could be something like `org.eclipse.cyclonedds.sec.auth.crl`. 

For a future implementation including support for runtime updates of the CRL, you could maybe build on the timed callback mechanism that is already used in the security plugins for permissions expiry and identity certificate expiry.

**Comment by clalancette** [comment]
> For the first step, without support for CRL updates during runtime, I would pick option 2 (as option 1 does not allow to use a local CRL file, and 3 is more invasive as you mentioned).

@dennis-adlink Fantastic, thanks for the feedback.  I'll go ahead and start working on a full-fledged implementation of Option 2.

> For a future implementation including support for runtime updates of the CRL, you could maybe build on the timed callback mechanism that is already used in the security plugins for permissions expiry and identity certificate expiry.

Yeah, that's kind of what I was thinking.  But I haven't thought through all of the implications of that.  I'll cross that bridge a little later.

**Comment by thijsmie** [comment]
Implementation for CRL was merged and released.
