### ISSUE TITLE
Cyclone DDS Package configuration file missing 

### ISSUE THREAD

**Issue by rahul19861986** [eclipse-cyclonedds/cyclonedds#843]
I had build cyclone dds with visual studio 2019, after build i was trying to build and run the basic helloword example 
im getting following error when i try to do so. Im pretty much new to Cmake and stuff,  can any one help in resolving this error ?

```
rkpsr@Rahul MINGW64 ~
$ cd cyclonedds

rkpsr@Rahul MINGW64 ~/cyclonedds (master)
$ cd examples

rkpsr@Rahul MINGW64 ~/cyclonedds/examples (master)
$ cd helloworld

rkpsr@Rahul MINGW64 ~/cyclonedds/examples/helloworld (master)
$ cd build

rkpsr@Rahul MINGW64 ~/cyclonedds/examples/helloworld/build (master)
$ cmake ../
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
CMake Error at CMakeLists.txt:17 (find_package):
  By not providing "FindCycloneDDS.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CycloneDDS", but CMake did not find one.

  Could not find a package configuration file provided by "CycloneDDS" with
  any of the following names:

    CycloneDDSConfig.cmake
    cyclonedds-config.cmake

  Add the installation prefix of "CycloneDDS" to CMAKE_PREFIX_PATH or set
  "CycloneDDS_DIR" to a directory containing one of the above files.  If
  "CycloneDDS" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "C:/Users/rkpsr/cyclonedds/examples/helloworld/build/CMakeFiles/CMakeOutput.log".

rkpsr@Rahul MINGW64 ~/cyclonedds/examples/helloworld/build (master)
$
```

**Comment by eboasson** [comment]
This is simple CMake informing you that it can't find the installed Cyclone build. I assume you have followed the README by specifying a `CMAKE_INSTALL_PREFIX` when building it:
```
$ cd build
$ cmake -G "<generator-name>" -DCMAKE_INSTALL_PREFIX=<install-location> -DBUILD_EXAMPLES=ON ..
$ cmake --build . --target install
```

That installs it whatever directory you substituted for the `<install-location>` placeholder in the above.

CMake doesn't maintain a global registry of any kind when you install something and when you want to use it you therefore generally have to specify where it can find the package. If you add `<install-location>` to the `CMAKE_PREFIX_PATH` like CMake suggests (e.g., do `cmake ... -DCMAKE_PREFIX_PATH=<install-location> ...`) it should be able to find the installed files.

All this is perfectly well documented and accessible via Google in many different places.

**Comment by rahul19861986** [comment]
Thanks for the reply
