### ISSUE TITLE
Parameters of wrong type used for dds_delete and dds_entity_lock

### ISSUE THREAD

**Issue by FirasSahliADLinktech** [eclipse-cyclonedds/cyclonedds#86]
In the file dds_entity.c on line 84 the parameter (e->m_hdl ) was provided to dds_entity_lock this parameter is of the type ( ut_handle_t) but a parameter of the type dds_entity_t is expected.
The same issue appears in the implementation of the function dds_delete_impl on line 373 ( (dds_delete(child->m_hdl) ).

**Comment by k0ekk0ek** [comment]
I agree that this is a little weird. It's correct, they both represent the same thing. It's probably to hide the handle server types from the DDS api. It's likely the handle server should actually just be moved to the DDS module(?).

**Comment by eboasson** [comment]
This has all been subject to pretty massive rewrites and I think it's gone. In any case, a dds_entity_t = a dds_return_t = a dds_handle_t = a int32_t by design, and this being C, the types are simply aliases and the distinction is only there as a hint.

If only it were Ada ...
