### ISSUE TITLE
Interoperability between Cyclonedds and OpenSplice

### ISSUE THREAD

**Issue by Lirx93** [eclipse-cyclonedds/cyclonedds#868]
Hi friends,

I have some problems when testing interoperability between Cyclonedds-cxx with OpenSplice. The example I used is the helloworld example. The idl is shown below.

`module HelloWorldData
{
  struct Msg
  {
    long userID;
    string message;
  };
  #pragma keylist Msg userID
};`

On the subscriber side, I used CycloneDDS on the Ubuntu Linux and the OpenSplice is used on the publisher side which is Windows.  The two machines are in the same local network.  The steps I did is shown below.

1. Run ./ddscxxHelloworldSubscriber on the the Ubuntu Linux 
2. Run sacs_helloworld_pub.exe on the Windows

However the subscriber didn't receive any messages.  So is it possible to make Cyclone DDS work with Opensplice, if yes, could you please tell me how I should do?

Thanks.

**Comment by ThijsSassen** [comment]
Hi @Lirx93, The helloworld C# example from OpenSplice is using a partition called "HelloWorld example" to send data to. The cxx helloworld example from Cyclone DDS does not use a partition so they will not be able to communicate with each other. To make it work you either have to adjust the CycloneDDS example to publish in the  "HelloWorld example" partition or remove the partition from the C# example from OpenSplice.

**Comment by Lirx93** [comment]
Hi @ThijsSassen, Thanks sincerely. I will have a try immediately :)

**Comment by Lirx93** [comment]
Hi @ThijsSassen, thanks for your response. 

I make a test according to your suggestion, I have made the partition name is both "HelloWorld example" in the Opensplice helloworld C# project and the CycloneDDS helloworld C++ project. But the subscriber didn't receive any messages from the publisher also.

The CycloneDDS code for setting the partition is shown below.
```
dds::pub::qos::PublisherQos pub_qos = participant.default_publisher_qos();
pub_qos << dds::core::policy::Partition("HelloWorld example");
dds::topic::Topic<HelloWorldData::Msg> topic(participant, "HelloWorldData_Msg");
dds::pub::Publisher publisher(participant, pub_qos);
```

The code of the OpenSplice helloworld example is not modified.

The OpenSplice cofiguration file is 
```
<OpenSplice>
    <Domain>
        <Name>ospl_sp_ddsi</Name>
        <Id>0</Id>
        <SingleProcess>true</SingleProcess>
        <Description>Stand-alone 'single-process' deployment and standard DDSI networking.</Description>
        <Service name="ddsi2">
            <Command>ddsi2</Command>
        </Service>
    </Domain>
    <DDSI2Service name="ddsi2">
        <General>
            <NetworkInterfaceAddress>AUTO</NetworkInterfaceAddress>
            <AllowMulticast>true</AllowMulticast>
            <EnableMulticastLoopback>true</EnableMulticastLoopback>
            <CoexistWithNativeNetworking>false</CoexistWithNativeNetworking>
        </General>
        <Compatibility>
            <!-- see the release notes and/or the OpenSplice configurator on DDSI interoperability -->
            <StandardsConformance>lax</StandardsConformance>
            <!-- the following one is necessary only for TwinOaks CoreDX DDS compatibility -->
            <!-- <ExplicitlyPublishQosSetToDefault>true</ExplicitlyPublishQosSetToDefault> -->
        </Compatibility>
    </DDSI2Service>
</OpenSplice>
```


The CycloneDDS configuration is 

```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <NetworkInterfaceAddress>auto</NetworkInterfaceAddress>
            <AllowMulticast>default</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```


Could you please help give some suggestions why OpenSplice can't interoperate with CycloneDDS?

**Comment by hansvanthag** [comment]
Hi, 
I'd guess its the durability QoS setting that for the OpenSplice example is set to Transient (via the example's entitymanager setting of the topic-QoS that serves as a default when creating the publisher/subscriber) whereas for the Cyclone example I believe its left 'default' i.e. 'Volatile', which would result in a RxO QoS-mismatch and thus won't communicate. As Cyclone doesn't yet support transient data, you might want to change the OpenSplice example to use a Volatile reader also.

**Comment by hansvanthag** [comment]
As the above provides some 'objective evidence' that OpenSplice and Cyclone DO interoperate, I'd suggest to close this issue ..

**Comment by k0ekk0ek** [comment]
Feel free to do so @hansvanthag :+1:
