### ISSUE TITLE
Multi QueryConditions on one DataWriter

### ISSUE THREAD

**Issue by raiars** [eclipse-cyclonedds/cyclonedds#87]
Hi, we are in the situation that one datareader needs different queryconditions on it to read different data samples with different keys. When one data sample(for example, key = i) comes, it will trigger its corresponding waitset that attach a querycondition(key == i).
When we test it on CycloneDDS, it seems Cyclone currently lacks support for this situation. When different queryconditions created simultaneously in different threads on one datareader, the waitset always return 0 without even reach the desiring wait time(it will return 0 as soon as dds_waitset_wait is executed). Even in one thread, when we create and delete queryconditions multi times, it may fail with the same result. Is it a bug or functions not supported yet?

**Comment by raiars** [comment]
I have narrowed down the problem that for even one querycondition on one waitset, when one data sample cannot satisfy the querycondition, the samples coming next will never go through the querycondition any more. 
It shows that the code gets into if(m_pre == m_post) which will will not go through querycondition, is this a bug? What does the variable m_pre and m_post do in this case?
![image](https://user-images.githubusercontent.com/11205435/50875336-d8b8f180-1402-11e9-939b-e405d6ad22bf.png)

**Comment by raiars** [comment]
Hi, bugs found!  I found there are two kind of bugs in two situations.
First, when one data sample comes into rhc, if there is not read data samples in rhc, mpre will be (0, 1).  After the data sample stores into rhc, mpost will also be (0, 1), which all means there are data samples not read. In this situation, m_pre == m_post, which will not trigger waitset for the lastest data sample.
Second, when two queryconditions both active in one rhc, if one is triggered while another is not. The untriggerd querycondition will keeps it m_trigger to be 0. However, after taken the data sample, rhc will do minus 1 on both queryconditions which will cause the m_trigger of untriggered querycondition to be -1. In this case, the untriggered querycondition will trigger a waitset abnormally, which causes the bug.
![image](https://user-images.githubusercontent.com/11205435/51009783-7a1f7f00-158c-11e9-929b-d6362e789d5f.png)

**Comment by eboasson** [comment]
The waitset mechanism is level-triggered, and m_pre/m_post is supposed to implement an edge detector so that the actual work involved in waking up threads only happens the on the transition. With that in mind, I don't quite follow the first part of this:

> if there is not read data samples in rhc, mpre will be (0, 1). After the data sample stores into rhc, mpost will also be (0, 1), which all means there are data samples not read. In this situation, m_pre == m_post, which will not trigger waitset for the lastest data sample.

that is the correct behaviour for an edge detector for the state/view/instance states. It may well be there is a bug here, it is just that this detail is something I don't quite get just now. But going back to your earlier question:

> It shows that the code gets into if(m_pre == m_post) which will will not go through querycondition, is this a bug? What does the variable m_pre and m_post do in this case?

that seems to me to be a bug: if the RHC is in a state where it contains 1 sample that matches a query condition — and so the query's "m_trigger" would be true — and that sample is overwritten by one that doesn't match the query, then it may well be that ``m_pre == m_post`` and yet the trigger is no longer there. I wouldn't mind if all that went wrong was a spurious wake up, but I don't see how the query's ``m_trigger`` would be cleared in that case. So it wouldn't be limited to single spurious wake up.

Short summary: ``m_pre`` and ``m_post`` only deal with the sample/view/instance states. So while avoiding evaluating a query condition is attractive, you'd better have proof that it is safe to avoid it. And I don't see that here.

This bit:

> However, after taken the data sample, rhc will do minus 1 on both queryconditions which will cause the m_trigger of untriggered querycondition to be -1. In this case, the untriggered querycondition will trigger a waitset abnormally, which causes the bug.

is pretty obviously a bug.

I guess it is time to me to dive into the details of the query conditions ... I'll admit to a certain level of repsonsibility for the sample/view/instance state triggering, but the query conditions come from elsewhere. So it may take a bit of study time to figure out what exactly to do — but you definitely have my attention ☺️👍🏻

**Comment by raiars** [comment]
Thanks for your reply! For the first bug, I wrote down a diagram for the situation that may be caused by it. Maybe you can have a look☺️
![img_1182](https://user-images.githubusercontent.com/11205435/51118120-90f2f980-184a-11e9-92ca-931999de6e7c.JPG)

**Comment by eboasson** [comment]
Hi @raiars ,

I just wanted to give you an update of the direction I intend to go to solve these problems. I have been looking into the way query conditions were originally built into Cyclone, and I think I'll have to do some real surgery, as I have found a couple more suspicious things by inspection ... For example, when you create a read condition it checks whether it matches some data given the then-current state of the reader history, but it doesn't do so for a query condition. Nonetheless it then continues as-if the query conditions can be evaluated incrementally, even though it is quite obvious that one can't incrementally evaluate something given an undefined starting point.

This continual incremental evaluation is done for the benefit of waitset triggering. This makes sense, but one might also want to use conditions without attaching them to a waitset. For read conditions, I expect this to be fairly rare (it is just a bitmask that you can also pass into the read function directly) and evaluating a them is pretty cheap; for query conditions, it makes much more sense to create them just for reading as it is the only way one can filter on the content of the data while reading/taking. To make matters worse, every sample needs to be checked, which for the current interface [*] even requires deserialisation. That means it can't be considered cheap.

So one change I intend to make is to distinguish between conditions that exist but are not currently attached to a waitset, and those that are attached to a waitset. Only the latter will then be included in the incremental evaluation. I _think_ it is reasonable to expect no more than a handful of query conditions on a given reader, and that offers the interesting possibility of adding a bitmask to each sample that tells you which conditions are met by that sample.

The attach-to-waitset operation will then select a bit in that bitmask from the currently unused bits, evaluate the condition against all samples, setting the bit accordingly. Once that's been done, the evaluation need then only be done when inserting the sample into the cache. Maintaining the trigger status then becomes a pretty straightforward bookkeeping exercise. (I am pretty sure the triggering bugs you ran into will disappear with this, hopefully without the introduction of new ones 😁.)

The other benefit is that a read/take with a query condition that is attached to a waitset will no longer have to evaluate the condition. That means the read/take gets to be (much) faster, at the cost of a slightly slower insertion (which is more spread out, so better for real-time behaviour given the simple locking strategy). If only a small fraction of the samples match, it should be faster overall.

Reading/taking with a query condition that is not attached to a waitset remains the same: the condition will simply have to be evaluated for each sample.

[*] The current interface has some issues ... the first is that it requires a completely deserialised sample, whereas I expect the typical filter to only check a few fields. Perhaps it could be constrained to not look inside sequences and unions.

The other problem I have with it is that it is quite useful to know whether the filter applies to key fields or attributes, or both: if, e.g., you know it selects a single key value, scanning all instances is quite a wasteful thing. Altogether, it is my preference to move towards the model that is used in the DCPS spec, where the condition is some expression that is parsed and then processed internally. That way the evaluation can reasonably operate on serialised data. Moreover, maintaining indices for improving query performance then also becomes a realistic — and I think attractive — option.

Some work will have to be done before that's possible though: the way the code currently deals with type descriptors is a bit too simplistic. So for now the interface will remain the same.

**Comment by eboasson** [comment]
Still on it ... the TLS bit sidetracked me a little bit, as does getting the paperwork in order for a first release, but it is pretty much back up on the priority list again.

**Comment by eboasson** [comment]
@raiars I didn't realise the issue would be closed automatically upon merging the pull request ... anyway, the problem really should be resolved now. If you could be so kind as to let me know whether this fits with your experience, that would be highly appreciated.
