### ISSUE TITLE
Why is 'Map' a syntax error with the 0.8.x idlc?

### ISSUE THREAD

**Issue by photex** [eclipse-cyclonedds/cyclonedds#892]
One of our existing IDL files defines an enum:

```
enum Frame {
    Map, // Map is a syntax error now?
    Odom,
    Base
  };
```

If I change 'Map' to 'Mapp' or '_Map' then the idl compiler carries on as usual. I thought that perhaps there is a new built-in Map datatype or so, but that was also not true.

**Comment by k0ekk0ek** [comment]
`map` is a reserved keyword (type) in IDL4 and IDL is case insensitive. But you can use the `-fcase-sensitive` compiler option to make the compiler be case sensitive. The case sensitivity is only important for some languages, none of which are currently supported by Cyclone DDS.

**Comment by photex** [comment]
Thank you for explaining! :D -fcase-sensitive definitely fixes the issue. But I think we'll plan to replace any usage of 'map' going forward in order to be in-line with the specification.
