### ISSUE TITLE
0.8.x idlc makes every struct a topic by default

### ISSUE THREAD

**Issue by photex** [eclipse-cyclonedds/cyclonedds#893]
Hello again!

We have a lot of structs. They aren't all intended to be topics. If we use the `#pragma keylist` approach to defining keys then things work as they did in 0.7.x (Only generating topic descriptors for structs with a key defined). 
If we switch to using the `@key` annotation, then everything gets a topic description, while only those structs with keys get the keylist in their description.

Is this expected?

**Comment by k0ekk0ek** [comment]
Hey @photex! Nice to see you back :slightly_smiling_face: The `#pragma keylist` vs `@key` is indeed a little weird. If you want to suppress all types being topics, then IDL4 has the `@nested` (structs/unions) and `@default_nested` (modules) annotations. By default `@nested` is false, so a descriptor and such will be generated. You can annotate using `@nested(TRUE)` to stop type support from being generated or annotate the module with `@default_nested(TRUE)` and then use `@nested(FALSE)` on a per topic base. That being said, you can also use `-fkeylist` to keep using keylists. The compiler tries to be smart about it, but will choose IDL4 compatibility if no `#pragma keylist` is encountered.

**Comment by photex** [comment]
Interesting! Thank you for explaining.

How do topics without a key work then? Are they essentially all considered unique instances in this case?

**Comment by k0ekk0ek** [comment]
I'm actually not sure. They're keyless, so that'd imply they're indeed all unique, but I'm not sure if in that case the entire struct is considered a key or not (instances vs samples). @eboasson? You probably know from the top of your head?

**Comment by photex** [comment]
It is a relatively useful thing to be able to use. In particular this lets us more easily handle streams of certain data I think. For example, object lists from our perception system can now be written without batching them into a sequence first, and our map node can integrate them from an array of samples instead of a sequence in a sample.

**Comment by hansvanthag** [comment]
In my understanding, a keyless topic is a 'single-place-buffer' i.e. a single-instance. So the contents (of a structure) itself is NOT considered a/the key ..

**Comment by eboasson** [comment]
@hansvanthag is correct: for keyless topics, there is only a single instance.
