### ISSUE TITLE
IDLC C code generation ignores structure inheritance

### ISSUE THREAD

**Issue by eboasson** [eclipse-cyclonedds/cyclonedds#897]
That is, with this input:
```IDL
struct A { long x; };
struct B : struct A { long y; };
```
I would expect that `B`'s inheriting `A` would not be silently discarded when generating C code. I haven't been able to find an IDL4-to-C mapping specification on the OMG website — IDL4.0 is a mere 5 years old, I am no doubt being unreasonable in expecting one already — so perhaps it is as simple as a missing error message.

However, with a frontend and C++ backend that support it, it would probably be better to do a provisional mapping to C. I think something as simple as:
```C
struct A { int32_t x; };
struct B { struct A _parent; int32_t y; };
```
would take core it.

**Comment by eboasson** [comment]
Should've thought of it (thanks @e-hndrks!): it is in the XTypes spec:

> 7.5.1.4.1.3 Other Programming Languages
> The language binding shall be generated as if an instance of the base type were the first member of the subtype with the name “parent,” as in the following equivalent IDL definition:
>```
> struct <struct_name> { <base_type_name> parent; // ... other members
> };
> ```

so it is actually defined and quite straightforward.

**Comment by trittsv** [comment]
@eboasson is there any plan in which release this issue will be fixed?

**Comment by dennis-adlink** [comment]
@trittsv I'm currently working on the implementation for structures (union inheritance will be implemented later). This is my work-in-progress version: https://github.com/dennis-adlink/cyclonedds/tree/idlc_inheritance

I think this generates the correct types and serializer instructions, but I've to do some more testing and check the CI results before creating a PR. But you could give this a try and see if it works for you (it is based on Cyclone master).

**Comment by trittsv** [comment]
@dennis-adlink can this issue be closed due to the merge of #1011 ?

**Comment by dennis-adlink** [comment]
@trittsv Yes, it can be closed, thanks. In case you run into any issue (related or unrelated to this one) or if you have further questions, please don't hesitate to open a new issue! 

@eboasson can you please close this one?

**Comment by eboasson** [comment]
> @eboasson can you please close this one?

With pleausre!
