### ISSUE TITLE
lookup_thread_state_real bug found

### ISSUE THREAD

**Issue by raiars** [eclipse-cyclonedds/cyclonedds#91]
Hi, I found a bug for thread management for user application threads. 
Imagine the usecase: the user is creating multiple threads in a for loop.(5 threads created, once they done, 5 new threads created again). In this case, thread id for a new thread may be same with that of an old thread(which is finished by the user application).  
However, in Cyclone thread management, the old application thread information will be recorded in the global thread pool.
Function lookup_thread_state:
```C
    if ((ts1 = tsd_thread_state) == NULL) {
        if ((ts1 = lookup_thread_state_real()) == NULL) {
            /* this situation only arises for threads that were not created
               using create_thread, aka application threads. since registering

               thread state should be fully automatic the name will simply be
               the identifier */
            tid = os_threadIdSelf();
            (void)snprintf(
                tname, sizeof(tname), "0x%"PRIxMAX, os_threadIdToInteger(tid));
            os_mutexLock(&thread_states.lock);
            ts1 = init_thread_state(tname);
            if (ts1 != NULL) {
                os_osInit();
                ts1->extTid = tid;
                ts1->tid = tid;   //The old thread information is recorded here!
                DDS_LOG(DDS_LC_INFO, "started application thread %s\n", tname);
                os_threadCleanupPush(&cleanup_thread_state, NULL);
            }
            assert(ts1->state == THREAD_STATE_ALIVE);
            os_mutexUnlock(&thread_states.lock);
        }
        tsd_thread_state = ts1;
    }
```
When a new thread with the same thread id comes, it will step into lookup_thread_state_real function. It will satisfy os_threadEqual (thread_states.ts[i].tid, tid) condition and return the information about an old thread. Then it will cause two real threads to both acquire one cyclone thread in the pool. This may cause unexpected problems. Can you have a look at it?
```C
struct thread_state1 *lookup_thread_state_real (void)
{
  if (thread_states.ts) {
    os_threadId tid = os_threadIdSelf ();
    unsigned i;
    for (i = 0; i < thread_states.nthreads; i++) {
      if (os_threadEqual (thread_states.ts[i].tid, tid) ) {   //The new thread with the same thread id will satisfy this condition
        return &thread_states.ts[i];  //An old finished thread information can be returned here!
      }
    }
  }
  return NULL;
}
```

**Comment by raiars** [comment]
My Solution is just not to store a user application thread id into the global pool and it seems work fine. ^_^

**Comment by eboasson** [comment]
> My Solution is just not to store a user application thread id into the global pool and it seems work fine. ^_^

But you do given them entries in ``thread_states.ts``, right? It needs them for the awake/asleep toggling in all API operations that are important for garbage collecting. But then, how do you free them (or is there no problem with that for you)?

> When a new thread with the same thread id comes, it will step into lookup_thread_state_real function. It will satisfy os_threadEqual (thread_states.ts[i].tid, tid) condition and return the information about an old thread. Then it will cause two real threads to both acquire one cyclone thread in the pool. This may cause unexpected problems. Can you have a look at it?

Surely if it gets the same thread id, the old one should be gone, and then it really _should_ be safe the reuse the slot. I can see two possible issues there (without having gotten around to trying it): firstly, there might well be some nastiness with reusing it because of some left-over state; and secondly, I don't know how exactly how ``os_threadCleanupPush`` will behave on all platforms, but I can imagine it can happen with a bit of a delay on some platforms, in which case, yes, trouble might ensue.

Which OS are you using? I'd like to understand what happens exactly ...

**Comment by raiars** [comment]
Hi, I did some modification on my use case and it works fine with DDS right now! It seems that I created too many threads before... but I do encounter the situation that two real threads get one virtual DDS thread from the pool before. And one thread attempt to do some modification on thread's vtime with state THREAD_STATE_ZERO and it causes assert vtime error on another thread. 
![image](https://user-images.githubusercontent.com/11205435/51300496-0f2be780-1a67-11e9-9c17-5cc7643c8aa5.png)
![image](https://user-images.githubusercontent.com/11205435/51300573-5d40eb00-1a67-11e9-8bac-49af7db055d8.png)
 I'm currently using Ubuntu16 for test. Right now it works fine for my use case. But my question is, for user  application threads, how do Cyclone clear its state in the virtual thread pool? Will the termination on a user application thread notify Cyclone? If not, how can Cyclone make sure that the new thread with the already existing thread ID will not get the old thread information? Thanks!

**Comment by eboasson** [comment]
Closing — there were definitely some ways in which application threads that survived domain shutdown & library deinitialization could get into trouble when the cleanup routine at the end of the thread's lifetime was invoked, but those are now worked around by leaking thread states if the absence of such threads can't be proved.

I hope the problem doesn't rear its ugly head again ...
