### ISSUE TITLE
Configuration guide needs updating

### ISSUE THREAD

**Issue by eboasson** [eclipse-cyclonedds/cyclonedds#914]
There is a guide to configuring Cyclone that attempts to give some background information to aid in navigating the scores of settings: https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/config.rst. There was at least one bug (fixed by #913) but it is highly unlikely that that was the only one.

There have also been quite a few changes to Cyclone since that document was last updated, so it needs updating.

**Comment by poetinger** [comment]
I believe the updates by @PeterCadogan fixed most of the problems with the configuration guide. So I will close this now, and if further discrepancies are found we can open individual issues for them.
