### ISSUE TITLE
Error while cross compiling with yocto

### ISSUE THREAD

**Issue by mtudan** [eclipse-cyclonedds/cyclonedds#915]
Hi,

I am trying to cross compile `cyclonedds` `0.8.0rc1` release using yocto project but I got the following configuration error:
```
| -- Configuring incomplete, errors occurred!
| See also "/home/ubuntu/yocto/build/tmp/work/cortexa7t2hf-neon-linux-gnueabi/cyclonedds/0.8.0rc1-r0/build/CMakeFiles/CMakeOutput.log".
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/home/ubuntu/yocto/build/tmp/work/cortexa7t2hf-neon-linux-gnueabi/cyclonedds/0.8.0rc1-r0/temp/run.do_configure.29481' failed with exit code 1:
| -- The C compiler identification is GNU 10.2.0
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Check for working C compiler: /home/ubuntu/yocto/build/tmp/work/cortexa7t2hf-neon-linux-gnueabi/cyclonedds/0.8.0rc1-r0/recipe-sysroot-native/usr/bin/arm-linux-gnueabi/arm-linux-gnueabi-gcc - skipped
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Setting build type to 'RelWithDebInfo' as none was specified.
| -- Linux/MacOS system found, trying to find iceoryx...
| -- iceoryx not found, falling back to loopback communication.
| -- Found OpenSSL: /home/ubuntu/yocto/build/tmp/work/cortexa7t2hf-neon-linux-gnueabi/cyclonedds/0.8.0rc1-r0/recipe-sysroot/usr/lib/libcrypto.so (found version "1.1.1j")
| -- Building with OpenSSL support
| CMake Error at src/tools/ddsconf/CMakeLists.txt:13 (find_program):
|   Could not find DDSCONF_EXECUTABLE using the following names: ddsconf
```
It seems that the error comes form the following `CMakeLists.txt` file:
https://github.com/eclipse-cyclonedds/cyclonedds/blob/0.8.0rc1/src/tools/ddsconf/CMakeLists.txt#L12

**Comment by sjames** [comment]
Cyclone needs the ddsconf executable to build, and this needs to be built for the host.  Here is how I solved it.

https://raw.githubusercontent.com/sjames/sabaton-ndk/main/yocto/meta-sabaton/recipes-connectivity/cyclonedds/cyclonedds.inc

We make the recipe depend on its native version,

`BBCLASSEXTEND = "native"

DEPENDS = "openssl cyclonedds-native iceoryx"
RDEPENDS_${PN} = ""`

And also install ddsperf in the do_install_append function. 

There may be a way to avoid the native build, but this involves installing the ddsperf into the host sysroot from the target build environment.  I'm not sure this can be done cleanly.  

Hope this helps.

**Comment by mtudan** [comment]
@sjames did you try to build [helloworld](https://github.com/eclipse-cyclonedds/cyclonedds/tree/master/examples/helloworld) example using yocto as well? It fails for me when trying to [find CycloneDDS cmake package](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/examples/helloworld/CMakeLists.txt#L17). Apparently it finds it, but only from the native build:
```
| CMake Error at CMakeLists.txt:17 (find_package):
|   Could not find a configuration file for package "CycloneDDS" that is
|   compatible with requested version "".
| 
|   The following configuration files were considered but not accepted:
| 
|     build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/cyclonedds/0.8.0rc2-r0/recipe-sysroot-native/usr/lib/cmake/CycloneDDS/CycloneDDSConfig.cmake, version: 0.8.0 (64bit)
```

**Comment by mtudan** [comment]
After changing machine to the `raspberrypi4-64`, build passes little further but fails at calling the `idlc_generate()` function:
```
| CMake Error at CMakeLists.txt:24 (idlc_generate):
|   Unknown CMake command "idlc_generate".
```

**Comment by sjames** [comment]
I didn't try to build the example in Yocto as I just need the library in the SDK.   I think the native installation package must be modified to install the cmake modules.
