### ISSUE TITLE
head->aba_head.s.a should be discounted in ddsrt_atomic_lifo_pop

### ISSUE THREAD

**Issue by 12li-wei** [eclipse-cyclonedds/cyclonedds#924]
we found head->aba_head.s.a is still increasing after invoking ddsrt_atomic_lifo_pop, should it be discounted?
   after invoking ddsrt_atomic_lifo_init:
        x.aba_head.s.a=0,     x.aba_head.s.b=(nil)
    after invoking ddsrt_atomic_lifo_push:
        x.aba_head.s.a=1,     x.aba_head.s.b=0x7ffd04280d6e
    after invoking ddsrt_atomic_lifo_pop:
        x.aba_head.s.a=2,     x.aba_head.s.b=(nil)

fix patch is as following
======================================
>` void *ddsrt_atomic_lifo_pop (ddsrt_atomic_lifo_t *head, size_t linkoff) {`
>`   uintptr_t a0, b0, b1;`
>`   do {`
>`      .........`
>`----   } while (!ddsrt_atomic_casvoidp2 (&head->aba_head, a0, b0, a0+1, b1));`
>`+++   } while (!ddsrt_atomic_casvoidp2 (&head->aba_head, a0, b0, a0-1, b1));`
>`   return (void *) b0;`

**Comment by eboasson** [comment]
Hi @12li-wei, thanks for paying such close attention, but in this case it really is the intention to always increment it. This is a classic way to avoid the [ABA problem](https://en.wikipedia.org/wiki/Compare-and-swap#ABA_problem) and changing it to decrement in `pop` would defeat the purpose.
