### ISSUE TITLE
ExplicitlyPublishQosSetToDefault breaks reader and/or writer

### ISSUE THREAD

**Issue by gsnuffles** [eclipse-cyclonedds/cyclonedds#937]
I have a reader and a writer that communicate perfecly fine, but when I set `ExplicitlyPublishQosSetToDefault` to true on the reader or both of them, they do not communicate anymore and I get the error messages:

```
1631028312.388135 [1] dq.builtin: invalid parameter list (vendor 1.16, version 2.1): pid 74 (TYPE_CONSISTENCY_ENFORCEMENT) invalid, input = 1,0,255,255,0,0,0,0
1631028312.388187 [1] dq.builtin: SPDP (vendor 1.16): invalid qos/parameters
```

Any idea why this is happening?

Edit: Adding to my confusion is the inconsistency,  that this does not always happen.

**Comment by eboasson** [comment]
Looks like a bug to me, and this appears to solve it:
```
diff --git a/src/core/ddsi/src/ddsi_plist.c b/src/core/ddsi/src/ddsi_plist.c
index 8a7aa2f0..082c05e1 100644
--- a/src/core/ddsi/src/ddsi_plist.c
+++ b/src/core/ddsi/src/ddsi_plist.c
@@ -542,7 +542,7 @@ static dds_return_t ser_type_consistency (struct nn_xmsg *xmsg, nn_parameterid_t
   char * const p = nn_xmsg_addpar_bo (xmsg, pid, 8, bo);
   const uint16_t kind = ddsrt_toBO2u (bo, (uint16_t) x->kind);
   memcpy (p, &kind, 2);
-  size_t offs = sizeof (x->kind);
+  size_t offs = sizeof (kind);
   p[offs + 0] = x->force_type_validation;
   p[offs + 1] = x->ignore_sequence_bounds;
   p[offs + 2] = x->ignore_string_bounds;
```
`x->kind`4 bytes in memory (an enum) where the wire format requires two bytes. That means it incorrectly introduces two bytes of padding, left uninitialized (in your case the `255,255`). Booleans are expected in those bytes, and so it correctly rejects these values as invalid input. If you have a chance to confirm that this indeed fixes it, I'd be grateful. The deserializer doesn't have this issue.

It hasn't been seen because the CI runs with the default setting for `ExplicitlyPublishQosSetToDefault` and the value happens to always be the default value. (That should change with #904, because that introduces the code where non-default values for type consistency enforcement actually become meaningful.)

**Comment by gsnuffles** [comment]
@eboasson Wow, that was fast. Are those changes already committed to master or do I need to apply them manually?

**Comment by eboasson** [comment]
It came in at just the right moment 🙂

I only did the fun part, I haven't turned it into a PR yet, let alone merged it into master.

**Comment by dennis-adlink** [comment]
As it was a bug in code I wrote, I've created the PR (#938) for this issue. Thanks @gsnuffles for reporting the issue, and @eboasson for fixing the issue! And yes, in #904 I'll add tests that use the flags from the Type Consistency QoS, it's on my to-do list.

**Comment by gsnuffles** [comment]
An additional question, when using a Connext Micro writer with cyclonedds I get a similar error:

```
DDS Log Msg: invalid parameter list (vendor 1.10, version 2.1): pid 21 (PRESENTATION) invalid, input = 1,0,1,0,0,1,0,0
```

Does this have anything to do with this?

**Comment by eboasson** [comment]
The presentation QoS policy is specified as:
```IDL
// The types in this file shall be serialized with XCDR encoding version 1
enum PresentationQosPolicyAccessScopeKind {
  INSTANCE_PRESENTATION_QOS,
  TOPIC_PRESENTATION_QOS,
  GROUP_PRESENTATION_QOS
};
@extensibility(APPENDABLE) @nested
struct PresentationQosPolicy {
  PresentationQosPolicyAccessScopeKind access_scope;
  boolean coherent_access;
  boolean ordered_access;
};
```
The comment at the top and the `@extensibility(APPENDABLE) @nested` bit is added in the XTypes 1.3 spec, it wasn't there originally but it also doesn't affect the wire representation (indeed it can't or there would be no interoperability).

The `enum` is 32-bits with the only possible values {0,1,2}, the booleans are one byte each and must be in {0,1} for it to be well-formed. So I'd say that `1,0,1,0,0,1,0,0` really is invalid and Connext Micro is sending malformed discovery data.

**Comment by gsnuffles** [comment]
@eboasson: Thank you for the detailed explanation.

**Comment by gsnuffles** [comment]
I think this can be closed as it was solved by PR https://github.com/eclipse-cyclonedds/cyclonedds/pull/938.
