### ISSUE TITLE
Update serdata functions to handle sequences/strings with shared memory

### ISSUE THREAD

**Issue by MatthiasKillat** [eclipse-cyclonedds/cyclonedds#941]
### Feature

To support bounded and unbounded sequences as well as strings with shared memory we need to modify the serdata functions.

The goal is to be able serialize the sample into shared memory even if the data type has no fixed size (instead of using the network) for local readers.

### Details

The following is required:
 
1. Update the flag in iceoryx user header to indicate whether the iceorxy memory chunk is holding the data in serialized/deserialized format.
2. Modify the serdata function `ddsi_serdata_from_loaned_sample()` to serialize the data from the sample into the iceoryx memory chunk, when the type is not fixed
3. Modify the serdata function `ddsi_serdata_from_iox()` to deserialize the data from the iceoryx memory chunk to the sample, when the type is not fixed

### Technical Assumption

The work should be based on https://github.com/eclipse-cyclonedds/cyclonedds/pull/788, which needs to be merged before in this case.

**Comment by sumanth-nirmal** [comment]
@MatthiasKillat and @eboasson The changes for this are merged in https://github.com/eclipse-cyclonedds/cyclonedds/pull/1000, we could probably close this issue, no?

**Comment by thijsmie** [comment]
Was merged and closing was already suggested :smile:.
