### ISSUE TITLE
Limitation on ut_handles for entities.

### ISSUE THREAD

**Issue by raiars** [eclipse-cyclonedds/cyclonedds#95]
Hi, I've been testing with a large amount of WaitSets and I find there are not enough handles for WaitSets. For the handle server, I find that there is no recycle function for it and the limit(1000) will be soon reached if many entities are created (even they are deleted). Will you consider to add some recycle functions for the handle server?

**Comment by eboasson** [comment]
@raiars, I think you may have been notified of my having created a branch for this, but if not: I think the fix-95 branch might be worth your while.

**Comment by eboasson** [comment]
Fixed
