### ISSUE TITLE
Build error with bison-3.8.1

### ISSUE THREAD

**Issue by hhoffstaette** [eclipse-cyclonedds/cyclonedds#951]
When trying to build 0.8.0 on Gentoo (amd64) I got the following error:
```
holger>make
[ 18%] Built target ddsconf
[ 75%] Built target ddsc
[ 77%] Built target pubsub
[ 80%] Built target idlpp
Consolidate compiler generated dependencies of target idl
[ 81%] Building C object src/idl/CMakeFiles/idl.dir/parser.c.o
/home/holger/tmp/cyclonedds/build/src/idl/parser.c: In function 'idl_yypush_parse':
src/parser.y:1052:11: error: label 'yyreturn' used but not defined
src/parser.y: In function 'idl_iskeyword':
src/parser.y:1105:16: error: 'yytoknum' undeclared (first use in this function); did you mean 'toknum'?
src/parser.y:1105:16: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [src/idl/CMakeFiles/idl.dir/build.make:265: src/idl/CMakeFiles/idl.dir/parser.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:570: src/idl/CMakeFiles/idl.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
``` 

This seems to be caused by the recently released bison-3.8.1, which changed or dropped a lot of previously deprecated features, see [here](https://lists.gnu.org/archive/html/bug-bison/2021-09/msg00022.html).  I briefly looked into parser.y but offhand couldn't figure out how to fix these two erors myself.

**Comment by eboasson** [comment]
The CI ran into the same on macOS (and then I upgraded bison locally and got stuck with the same). #949 should do the trick, even if it relies on a quick hack.

**Comment by hhoffstaette** [comment]
The patches in #949 made it build immediately and everything seems to be working fire, incl. a quick ddsperf run. Thanks!

**Comment by k0ekk0ek** [comment]
Closing this issue as the patches have been merged and builds are up and running again. Thanks for reporting @hhoffstaette!
