### ISSUE TITLE
ROS2 galactic CycloneDDS crash

### ISSUE THREAD

**Issue by carteavcar01** [eclipse-cyclonedds/cyclonedds#955]
hey,
does anyone face with that log:
/tmp/binarydeb/ros-galactic-cyclonedds-0.8.0/src/core/ddsi/src/q_receive.c:3172: handle_submsg_sequence: Assertion `thread_is_asleep ()' failed

I've got a ground filter node, when one of the callback is called the node is crash and the log appear.

**Comment by eboasson** [comment]
Fixed in `0.8.0rc` — more details at https://github.com/ros2/rmw_cyclonedds/issues/338

**Comment by thijsmie** [comment]
Fix merged and released.
